$axure.loadCurrentPage({
  "url":"需求场景描述.html",
  "generationDate":new Date(1448450535229.77),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"tplb_img",
"jdt_bfb",
"qsjs_r",
"tpcc_wz",
"tpcc_zt",
"tpcc_kd",
"yz_msg"],
  "page":{
    "packageId":"d9d47be3fcdf4553bd0fa1c7b97fa0f8",
    "type":"Axure:Page",
    "name":"需求场景描述",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d948529bd4b448208b7ae275ee697132",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":-10,
              "y":-40},
            "size":{
              "width":3610,
              "height":2080}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea38f7a2f10f4a22b1b0f8f0daff712b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":-10,
                  "y":-40},
                "size":{
                  "width":3610,
                  "height":2080}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/需求场景描述/u0.png"}},
{
          "id":"e271721034de44e880c9f6c21a61204a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":50,
              "y":44},
            "size":{
              "width":200,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56b8e254e6e947e790822f1b19b8e3ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":44},
                "size":{
                  "width":200,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38f1bfbade8b46ee90ab53a08654d98a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":50,
              "y":100},
            "size":{
              "width":1050,
              "height":114}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89d07490f1034450bd0731f5c4aa3c79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":100},
                "size":{
                  "width":1050,
                  "height":114}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"340519a8bef644879d421ebc4f4e1e56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":50,
              "y":260},
            "size":{
              "width":510,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19101c66ba07438a89879399c3d2eb49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":260},
                "size":{
                  "width":510,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"771ae4bf84ee4cd992353c53dfeb92ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":50,
              "y":322},
            "size":{
              "width":1390,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17ece8edb3324c08bbfabcc5dda9ba18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":322},
                "size":{
                  "width":1390,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76e0fea7a3b34b56b3391b9d4b2064bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":50,
              "y":547},
            "size":{
              "width":510,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6602bb4814f485588b0c3678ac4c461",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":547},
                "size":{
                  "width":510,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d976c84ed9964a0fae72b9b34d7b79b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":50,
              "y":612},
            "size":{
              "width":1220,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19ce736befad4682bdc2b98ad259f7fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":612},
                "size":{
                  "width":1220,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d948529bd4b448208b7ae275ee697132":{
      "scriptId":"u0"},
    "ea38f7a2f10f4a22b1b0f8f0daff712b":{
      "scriptId":"u1"},
    "e271721034de44e880c9f6c21a61204a":{
      "scriptId":"u2"},
    "56b8e254e6e947e790822f1b19b8e3ec":{
      "scriptId":"u3"},
    "38f1bfbade8b46ee90ab53a08654d98a":{
      "scriptId":"u4"},
    "89d07490f1034450bd0731f5c4aa3c79":{
      "scriptId":"u5"},
    "340519a8bef644879d421ebc4f4e1e56":{
      "scriptId":"u6"},
    "19101c66ba07438a89879399c3d2eb49":{
      "scriptId":"u7"},
    "771ae4bf84ee4cd992353c53dfeb92ef":{
      "scriptId":"u8"},
    "17ece8edb3324c08bbfabcc5dda9ba18":{
      "scriptId":"u9"},
    "76e0fea7a3b34b56b3391b9d4b2064bc":{
      "scriptId":"u10"},
    "e6602bb4814f485588b0c3678ac4c461":{
      "scriptId":"u11"},
    "d976c84ed9964a0fae72b9b34d7b79b3":{
      "scriptId":"u12"},
    "19ce736befad4682bdc2b98ad259f7fa":{
      "scriptId":"u13"}}});