$axure.loadCurrentPage({
  "url":"员工就餐-午餐.html",
  "generationDate":new Date(1448450537882.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"tplb_img",
"jdt_bfb",
"qsjs_r",
"tpcc_wz",
"tpcc_zt",
"tpcc_kd",
"yz_msg"],
  "page":{
    "packageId":"6448cf87f8c74bfeb1ceb32160fd05f2",
    "type":"Axure:Page",
    "name":"员工就餐-午餐",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4a4199315e4048a6b41eb6186dae7217",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":30,
              "y":79},
            "size":{
              "width":320,
              "height":590},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b56592ff62964f03b920d434d46b50ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":30,
                  "y":79},
                "size":{
                  "width":320,
                  "height":590},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-午餐/u0.png"}},
{
          "id":"57ca9a7056194e1aba7991b6b2dfe636",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":79},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ad03dfc0dde4f20b2711af551fd4d70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":37,
                  "y":79},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u2.png"}},
{
          "id":"a00b41987a414f5fa5c3e2e6ab4f4486",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":94},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9efeb5aa11d44af593523c8d4dac6af0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":94},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u4.png"}},
{
          "id":"d4de20b488ef464f897a405e8b1871d3",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":143,
              "y":107},
            "size":{
              "width":123,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bd63439e7d64b6e99745db67fb7d197",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":143,
                  "y":107},
                "size":{
                  "width":123,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"526a78c716584aa7a407714ed77ff1f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":107},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4090e5cec3c47e98247d900ce4fa7bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":107},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u8.png"}},
{
          "id":"33c4f2b193164f36b6d1c2c565b67ab8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":159},
            "size":{
              "width":303,
              "height":320},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07728c50de114909bc095f52838c6bba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":39,
                  "y":159},
                "size":{
                  "width":303,
                  "height":320},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-午餐/u10.png"}},
{
          "id":"60fbfc020c7043abab4708a2b4b46322",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":90,
              "y":249},
            "size":{
              "width":185,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee1abef6c8404ba698d6c69e3e5ecf9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":90,
                  "y":249},
                "size":{
                  "width":185,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-午餐/u12.png"}},
{
          "id":"6713ddcb438047a493008ac6c4d7dace",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":294,
              "y":439},
            "size":{
              "width":23,
              "height":23},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54dfd5380f5241148a6dbe9fc3d6c904",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":294,
                  "y":439},
                "size":{
                  "width":23,
                  "height":23},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 消费详情,<br>遮罩",
                      "objectsToFades":[{
                          "objectPath":["85901d2e0d8b4180a2ff4b0749547d99"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["aea1a3f82d6542a98984d3dda747676c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/员工就餐-午餐/u14.png"}},
{
          "id":"c24a2ab075814f8fb537f4115d431622",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":209,
              "y":443},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb0eb9a662d249dabe7ada77767be901",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":209,
                  "y":443},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 消费详情,<br>遮罩",
                      "objectsToFades":[{
                          "objectPath":["85901d2e0d8b4180a2ff4b0749547d99"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["aea1a3f82d6542a98984d3dda747676c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f998cb3ce4af459a9b633d8759cc8df6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":54,
              "y":179},
            "size":{
              "width":190,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d618d09037e4439839e2afa6708daf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":54,
                  "y":179},
                "size":{
                  "width":190,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21db972286054f4a910cdb0a511243da",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":230},
            "size":{
              "width":289,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/员工就餐-午餐/u20_line.png"}},
{
          "id":"77bba4ad541f46c89db41eab2fa56ef4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":54,
              "y":208},
            "size":{
              "width":280,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"908ddab90d02402b8af7cd2f902f2145",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":54,
                  "y":208},
                "size":{
                  "width":280,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aea1a3f82d6542a98984d3dda747676c",
          "label":"遮罩",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x91000000},
            "location":{
              "x":30,
              "y":140},
            "size":{
              "width":320,
              "height":530},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"956aa09ae8854a3eb4ceb1cee800413a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x91000000},
                "location":{
                  "x":30,
                  "y":140},
                "size":{
                  "width":320,
                  "height":530},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-午餐/遮罩_u23.png"}},
{
          "id":"85901d2e0d8b4180a2ff4b0749547d99",
          "label":"消费详情",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":30,
              "y":255},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"8f89b91226ad4ea78651c959e36480be",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"63c6aa5b47224e85ad2b2aafb751f2b5",
                  "label":"",
                  "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":290,
                      "height":280},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"8"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5b34f09544524f2fb55a901d693f981f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":290,
                          "height":280},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"8"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/员工就餐-午餐/u26.png"}},
{
                  "id":"fcfa2e8d7c9e47569348d74fb58f9c07",
                  "label":"",
                  "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":35,
                      "y":126},
                    "size":{
                      "width":289,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9d4c1edbb91a47f79cce88c3f2fe824d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":35,
                          "y":126},
                        "size":{
                          "width":289,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e6712076bf5b4a8198dfa05e83d1df9b",
                  "label":"",
                  "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":35,
                      "y":210},
                    "size":{
                      "width":289,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"164d19bfb9a6443d8e6bc8223eeb1a02",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":35,
                          "y":210},
                        "size":{
                          "width":289,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8c8d2a1038e54c26b5b9e437408ba299",
                  "label":"",
                  "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":35,
                      "y":250},
                    "size":{
                      "width":289,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c5f3cdb6bc394e56a08e67bd2488bb5b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":35,
                          "y":250},
                        "size":{
                          "width":289,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d7986ffd7f6d4038a84a05baa2e9161f",
                  "label":"",
                  "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":35,
                      "y":54},
                    "size":{
                      "width":289,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fb53f926dda64ba4a8b46553baf73de3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":35,
                          "y":54},
                        "size":{
                          "width":289,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f08ab10efbfa4abc832e74d82df3e546",
                  "label":"",
                  "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":35,
                      "y":90},
                    "size":{
                      "width":289,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"32689880f45544c582fa08871b1aacfa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":35,
                          "y":90},
                        "size":{
                          "width":289,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"929ed0c919e641808d2cd3cb3d42ea2c",
                  "label":"",
                  "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":35,
                      "y":170},
                    "size":{
                      "width":289,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3692c820a56449a4ab788d9a28365a43",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":35,
                          "y":170},
                        "size":{
                          "width":289,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f3d3b97c339c42179c0fc461ea37b5b1",
                  "label":"",
                  "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":277,
                      "y":31},
                    "size":{
                      "width":23,
                      "height":23},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"68cabd9479c041299ecf3e22ec071ec8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":277,
                          "y":31},
                        "size":{
                          "width":23,
                          "height":23},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF666666}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 遮罩,<br>消费详情",
                              "objectsToFades":[{
                                  "objectPath":["aea1a3f82d6542a98984d3dda747676c"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["85901d2e0d8b4180a2ff4b0749547d99"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/员工就餐-午餐/u40.png"}}]}]},
{
          "id":"3ccb2dc944944d918c9946b8ede37625",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":450,
              "y":79},
            "size":{
              "width":320,
              "height":590},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5793882c6bf84e4d8e4983725fc30d90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":450,
                  "y":79},
                "size":{
                  "width":320,
                  "height":590},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-午餐/u0.png"}},
{
          "id":"9e15cfc46b4c4a2d89e373ddc5c7a111",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":457,
              "y":79},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28e7586c287e424eb80f58662cb5b913",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":457,
                  "y":79},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u2.png"}},
{
          "id":"2383c5f2158f40e49a5452cedb99c85f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":94},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4297759642064a3cb8a75e653975e307",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":94},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u4.png"}},
{
          "id":"2e47e4472a60495f8d90a3eb615b1a9e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":461,
              "y":107},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ec02f487eaf45cc80008f027ba44dd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":461,
                  "y":107},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u8.png"}},
{
          "id":"8b73f8b38c844347bc7c301b85880a17",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":560,
              "y":105},
            "size":{
              "width":123,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c8b88303dc849ffa6474c16cdec9b81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":560,
                  "y":105},
                "size":{
                  "width":123,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c943985f185746d191ae79d2909de399",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":457,
              "y":159},
            "size":{
              "width":303,
              "height":320},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d898f22222f41d59bdebffcc8ace0b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":457,
                  "y":159},
                "size":{
                  "width":303,
                  "height":320},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-午餐/u10.png"}},
{
          "id":"966d8b6209784a84a73d6b28dbcfef1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":508,
              "y":249},
            "size":{
              "width":185,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7bed77003f24b4597343a20c1790378",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":508,
                  "y":249},
                "size":{
                  "width":185,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-午餐/u12.png"}},
{
          "id":"48d8b5c0e1894ccd8e78b499be6536af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":712,
              "y":439},
            "size":{
              "width":23,
              "height":23},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be9cbb5a7ae442b6807766353695ccc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":712,
                  "y":439},
                "size":{
                  "width":23,
                  "height":23},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 消费详情,<br>遮罩",
                      "objectsToFades":[{
                          "objectPath":["85901d2e0d8b4180a2ff4b0749547d99"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["aea1a3f82d6542a98984d3dda747676c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/员工就餐-午餐/u14.png"}},
{
          "id":"0292ee37efe14bcd880677374403ed50",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":627,
              "y":443},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3f4ea4b2344445999db199cbc86aea1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":627,
                  "y":443},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 消费详情,<br>遮罩",
                      "objectsToFades":[{
                          "objectPath":["85901d2e0d8b4180a2ff4b0749547d99"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["aea1a3f82d6542a98984d3dda747676c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24274f2e280942e98a68ba58052c2628",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":472,
              "y":179},
            "size":{
              "width":190,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3e292378c3f466ea34592e8e1924f64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":472,
                  "y":179},
                "size":{
                  "width":190,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81518d9e21c545e09479a2f9ed975150",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":230},
            "size":{
              "width":289,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/员工就餐-午餐/u20_line.png"}},
{
          "id":"d41dd88c7dab46a8af4562293fcf567f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":472,
              "y":208},
            "size":{
              "width":280,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db1bace6721d41769e933c8e66aa4eb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":472,
                  "y":208},
                "size":{
                  "width":280,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8649acf95da6448f94b20061fb7b74a2",
          "label":"遮罩",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x91000000},
            "location":{
              "x":450,
              "y":139},
            "size":{
              "width":320,
              "height":530},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d515d4923bcb49779b40b5622f1c0102",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x91000000},
                "location":{
                  "x":450,
                  "y":139},
                "size":{
                  "width":320,
                  "height":530},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-午餐/遮罩_u23.png"}},
{
          "id":"0ee120f17f11462fa64dd7e93dc984ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":507,
              "y":309},
            "size":{
              "width":200,
              "height":100},
            "cornerRadiusTopLeft":"11"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a106943989b0429ea8296ddae8bc5b25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":507,
                  "y":309},
                "size":{
                  "width":200,
                  "height":100},
                "cornerRadiusTopLeft":"11"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-午餐/u67.png"}},
{
          "id":"0cef2f03849f45fb818733c7ea68d0cf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":507,
              "y":367},
            "size":{
              "width":200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/员工就餐-午餐/u69_line.png"}},
{
          "id":"ee8f452d59e94b4ba354c81b3f777945",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":593,
              "y":381},
            "size":{
              "width":47,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"733ea08955dc456c88ea1a2bbe32bf47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":593,
                  "y":381},
                "size":{
                  "width":47,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1db4ea49f27f45fb892491bd8eded7c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":541,
              "y":333},
            "size":{
              "width":163,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb9c8467595548e08988791676d49c7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":541,
                  "y":333},
                "size":{
                  "width":163,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd07ff970aab4318a18b8602777bffa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":457,
              "y":32},
            "size":{
              "width":225,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c026044ff254dbc822a8265cbdec04b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":457,
                  "y":32},
                "size":{
                  "width":225,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "4a4199315e4048a6b41eb6186dae7217":{
      "scriptId":"u0"},
    "b56592ff62964f03b920d434d46b50ec":{
      "scriptId":"u1"},
    "57ca9a7056194e1aba7991b6b2dfe636":{
      "scriptId":"u2"},
    "6ad03dfc0dde4f20b2711af551fd4d70":{
      "scriptId":"u3"},
    "a00b41987a414f5fa5c3e2e6ab4f4486":{
      "scriptId":"u4"},
    "9efeb5aa11d44af593523c8d4dac6af0":{
      "scriptId":"u5"},
    "d4de20b488ef464f897a405e8b1871d3":{
      "scriptId":"u6"},
    "4bd63439e7d64b6e99745db67fb7d197":{
      "scriptId":"u7"},
    "526a78c716584aa7a407714ed77ff1f0":{
      "scriptId":"u8"},
    "b4090e5cec3c47e98247d900ce4fa7bc":{
      "scriptId":"u9"},
    "33c4f2b193164f36b6d1c2c565b67ab8":{
      "scriptId":"u10"},
    "07728c50de114909bc095f52838c6bba":{
      "scriptId":"u11"},
    "60fbfc020c7043abab4708a2b4b46322":{
      "scriptId":"u12"},
    "ee1abef6c8404ba698d6c69e3e5ecf9b":{
      "scriptId":"u13"},
    "6713ddcb438047a493008ac6c4d7dace":{
      "scriptId":"u14"},
    "54dfd5380f5241148a6dbe9fc3d6c904":{
      "scriptId":"u15"},
    "c24a2ab075814f8fb537f4115d431622":{
      "scriptId":"u16"},
    "cb0eb9a662d249dabe7ada77767be901":{
      "scriptId":"u17"},
    "f998cb3ce4af459a9b633d8759cc8df6":{
      "scriptId":"u18"},
    "7d618d09037e4439839e2afa6708daf0":{
      "scriptId":"u19"},
    "21db972286054f4a910cdb0a511243da":{
      "scriptId":"u20"},
    "77bba4ad541f46c89db41eab2fa56ef4":{
      "scriptId":"u21"},
    "908ddab90d02402b8af7cd2f902f2145":{
      "scriptId":"u22"},
    "aea1a3f82d6542a98984d3dda747676c":{
      "scriptId":"u23"},
    "956aa09ae8854a3eb4ceb1cee800413a":{
      "scriptId":"u24"},
    "85901d2e0d8b4180a2ff4b0749547d99":{
      "scriptId":"u25"},
    "63c6aa5b47224e85ad2b2aafb751f2b5":{
      "scriptId":"u26"},
    "5b34f09544524f2fb55a901d693f981f":{
      "scriptId":"u27"},
    "fcfa2e8d7c9e47569348d74fb58f9c07":{
      "scriptId":"u28"},
    "9d4c1edbb91a47f79cce88c3f2fe824d":{
      "scriptId":"u29"},
    "e6712076bf5b4a8198dfa05e83d1df9b":{
      "scriptId":"u30"},
    "164d19bfb9a6443d8e6bc8223eeb1a02":{
      "scriptId":"u31"},
    "8c8d2a1038e54c26b5b9e437408ba299":{
      "scriptId":"u32"},
    "c5f3cdb6bc394e56a08e67bd2488bb5b":{
      "scriptId":"u33"},
    "d7986ffd7f6d4038a84a05baa2e9161f":{
      "scriptId":"u34"},
    "fb53f926dda64ba4a8b46553baf73de3":{
      "scriptId":"u35"},
    "f08ab10efbfa4abc832e74d82df3e546":{
      "scriptId":"u36"},
    "32689880f45544c582fa08871b1aacfa":{
      "scriptId":"u37"},
    "929ed0c919e641808d2cd3cb3d42ea2c":{
      "scriptId":"u38"},
    "3692c820a56449a4ab788d9a28365a43":{
      "scriptId":"u39"},
    "f3d3b97c339c42179c0fc461ea37b5b1":{
      "scriptId":"u40"},
    "68cabd9479c041299ecf3e22ec071ec8":{
      "scriptId":"u41"},
    "3ccb2dc944944d918c9946b8ede37625":{
      "scriptId":"u42"},
    "5793882c6bf84e4d8e4983725fc30d90":{
      "scriptId":"u43"},
    "9e15cfc46b4c4a2d89e373ddc5c7a111":{
      "scriptId":"u44"},
    "28e7586c287e424eb80f58662cb5b913":{
      "scriptId":"u45"},
    "2383c5f2158f40e49a5452cedb99c85f":{
      "scriptId":"u46"},
    "4297759642064a3cb8a75e653975e307":{
      "scriptId":"u47"},
    "2e47e4472a60495f8d90a3eb615b1a9e":{
      "scriptId":"u48"},
    "7ec02f487eaf45cc80008f027ba44dd8":{
      "scriptId":"u49"},
    "8b73f8b38c844347bc7c301b85880a17":{
      "scriptId":"u50"},
    "1c8b88303dc849ffa6474c16cdec9b81":{
      "scriptId":"u51"},
    "c943985f185746d191ae79d2909de399":{
      "scriptId":"u52"},
    "5d898f22222f41d59bdebffcc8ace0b5":{
      "scriptId":"u53"},
    "966d8b6209784a84a73d6b28dbcfef1d":{
      "scriptId":"u54"},
    "f7bed77003f24b4597343a20c1790378":{
      "scriptId":"u55"},
    "48d8b5c0e1894ccd8e78b499be6536af":{
      "scriptId":"u56"},
    "be9cbb5a7ae442b6807766353695ccc3":{
      "scriptId":"u57"},
    "0292ee37efe14bcd880677374403ed50":{
      "scriptId":"u58"},
    "b3f4ea4b2344445999db199cbc86aea1":{
      "scriptId":"u59"},
    "24274f2e280942e98a68ba58052c2628":{
      "scriptId":"u60"},
    "c3e292378c3f466ea34592e8e1924f64":{
      "scriptId":"u61"},
    "81518d9e21c545e09479a2f9ed975150":{
      "scriptId":"u62"},
    "d41dd88c7dab46a8af4562293fcf567f":{
      "scriptId":"u63"},
    "db1bace6721d41769e933c8e66aa4eb0":{
      "scriptId":"u64"},
    "8649acf95da6448f94b20061fb7b74a2":{
      "scriptId":"u65"},
    "d515d4923bcb49779b40b5622f1c0102":{
      "scriptId":"u66"},
    "0ee120f17f11462fa64dd7e93dc984ef":{
      "scriptId":"u67"},
    "a106943989b0429ea8296ddae8bc5b25":{
      "scriptId":"u68"},
    "0cef2f03849f45fb818733c7ea68d0cf":{
      "scriptId":"u69"},
    "ee8f452d59e94b4ba354c81b3f777945":{
      "scriptId":"u70"},
    "733ea08955dc456c88ea1a2bbe32bf47":{
      "scriptId":"u71"},
    "1db4ea49f27f45fb892491bd8eded7c8":{
      "scriptId":"u72"},
    "bb9c8467595548e08988791676d49c7f":{
      "scriptId":"u73"},
    "fd07ff970aab4318a18b8602777bffa8":{
      "scriptId":"u74"},
    "2c026044ff254dbc822a8265cbdec04b":{
      "scriptId":"u75"}}});