$axure.loadCurrentPage({
  "url":"员工就餐-午餐.html",
  "generationDate":new Date(1448611752218.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"tplb_img",
"jdt_bfb",
"qsjs_r",
"tpcc_wz",
"tpcc_zt",
"tpcc_kd",
"yz_msg"],
  "page":{
    "packageId":"6448cf87f8c74bfeb1ceb32160fd05f2",
    "type":"Axure:Page",
    "name":"员工就餐-午餐",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fd07ff970aab4318a18b8602777bffa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":457,
              "y":32},
            "size":{
              "width":225,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c026044ff254dbc822a8265cbdec04b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":457,
                  "y":32},
                "size":{
                  "width":225,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a99780c9b3348a28226bce2cbfef5d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":40,
              "y":79},
            "size":{
              "width":320,
              "height":620},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"032a3e60788e479b8f410fadf7851763",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":40,
                  "y":79},
                "size":{
                  "width":320,
                  "height":620},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-午餐/u2.png"}},
{
          "id":"4b04325807d4410e9934391bd0f5c4da",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":94},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d61cd77e16e64274bb6fc581c3835af6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":94},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u4.png"}},
{
          "id":"7855d4fd58254fc9af959cde4b8eeba4",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":162,
              "y":105},
            "size":{
              "width":128,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2416113ce2294eb1bbe95c8060d08cd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":162,
                  "y":105},
                "size":{
                  "width":128,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4c46cdf93704bb99cfcadd4aa7d1990",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":107},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33004efca4ed4bb5b629acbf74dd40f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":107},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u8.png"}},
{
          "id":"31582337d00e49018b485b8e79baaafc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":79},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9061c53c76d340759eab49d6065c6aaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":79},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u2.png"}},
{
          "id":"c59ae91c530449c8a8f402aef92c8dd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":45,
              "y":159},
            "size":{
              "width":309,
              "height":431},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c4e89d6954e4e87afc077193e4145c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":45,
                  "y":159},
                "size":{
                  "width":309,
                  "height":431},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-午餐/u12.png"}},
{
          "id":"8c979bab7aee4be1bd4278cc68e1c281",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":64,
              "y":230},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aae0beceff8f4dc98f0f6a15d30e71b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":64,
                  "y":230},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce2304266e084cd09f499ad2b0488914",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":208},
            "size":{
              "width":305,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/券列表/u54_line.png"}},
{
          "id":"d51dc237ebe04592b5eec5705b80c44f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0x87797979},
            "location":{
              "x":62,
              "y":164},
            "size":{
              "width":45,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3be9d9adf3d490391cbccccbab4bb4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0x87797979},
                "location":{
                  "x":62,
                  "y":164},
                "size":{
                  "width":45,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐券/u30.png"}},
{
          "id":"e7b3bb6a34f64106a9c2cc3d47139aae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":166},
            "size":{
              "width":198,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75c6a700d6474137b73ed4139bb68674",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":166},
                "size":{
                  "width":198,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a84ce9a8a954d5cbd68314b2225ed43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":193},
            "size":{
              "width":198,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0757d614a5e54b35b1ea6c8894e7a5ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":193},
                "size":{
                  "width":198,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"726232e7441d4951a94a41289f772e9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":269},
            "size":{
              "width":225,
              "height":225}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b012858eaa89420887739b39e1cd8859",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":269},
                "size":{
                  "width":225,
                  "height":225}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐券/u14.png"}},
{
          "id":"ccfaf239e82d4f4696e90e23006b60db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":320,
              "y":174},
            "size":{
              "width":32,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85966243cf0e49838cd498f96df2dfe0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":320,
                  "y":174},
                "size":{
                  "width":32,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ced3e9add2840598dd436aa0670e269",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":510},
            "size":{
              "width":305,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/券列表/u54_line.png"}},
{
          "id":"81edee2f4c91437c922250c1948108dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":64,
              "y":530},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9516158618464aba9d3cab0fbec5795d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":64,
                  "y":530},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"604bbcd37f0245219cd63464a179b014",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":60,
              "y":565},
            "size":{
              "width":280,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1121d9eca3b74ad6a2348f8dc3bf15ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":60,
                  "y":565},
                "size":{
                  "width":280,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e84567e69ee4d56bdba3bc1622035e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":457,
              "y":94},
            "size":{
              "width":320,
              "height":591},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ca6094403cb4811bc69a87b4f432f8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":457,
                  "y":94},
                "size":{
                  "width":320,
                  "height":591},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-午餐/u32.png"}},
{
          "id":"a15162bbf6be4269b13ef8892bb8a64d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":457,
              "y":109},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebb4077445564cf69de911110997e3df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":457,
                  "y":109},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u4.png"}},
{
          "id":"a5909c3029a644468d253772ce5e3bd5",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":579,
              "y":120},
            "size":{
              "width":128,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f9175186ef54939ba00523a47e2a44d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":579,
                  "y":120},
                "size":{
                  "width":128,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d022c1963754d84b356c6c9fcc828d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":468,
              "y":122},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e048d39cd6a14b27a2e18bbe3f5a1229",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":468,
                  "y":122},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u8.png"}},
{
          "id":"c7e14c046af14c4c9c9395043db61cab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":94},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bd51ee7f5f64cc4befba1bc43cc3803",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":464,
                  "y":94},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u2.png"}},
{
          "id":"bc131063f5914cccb3344b7989cb8aac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":462,
              "y":174},
            "size":{
              "width":309,
              "height":431},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e3816768c4443b1a3e0d06dbdbedce2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":462,
                  "y":174},
                "size":{
                  "width":309,
                  "height":431},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-午餐/u12.png"}},
{
          "id":"48a58bba5c4846bbb676b4ef467ba974",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":481,
              "y":245},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58c879f08b5941aa8701ec77ebb07005",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":481,
                  "y":245},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d1d8c456a0a45cba76ac9f7d6f269cb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":223},
            "size":{
              "width":305,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/券列表/u54_line.png"}},
{
          "id":"70f7e38452bc47b3b1008b1d81e83428",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0x87797979},
            "location":{
              "x":479,
              "y":179},
            "size":{
              "width":45,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e798a90d57da4323bc3f428508b32102",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0x87797979},
                "location":{
                  "x":479,
                  "y":179},
                "size":{
                  "width":45,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐券/u30.png"}},
{
          "id":"8d41f00bd2204447bc2c71353bf24b48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":537,
              "y":181},
            "size":{
              "width":198,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a05c8f5e7844c68b2763eec168bd1fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":537,
                  "y":181},
                "size":{
                  "width":198,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a859c1df76342728d7e1f92785dccef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":535,
              "y":208},
            "size":{
              "width":198,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8761bf1e890a46fca606bf2f51498058",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":535,
                  "y":208},
                "size":{
                  "width":198,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b8abf76b854490998adf44b6e0ba2d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":497,
              "y":284},
            "size":{
              "width":225,
              "height":225}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d86a207177240b788a8b3ff6b4cbd6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":497,
                  "y":284},
                "size":{
                  "width":225,
                  "height":225}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐券/u14.png"}},
{
          "id":"0a3378c4cc154bf9a14f63e642e26ab5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":737,
              "y":189},
            "size":{
              "width":32,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"111263c12f7f4a36b45229e0b8f2f8ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":737,
                  "y":189},
                "size":{
                  "width":32,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9b99a248cfa49118c7262461c17a986",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":525},
            "size":{
              "width":305,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/券列表/u54_line.png"}},
{
          "id":"cc74b28fe96346989c6f9e616f9bd13c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":481,
              "y":545},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34538a27e7f64040af60ba4be13e93fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":481,
                  "y":545},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"220bf97154a049e3b8206f7966699bd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":477,
              "y":580},
            "size":{
              "width":280,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7673314f98924ed79eccb7a3eb8febf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":477,
                  "y":580},
                "size":{
                  "width":280,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8649acf95da6448f94b20061fb7b74a2",
          "label":"遮罩",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x91000000},
            "location":{
              "x":457,
              "y":155},
            "size":{
              "width":320,
              "height":530},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d515d4923bcb49779b40b5622f1c0102",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x91000000},
                "location":{
                  "x":457,
                  "y":155},
                "size":{
                  "width":320,
                  "height":530},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-午餐/遮罩_u62.png"}},
{
          "id":"0ee120f17f11462fa64dd7e93dc984ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":514,
              "y":325},
            "size":{
              "width":200,
              "height":100},
            "cornerRadiusTopLeft":"11"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a106943989b0429ea8296ddae8bc5b25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":514,
                  "y":325},
                "size":{
                  "width":200,
                  "height":100},
                "cornerRadiusTopLeft":"11"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-午餐/u64.png"}},
{
          "id":"0cef2f03849f45fb818733c7ea68d0cf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":514,
              "y":383},
            "size":{
              "width":200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/员工就餐-午餐/u66_line.png"}},
{
          "id":"ee8f452d59e94b4ba354c81b3f777945",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":600,
              "y":397},
            "size":{
              "width":47,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"733ea08955dc456c88ea1a2bbe32bf47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":600,
                  "y":397},
                "size":{
                  "width":47,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1db4ea49f27f45fb892491bd8eded7c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":548,
              "y":349},
            "size":{
              "width":163,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb9c8467595548e08988791676d49c7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":548,
                  "y":349},
                "size":{
                  "width":163,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce29b921f01443eaa024f0d358de8ab2",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":159},
            "size":{
              "width":305,
              "height":59}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 午餐券详情",
                      "target":{
                        "targetType":"page",
                        "url":"午餐券详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "fd07ff970aab4318a18b8602777bffa8":{
      "scriptId":"u0"},
    "2c026044ff254dbc822a8265cbdec04b":{
      "scriptId":"u1"},
    "0a99780c9b3348a28226bce2cbfef5d7":{
      "scriptId":"u2"},
    "032a3e60788e479b8f410fadf7851763":{
      "scriptId":"u3"},
    "4b04325807d4410e9934391bd0f5c4da":{
      "scriptId":"u4"},
    "d61cd77e16e64274bb6fc581c3835af6":{
      "scriptId":"u5"},
    "7855d4fd58254fc9af959cde4b8eeba4":{
      "scriptId":"u6"},
    "2416113ce2294eb1bbe95c8060d08cd8":{
      "scriptId":"u7"},
    "b4c46cdf93704bb99cfcadd4aa7d1990":{
      "scriptId":"u8"},
    "33004efca4ed4bb5b629acbf74dd40f9":{
      "scriptId":"u9"},
    "31582337d00e49018b485b8e79baaafc":{
      "scriptId":"u10"},
    "9061c53c76d340759eab49d6065c6aaa":{
      "scriptId":"u11"},
    "c59ae91c530449c8a8f402aef92c8dd4":{
      "scriptId":"u12"},
    "7c4e89d6954e4e87afc077193e4145c5":{
      "scriptId":"u13"},
    "8c979bab7aee4be1bd4278cc68e1c281":{
      "scriptId":"u14"},
    "aae0beceff8f4dc98f0f6a15d30e71b0":{
      "scriptId":"u15"},
    "ce2304266e084cd09f499ad2b0488914":{
      "scriptId":"u16"},
    "d51dc237ebe04592b5eec5705b80c44f":{
      "scriptId":"u17"},
    "b3be9d9adf3d490391cbccccbab4bb4e":{
      "scriptId":"u18"},
    "e7b3bb6a34f64106a9c2cc3d47139aae":{
      "scriptId":"u19"},
    "75c6a700d6474137b73ed4139bb68674":{
      "scriptId":"u20"},
    "6a84ce9a8a954d5cbd68314b2225ed43":{
      "scriptId":"u21"},
    "0757d614a5e54b35b1ea6c8894e7a5ab":{
      "scriptId":"u22"},
    "726232e7441d4951a94a41289f772e9e":{
      "scriptId":"u23"},
    "b012858eaa89420887739b39e1cd8859":{
      "scriptId":"u24"},
    "ccfaf239e82d4f4696e90e23006b60db":{
      "scriptId":"u25"},
    "85966243cf0e49838cd498f96df2dfe0":{
      "scriptId":"u26"},
    "2ced3e9add2840598dd436aa0670e269":{
      "scriptId":"u27"},
    "81edee2f4c91437c922250c1948108dd":{
      "scriptId":"u28"},
    "9516158618464aba9d3cab0fbec5795d":{
      "scriptId":"u29"},
    "604bbcd37f0245219cd63464a179b014":{
      "scriptId":"u30"},
    "1121d9eca3b74ad6a2348f8dc3bf15ed":{
      "scriptId":"u31"},
    "9e84567e69ee4d56bdba3bc1622035e6":{
      "scriptId":"u32"},
    "8ca6094403cb4811bc69a87b4f432f8a":{
      "scriptId":"u33"},
    "a15162bbf6be4269b13ef8892bb8a64d":{
      "scriptId":"u34"},
    "ebb4077445564cf69de911110997e3df":{
      "scriptId":"u35"},
    "a5909c3029a644468d253772ce5e3bd5":{
      "scriptId":"u36"},
    "0f9175186ef54939ba00523a47e2a44d":{
      "scriptId":"u37"},
    "5d022c1963754d84b356c6c9fcc828d4":{
      "scriptId":"u38"},
    "e048d39cd6a14b27a2e18bbe3f5a1229":{
      "scriptId":"u39"},
    "c7e14c046af14c4c9c9395043db61cab":{
      "scriptId":"u40"},
    "2bd51ee7f5f64cc4befba1bc43cc3803":{
      "scriptId":"u41"},
    "bc131063f5914cccb3344b7989cb8aac":{
      "scriptId":"u42"},
    "8e3816768c4443b1a3e0d06dbdbedce2":{
      "scriptId":"u43"},
    "48a58bba5c4846bbb676b4ef467ba974":{
      "scriptId":"u44"},
    "58c879f08b5941aa8701ec77ebb07005":{
      "scriptId":"u45"},
    "8d1d8c456a0a45cba76ac9f7d6f269cb":{
      "scriptId":"u46"},
    "70f7e38452bc47b3b1008b1d81e83428":{
      "scriptId":"u47"},
    "e798a90d57da4323bc3f428508b32102":{
      "scriptId":"u48"},
    "8d41f00bd2204447bc2c71353bf24b48":{
      "scriptId":"u49"},
    "7a05c8f5e7844c68b2763eec168bd1fc":{
      "scriptId":"u50"},
    "2a859c1df76342728d7e1f92785dccef":{
      "scriptId":"u51"},
    "8761bf1e890a46fca606bf2f51498058":{
      "scriptId":"u52"},
    "4b8abf76b854490998adf44b6e0ba2d1":{
      "scriptId":"u53"},
    "6d86a207177240b788a8b3ff6b4cbd6c":{
      "scriptId":"u54"},
    "0a3378c4cc154bf9a14f63e642e26ab5":{
      "scriptId":"u55"},
    "111263c12f7f4a36b45229e0b8f2f8ca":{
      "scriptId":"u56"},
    "d9b99a248cfa49118c7262461c17a986":{
      "scriptId":"u57"},
    "cc74b28fe96346989c6f9e616f9bd13c":{
      "scriptId":"u58"},
    "34538a27e7f64040af60ba4be13e93fb":{
      "scriptId":"u59"},
    "220bf97154a049e3b8206f7966699bd1":{
      "scriptId":"u60"},
    "7673314f98924ed79eccb7a3eb8febf2":{
      "scriptId":"u61"},
    "8649acf95da6448f94b20061fb7b74a2":{
      "scriptId":"u62"},
    "d515d4923bcb49779b40b5622f1c0102":{
      "scriptId":"u63"},
    "0ee120f17f11462fa64dd7e93dc984ef":{
      "scriptId":"u64"},
    "a106943989b0429ea8296ddae8bc5b25":{
      "scriptId":"u65"},
    "0cef2f03849f45fb818733c7ea68d0cf":{
      "scriptId":"u66"},
    "ee8f452d59e94b4ba354c81b3f777945":{
      "scriptId":"u67"},
    "733ea08955dc456c88ea1a2bbe32bf47":{
      "scriptId":"u68"},
    "1db4ea49f27f45fb892491bd8eded7c8":{
      "scriptId":"u69"},
    "bb9c8467595548e08988791676d49c7f":{
      "scriptId":"u70"},
    "ce29b921f01443eaa024f0d358de8ab2":{
      "scriptId":"u71"}}});