$axure.loadCurrentPage({
  "url":"早餐就餐流程图.html",
  "generationDate":new Date(1448611750638.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"tplb_img",
"jdt_bfb",
"qsjs_r",
"tpcc_wz",
"tpcc_zt",
"tpcc_kd",
"yz_msg"],
  "page":{
    "packageId":"b5d18f7fc25449fdace9c485c3083eef",
    "type":"Axure:Page",
    "name":"早餐就餐流程图",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3310d70bbf7c42499eedd3e8daf8c4b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":-10,
              "y":-40},
            "size":{
              "width":3610,
              "height":2080}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f2211f5572d49a4b1bd20275fc6f147",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":-10,
                  "y":-40},
                "size":{
                  "width":3610,
                  "height":2080}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/需求场景描述/u0.png"}},
{
          "id":"c92a9ba662e64b8bbc9dcf8f5971c126",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":77,
              "y":407},
            "size":{
              "width":373,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7035641699542b7b46338b9ab79d038",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":77,
                  "y":407},
                "size":{
                  "width":373,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a747870fc4e4960b835d50a067dada7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":110},
            "size":{
              "width":617,
              "height":239}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67ac668b1b56432595240df1ea155317",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":110},
                "size":{
                  "width":617,
                  "height":239}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐就餐流程图/u4.png"}},
{
          "id":"54c1da645e754b7dbe0f2bbb7fae6433",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":77,
              "y":30},
            "size":{
              "width":373,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c47c502f97244b54bc34ad1a457e626a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":77,
                  "y":30},
                "size":{
                  "width":373,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06b8e290351d4a4c8b1e6ca1e848a326",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":77,
              "y":486},
            "size":{
              "width":128,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51b810f4b33a4b1a8cf6aeacc6805d31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":77,
                  "y":486},
                "size":{
                  "width":128,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"423977bc9c5145adb73f02dfc78249bd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":520},
            "size":{
              "width":258,
              "height":460}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"232009501a744c3e9ef6254b141cb335",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":520},
                "size":{
                  "width":258,
                  "height":460}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐就餐流程图/u10.png"}},
{
          "id":"2f6267cf17584e78bfc9f43d9ea1e1c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":390,
              "y":486},
            "size":{
              "width":230,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b3c8e3e84994f11a67ae134929bd73c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":390,
                  "y":486},
                "size":{
                  "width":230,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3512f63c2b0a4b53a17c7ecc4e8e27e1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":706,
              "y":520},
            "size":{
              "width":260,
              "height":460}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eae21ffd53f34372b91f6cf192cda421",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":706,
                  "y":520},
                "size":{
                  "width":260,
                  "height":460}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐就餐流程图/u14.png"}},
{
          "id":"07c0e46d536c4325b786b86910a75ec4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":700,
              "y":486},
            "size":{
              "width":230,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e3841aa85d24aa29b3aed06300a2961",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":700,
                  "y":486},
                "size":{
                  "width":230,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9c7afa155374dd68ef4507f268b604e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1040,
              "y":520},
            "size":{
              "width":263,
              "height":460}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6fddd8c14c14dfd9ac1812be897aa96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1040,
                  "y":520},
                "size":{
                  "width":263,
                  "height":460}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐就餐流程图/u18.png"}},
{
          "id":"c8f5e77a4ced4e1b869e7f3e2a085649",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1040,
              "y":486},
            "size":{
              "width":230,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0976e7244c24a6eb76836aae1f9fd98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1040,
                  "y":486},
                "size":{
                  "width":230,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d230f60a83174ce5afc87d78ff07f1de",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":730},
            "size":{
              "width":236,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/早餐就餐流程图/u22_start.png",
            "end~":"images/早餐就餐流程图/u22_end.png",
            "line~":"images/早餐就餐流程图/u22_line.png"}},
{
          "id":"f2cbd34091a4467e99ca9c10e30b73a7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":950,
              "y":954},
            "size":{
              "width":90,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/早餐就餐流程图/u22_start.png",
            "end~":"images/早餐就餐流程图/u22_end.png",
            "line~":"images/早餐就餐流程图/u23_line.png"}},
{
          "id":"74a37d1321e947d5978d4a83497de599",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1378,
              "y":520},
            "size":{
              "width":258,
              "height":460}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"732c16d40d07444086117245dec127ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1378,
                  "y":520},
                "size":{
                  "width":258,
                  "height":460}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐就餐流程图/u24.png"}},
{
          "id":"3d060c33971541be837c9443e2f1d404",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1378,
              "y":476},
            "size":{
              "width":252,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ef96b79ef96453da82527eb902072b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1378,
                  "y":476},
                "size":{
                  "width":252,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a1b3275bcea49679460a9c5d8de2ffc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1700,
              "y":520},
            "size":{
              "width":258,
              "height":529}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbe6b7bd5556435fb6fff098a068125b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1700,
                  "y":520},
                "size":{
                  "width":258,
                  "height":529}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐就餐流程图/u28.png"}},
{
          "id":"a3b60c4d0084445ea667094acaeb95c2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1303,
              "y":954},
            "size":{
              "width":75,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/早餐就餐流程图/u22_start.png",
            "end~":"images/早餐就餐流程图/u22_end.png",
            "line~":"images/早餐就餐流程图/u30_line.png"}},
{
          "id":"c4c805e0a6864c27b27fd3526acac8f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1700,
              "y":476},
            "size":{
              "width":252,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c722970962904371bf5031240be19491",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1700,
                  "y":476},
                "size":{
                  "width":252,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86bb5fec06684a90ae288e7877c6431b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1622,
              "y":550},
            "size":{
              "width":78,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/早餐就餐流程图/u22_start.png",
            "end~":"images/早餐就餐流程图/u22_end.png",
            "line~":"images/早餐就餐流程图/u33_line.png"}},
{
          "id":"2643d20580de4c81bf74d64f3b58befd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1958,
              "y":750},
            "size":{
              "width":152,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/早餐就餐流程图/u22_start.png",
            "end~":"images/早餐就餐流程图/u22_end.png",
            "line~":"images/早餐就餐流程图/u34_line.png"}},
{
          "id":"1cf5db4e70364d1ea58bbdeca6b58be2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1978,
              "y":723},
            "size":{
              "width":252,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb417019474a49d4b847ceb426de3131",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1978,
                  "y":723},
                "size":{
                  "width":252,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3404a27335dc483c8e6e580d5ec96076",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2110,
              "y":510},
            "size":{
              "width":265,
              "height":539}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15f0a72e7eb2425ca79fe74f11b7781d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2110,
                  "y":510},
                "size":{
                  "width":265,
                  "height":539}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐就餐流程图/u37.png"}},
{
          "id":"940e31bf724d4442a7fb6aef68513e0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":2110,
              "y":476},
            "size":{
              "width":252,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74e75527fc3c4858b6af49d7ff6e659a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":2110,
                  "y":476},
                "size":{
                  "width":252,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ed387b92b214a85b407f2c7d38ae071",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1700,
              "y":1139},
            "size":{
              "width":258,
              "height":455}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91748c733766495da6e4ac03ca71baef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1700,
                  "y":1139},
                "size":{
                  "width":258,
                  "height":455}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐就餐流程图/u41.png"}},
{
          "id":"6182b370ec3b4ba9b96449eee0ef1d4f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1710,
              "y":560},
            "size":{
              "width":10,
              "height":579},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/早餐就餐流程图/u43_start.png",
            "end~":"images/早餐就餐流程图/u43_end.png",
            "line~":"images/早餐就餐流程图/u43_line.png"}},
{
          "id":"dac2a5d2fb7f46d4aeefa87e2b71d529",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":1710,
              "y":1170},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eeb20b94610a47eebcf57f8fa2dda821",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":1710,
                  "y":1170},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"f4b18e5c36ef4a76a01be50bec8d9485",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1720,
              "y":1095},
            "size":{
              "width":252,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"486eaacf650f4e2fbd23e368224659f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1720,
                  "y":1095},
                "size":{
                  "width":252,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e5f006453414001a3c64dd9b2813a9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":2130,
              "y":1095},
            "size":{
              "width":252,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9657fa3bbc7b42abb0b1a573f7b49c7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":2130,
                  "y":1095},
                "size":{
                  "width":252,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac4aaaeb5bad471d999912c9b766a24b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2114,
              "y":1132},
            "size":{
              "width":257,
              "height":452}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"668b602ca7f34df09eb1a054891023a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2114,
                  "y":1132},
                "size":{
                  "width":257,
                  "height":452}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐就餐流程图/u50.png"}},
{
          "id":"20a6e7eadd9949f188545d8ec5752794",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":2120,
              "y":550},
            "size":{
              "width":10,
              "height":582},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/早餐就餐流程图/u43_start.png",
            "end~":"images/早餐就餐流程图/u43_end.png",
            "line~":"images/早餐就餐流程图/u52_line.png"}},
{
          "id":"2b256a2fa89b444db9051cb74bb46410",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":706,
              "y":1173},
            "size":{
              "width":264,
              "height":468}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d5e100b49684d2ab9405b0f467cf9e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":706,
                  "y":1173},
                "size":{
                  "width":264,
                  "height":468}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐就餐流程图/u53.png"}},
{
          "id":"a3a1dd4d359a4a82866721efbd74834c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":706,
              "y":1139},
            "size":{
              "width":230,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fe2d0d5edcc401bbea591f05f9369f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":706,
                  "y":1139},
                "size":{
                  "width":230,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba1b62c4780e4d4aae5442ce4dfd481d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":875,
              "y":560},
            "size":{
              "width":10,
              "height":613},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/早餐就餐流程图/u43_start.png",
            "end~":"images/早餐就餐流程图/u43_end.png",
            "line~":"images/早餐就餐流程图/u57_line.png"}},
{
          "id":"675a05087096467d9644c3e5cc03a921",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":2120,
              "y":1164},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9071d9c2414a4b748a3ddfab9325be61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":2120,
                  "y":1164},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"5499cb485e6d44bcb7df3fcbd35ee78f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":56,
              "y":520},
            "size":{
              "width":254,
              "height":458}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fc3e8fc242446858f22d88308911e56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":56,
                  "y":520},
                "size":{
                  "width":254,
                  "height":458}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐就餐流程图/u60.png"}},
{
          "id":"2ad9ae4dde1549be95deb34881b98e5a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":760},
            "size":{
              "width":90,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/早餐就餐流程图/u22_start.png",
            "end~":"images/早餐就餐流程图/u22_end.png",
            "line~":"images/早餐就餐流程图/u23_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "3310d70bbf7c42499eedd3e8daf8c4b7":{
      "scriptId":"u0"},
    "8f2211f5572d49a4b1bd20275fc6f147":{
      "scriptId":"u1"},
    "c92a9ba662e64b8bbc9dcf8f5971c126":{
      "scriptId":"u2"},
    "d7035641699542b7b46338b9ab79d038":{
      "scriptId":"u3"},
    "4a747870fc4e4960b835d50a067dada7":{
      "scriptId":"u4"},
    "67ac668b1b56432595240df1ea155317":{
      "scriptId":"u5"},
    "54c1da645e754b7dbe0f2bbb7fae6433":{
      "scriptId":"u6"},
    "c47c502f97244b54bc34ad1a457e626a":{
      "scriptId":"u7"},
    "06b8e290351d4a4c8b1e6ca1e848a326":{
      "scriptId":"u8"},
    "51b810f4b33a4b1a8cf6aeacc6805d31":{
      "scriptId":"u9"},
    "423977bc9c5145adb73f02dfc78249bd":{
      "scriptId":"u10"},
    "232009501a744c3e9ef6254b141cb335":{
      "scriptId":"u11"},
    "2f6267cf17584e78bfc9f43d9ea1e1c2":{
      "scriptId":"u12"},
    "5b3c8e3e84994f11a67ae134929bd73c":{
      "scriptId":"u13"},
    "3512f63c2b0a4b53a17c7ecc4e8e27e1":{
      "scriptId":"u14"},
    "eae21ffd53f34372b91f6cf192cda421":{
      "scriptId":"u15"},
    "07c0e46d536c4325b786b86910a75ec4":{
      "scriptId":"u16"},
    "2e3841aa85d24aa29b3aed06300a2961":{
      "scriptId":"u17"},
    "f9c7afa155374dd68ef4507f268b604e":{
      "scriptId":"u18"},
    "c6fddd8c14c14dfd9ac1812be897aa96":{
      "scriptId":"u19"},
    "c8f5e77a4ced4e1b869e7f3e2a085649":{
      "scriptId":"u20"},
    "a0976e7244c24a6eb76836aae1f9fd98":{
      "scriptId":"u21"},
    "d230f60a83174ce5afc87d78ff07f1de":{
      "scriptId":"u22"},
    "f2cbd34091a4467e99ca9c10e30b73a7":{
      "scriptId":"u23"},
    "74a37d1321e947d5978d4a83497de599":{
      "scriptId":"u24"},
    "732c16d40d07444086117245dec127ab":{
      "scriptId":"u25"},
    "3d060c33971541be837c9443e2f1d404":{
      "scriptId":"u26"},
    "7ef96b79ef96453da82527eb902072b2":{
      "scriptId":"u27"},
    "4a1b3275bcea49679460a9c5d8de2ffc":{
      "scriptId":"u28"},
    "cbe6b7bd5556435fb6fff098a068125b":{
      "scriptId":"u29"},
    "a3b60c4d0084445ea667094acaeb95c2":{
      "scriptId":"u30"},
    "c4c805e0a6864c27b27fd3526acac8f5":{
      "scriptId":"u31"},
    "c722970962904371bf5031240be19491":{
      "scriptId":"u32"},
    "86bb5fec06684a90ae288e7877c6431b":{
      "scriptId":"u33"},
    "2643d20580de4c81bf74d64f3b58befd":{
      "scriptId":"u34"},
    "1cf5db4e70364d1ea58bbdeca6b58be2":{
      "scriptId":"u35"},
    "eb417019474a49d4b847ceb426de3131":{
      "scriptId":"u36"},
    "3404a27335dc483c8e6e580d5ec96076":{
      "scriptId":"u37"},
    "15f0a72e7eb2425ca79fe74f11b7781d":{
      "scriptId":"u38"},
    "940e31bf724d4442a7fb6aef68513e0e":{
      "scriptId":"u39"},
    "74e75527fc3c4858b6af49d7ff6e659a":{
      "scriptId":"u40"},
    "3ed387b92b214a85b407f2c7d38ae071":{
      "scriptId":"u41"},
    "91748c733766495da6e4ac03ca71baef":{
      "scriptId":"u42"},
    "6182b370ec3b4ba9b96449eee0ef1d4f":{
      "scriptId":"u43"},
    "dac2a5d2fb7f46d4aeefa87e2b71d529":{
      "scriptId":"u44"},
    "eeb20b94610a47eebcf57f8fa2dda821":{
      "scriptId":"u45"},
    "f4b18e5c36ef4a76a01be50bec8d9485":{
      "scriptId":"u46"},
    "486eaacf650f4e2fbd23e368224659f0":{
      "scriptId":"u47"},
    "8e5f006453414001a3c64dd9b2813a9c":{
      "scriptId":"u48"},
    "9657fa3bbc7b42abb0b1a573f7b49c7a":{
      "scriptId":"u49"},
    "ac4aaaeb5bad471d999912c9b766a24b":{
      "scriptId":"u50"},
    "668b602ca7f34df09eb1a054891023a5":{
      "scriptId":"u51"},
    "20a6e7eadd9949f188545d8ec5752794":{
      "scriptId":"u52"},
    "2b256a2fa89b444db9051cb74bb46410":{
      "scriptId":"u53"},
    "3d5e100b49684d2ab9405b0f467cf9e6":{
      "scriptId":"u54"},
    "a3a1dd4d359a4a82866721efbd74834c":{
      "scriptId":"u55"},
    "1fe2d0d5edcc401bbea591f05f9369f7":{
      "scriptId":"u56"},
    "ba1b62c4780e4d4aae5442ce4dfd481d":{
      "scriptId":"u57"},
    "675a05087096467d9644c3e5cc03a921":{
      "scriptId":"u58"},
    "9071d9c2414a4b748a3ddfab9325be61":{
      "scriptId":"u59"},
    "5499cb485e6d44bcb7df3fcbd35ee78f":{
      "scriptId":"u60"},
    "6fc3e8fc242446858f22d88308911e56":{
      "scriptId":"u61"},
    "2ad9ae4dde1549be95deb34881b98e5a":{
      "scriptId":"u62"}}});