$axure.loadCurrentPage({
  "url":"下单.html",
  "generationDate":new Date(1448611751349.33),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"tplb_img",
"jdt_bfb",
"qsjs_r",
"tpcc_wz",
"tpcc_zt",
"tpcc_kd",
"yz_msg"],
  "page":{
    "packageId":"61fafeb4910545d5a4386cee34f9c215",
    "type":"Axure:Page",
    "name":"下单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"90a6b778c76242f8be529c11bffeed33",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":320,
              "height":568},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd9f81613b2545b0a514ff2ca6aa1d74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":320,
                  "height":568},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u0.png"}},
{
          "id":"d42eeee33c3640648851593d8534fc40",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":20},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22c28264bfb145389d2c13d4f7883a71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":20},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u2.png"}},
{
          "id":"9b49989acf2d44c1aac4a72e732795d0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":35},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bce4e806168a401488f8cb2de1e5266f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":35},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u4.png"}},
{
          "id":"10e94b7898da41a989e5c2de990d74c1",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":132,
              "y":46},
            "size":{
              "width":95,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05655e34aa2d48779f055cb947c26c52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":132,
                  "y":46},
                "size":{
                  "width":95,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17c437624ebb4a7480800784a0a264d8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":48},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"add311b7133b4e529d08aa005ddd28e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":48},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u8.png"}},
{
          "id":"8076d618dcbf40f19bc814f5d0001019",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":82},
            "size":{
              "width":320,
              "height":258},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1efe20d310b640239bff397f5de978b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":82},
                "size":{
                  "width":320,
                  "height":258},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下单/u10.png"}},
{
          "id":"939a2fc71fac4655ae81d35c7482afa7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":31,
              "y":98},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e9b22d72e9e44709ab5fd27f6e5cb45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":31,
                  "y":98},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a8cb491a2ef41b898be86345ea01916",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":172},
            "size":{
              "width":219,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab36cba081044f699c7fd73a32402224",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":172},
                "size":{
                  "width":219,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6923b8cdf39449aaa596708565d5097b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":223,
              "y":172},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96f27804d8e34260b2e4a3cb1814eb47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":223,
                  "y":172},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c87ef3c74cb44009b055d9b6e3eeb943",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":290,
              "y":172},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56561ffcbd194460966de0bd0c4434aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":290,
                  "y":172},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05263df443a249ca9b190c211bbbe4e0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":118},
            "size":{
              "width":304,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC8C8C8}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/下单/u20_line.png"}},
{
          "id":"9596670b9e474054bc286927b09f6aaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":31,
              "y":134},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd5f569d1a454d85aa0664a61fa65fd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":31,
                  "y":134},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23e3beebcd0048cdad5af3e774af3708",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":188},
            "size":{
              "width":304,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC8C8C8}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/下单/u20_line.png"}},
{
          "id":"64d4cd391a4443b8a4f7a1373dbab4a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":538},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d57adef20c254fc08a34c546b11f7f81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":538},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u48.png"}},
{
          "id":"9c0330ea2aba4a019d3ff474b9801ab3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":240,
              "y":538},
            "size":{
              "width":100,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a87fac2b752f489fbd8e48f34808ac0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":240,
                  "y":538},
                "size":{
                  "width":100,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u52.png"}},
{
          "id":"85eedefdfe0f469a8b32f79c08d6b9f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":31,
              "y":208},
            "size":{
              "width":99,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a24f81b50de04fc78260d1c569516dda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":31,
                  "y":208},
                "size":{
                  "width":99,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c517adfa7a4453bb5450fceb4792725",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":90,
              "y":250},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b63602c1535f47daa1d70c9d52bc5148",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":90,
                  "y":250},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下单/u30.png"}},
{
          "id":"f7adeedb729a4df19f0d70d2138bca1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":190,
              "y":250},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18ce27abe13e419abc2836cf3c47e875",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":190,
                  "y":250},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下单/u30.png"}},
{
          "id":"d49bd78b13d7431b97f7adb40531a540",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":31,
              "y":555},
            "size":{
              "width":89,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e67098109e8b4ce2a7e8ebceabf32456",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":31,
                  "y":555},
                "size":{
                  "width":89,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "90a6b778c76242f8be529c11bffeed33":{
      "scriptId":"u0"},
    "bd9f81613b2545b0a514ff2ca6aa1d74":{
      "scriptId":"u1"},
    "d42eeee33c3640648851593d8534fc40":{
      "scriptId":"u2"},
    "22c28264bfb145389d2c13d4f7883a71":{
      "scriptId":"u3"},
    "9b49989acf2d44c1aac4a72e732795d0":{
      "scriptId":"u4"},
    "bce4e806168a401488f8cb2de1e5266f":{
      "scriptId":"u5"},
    "10e94b7898da41a989e5c2de990d74c1":{
      "scriptId":"u6"},
    "05655e34aa2d48779f055cb947c26c52":{
      "scriptId":"u7"},
    "17c437624ebb4a7480800784a0a264d8":{
      "scriptId":"u8"},
    "add311b7133b4e529d08aa005ddd28e2":{
      "scriptId":"u9"},
    "8076d618dcbf40f19bc814f5d0001019":{
      "scriptId":"u10"},
    "1efe20d310b640239bff397f5de978b7":{
      "scriptId":"u11"},
    "939a2fc71fac4655ae81d35c7482afa7":{
      "scriptId":"u12"},
    "3e9b22d72e9e44709ab5fd27f6e5cb45":{
      "scriptId":"u13"},
    "1a8cb491a2ef41b898be86345ea01916":{
      "scriptId":"u14"},
    "ab36cba081044f699c7fd73a32402224":{
      "scriptId":"u15"},
    "6923b8cdf39449aaa596708565d5097b":{
      "scriptId":"u16"},
    "96f27804d8e34260b2e4a3cb1814eb47":{
      "scriptId":"u17"},
    "c87ef3c74cb44009b055d9b6e3eeb943":{
      "scriptId":"u18"},
    "56561ffcbd194460966de0bd0c4434aa":{
      "scriptId":"u19"},
    "05263df443a249ca9b190c211bbbe4e0":{
      "scriptId":"u20"},
    "9596670b9e474054bc286927b09f6aaa":{
      "scriptId":"u21"},
    "bd5f569d1a454d85aa0664a61fa65fd0":{
      "scriptId":"u22"},
    "23e3beebcd0048cdad5af3e774af3708":{
      "scriptId":"u23"},
    "64d4cd391a4443b8a4f7a1373dbab4a8":{
      "scriptId":"u24"},
    "d57adef20c254fc08a34c546b11f7f81":{
      "scriptId":"u25"},
    "9c0330ea2aba4a019d3ff474b9801ab3":{
      "scriptId":"u26"},
    "a87fac2b752f489fbd8e48f34808ac0f":{
      "scriptId":"u27"},
    "85eedefdfe0f469a8b32f79c08d6b9f6":{
      "scriptId":"u28"},
    "a24f81b50de04fc78260d1c569516dda":{
      "scriptId":"u29"},
    "7c517adfa7a4453bb5450fceb4792725":{
      "scriptId":"u30"},
    "b63602c1535f47daa1d70c9d52bc5148":{
      "scriptId":"u31"},
    "f7adeedb729a4df19f0d70d2138bca1f":{
      "scriptId":"u32"},
    "18ce27abe13e419abc2836cf3c47e875":{
      "scriptId":"u33"},
    "d49bd78b13d7431b97f7adb40531a540":{
      "scriptId":"u34"},
    "e67098109e8b4ce2a7e8ebceabf32456":{
      "scriptId":"u35"}}});