$axure.loadCurrentPage({
  "url":"午餐就餐流程图.html",
  "generationDate":new Date(1448611751094.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"tplb_img",
"jdt_bfb",
"qsjs_r",
"tpcc_wz",
"tpcc_zt",
"tpcc_kd",
"yz_msg"],
  "page":{
    "packageId":"0d9525de90b8442e9106cf6be7ee8457",
    "type":"Axure:Page",
    "name":"午餐就餐流程图",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3b270b5b17db4075aef477adb39fe25a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":0,
              "y":-10},
            "size":{
              "width":2800,
              "height":2080}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a82eba4ffa3c4e919fe906e236b4c0c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":0,
                  "y":-10},
                "size":{
                  "width":2800,
                  "height":2080}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/午餐就餐流程图/u0.png"}},
{
          "id":"6845cff391ce4330bf30c9d604ca3a71",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":77,
              "y":307},
            "size":{
              "width":373,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81e898f0cb2b4046aa0f2daa1c33465a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":77,
                  "y":307},
                "size":{
                  "width":373,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8907c53b0da4451b6b514bee38b499b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":77,
              "y":30},
            "size":{
              "width":373,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"046e90c501354ee6a9cc5f2f48a84cda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":77,
                  "y":30},
                "size":{
                  "width":373,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d24d51090c854a31ba5014fb49bb0c53",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":110},
            "size":{
              "width":725,
              "height":126}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a0ed972de13486791b4ceb1fde75193",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":110},
                "size":{
                  "width":725,
                  "height":126}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/午餐就餐流程图/u6.png"}},
{
          "id":"c3d6fea679254e37b1ac7dbdc51742e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":77,
              "y":386},
            "size":{
              "width":128,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e89afe07196747acbcfa8edc0978fc83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":77,
                  "y":386},
                "size":{
                  "width":128,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2a895c08d1f46b8959f30b0bc102c33",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":420},
            "size":{
              "width":258,
              "height":460}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abc558b3a95349e195dc6c4fc8a77437",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":420},
                "size":{
                  "width":258,
                  "height":460}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐就餐流程图/u10.png"}},
{
          "id":"c5be54728e4d487b8adabb2dbf143469",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":390,
              "y":386},
            "size":{
              "width":230,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68be795cc32942cba5f8cb25a69b7749",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":390,
                  "y":386},
                "size":{
                  "width":230,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"55f0c367b6fe48d5b64290fc6fedf75e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":628},
            "size":{
              "width":110,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/早餐就餐流程图/u22_start.png",
            "end~":"images/早餐就餐流程图/u22_end.png",
            "line~":"images/午餐就餐流程图/u14_line.png"}},
{
          "id":"f6a561501fd945f497b7e1037aafc7db",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":715,
              "y":420},
            "size":{
              "width":251,
              "height":460}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a716454de4342a1a365c635c93b9e3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":715,
                  "y":420},
                "size":{
                  "width":251,
                  "height":460}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/午餐就餐流程图/u15.png"}},
{
          "id":"b32fa541a11349a6955b53d8dd3730f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":710,
              "y":386},
            "size":{
              "width":230,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f557d6a93f54eaeb1a7eb88795a7675",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":710,
                  "y":386},
                "size":{
                  "width":230,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3abb74dd7534cc6b89998ceaa848f37",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1047,
              "y":415},
            "size":{
              "width":253,
              "height":470}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71b5bea1e746416d9a2335f6ce149b7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1047,
                  "y":415},
                "size":{
                  "width":253,
                  "height":470}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/午餐就餐流程图/u19.png"}},
{
          "id":"791ed22b99d04e2daea21921745eba19",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":937,
              "y":705},
            "size":{
              "width":110,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/早餐就餐流程图/u22_start.png",
            "end~":"images/早餐就餐流程图/u22_end.png",
            "line~":"images/午餐就餐流程图/u14_line.png"}},
{
          "id":"dd1dcc2819cd46158c2a222833e4b501",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":420},
            "size":{
              "width":254,
              "height":458}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"121913763e384a68af8dd1052b8c0334",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":66,
                  "y":420},
                "size":{
                  "width":254,
                  "height":458}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐就餐流程图/u60.png"}},
{
          "id":"d8a05e93bc7f45e59fc97abc2bf9a9d9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":660},
            "size":{
              "width":110,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/早餐就餐流程图/u22_start.png",
            "end~":"images/早餐就餐流程图/u22_end.png",
            "line~":"images/午餐就餐流程图/u14_line.png"}},
{
          "id":"2964acb74adc46e99f293080da4b79d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1047,
              "y":376},
            "size":{
              "width":230,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3b9f299ef5947f0a31cb2c480fb3f09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1047,
                  "y":376},
                "size":{
                  "width":230,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3b270b5b17db4075aef477adb39fe25a":{
      "scriptId":"u0"},
    "a82eba4ffa3c4e919fe906e236b4c0c1":{
      "scriptId":"u1"},
    "6845cff391ce4330bf30c9d604ca3a71":{
      "scriptId":"u2"},
    "81e898f0cb2b4046aa0f2daa1c33465a":{
      "scriptId":"u3"},
    "f8907c53b0da4451b6b514bee38b499b":{
      "scriptId":"u4"},
    "046e90c501354ee6a9cc5f2f48a84cda":{
      "scriptId":"u5"},
    "d24d51090c854a31ba5014fb49bb0c53":{
      "scriptId":"u6"},
    "2a0ed972de13486791b4ceb1fde75193":{
      "scriptId":"u7"},
    "c3d6fea679254e37b1ac7dbdc51742e0":{
      "scriptId":"u8"},
    "e89afe07196747acbcfa8edc0978fc83":{
      "scriptId":"u9"},
    "f2a895c08d1f46b8959f30b0bc102c33":{
      "scriptId":"u10"},
    "abc558b3a95349e195dc6c4fc8a77437":{
      "scriptId":"u11"},
    "c5be54728e4d487b8adabb2dbf143469":{
      "scriptId":"u12"},
    "68be795cc32942cba5f8cb25a69b7749":{
      "scriptId":"u13"},
    "55f0c367b6fe48d5b64290fc6fedf75e":{
      "scriptId":"u14"},
    "f6a561501fd945f497b7e1037aafc7db":{
      "scriptId":"u15"},
    "1a716454de4342a1a365c635c93b9e3a":{
      "scriptId":"u16"},
    "b32fa541a11349a6955b53d8dd3730f6":{
      "scriptId":"u17"},
    "5f557d6a93f54eaeb1a7eb88795a7675":{
      "scriptId":"u18"},
    "f3abb74dd7534cc6b89998ceaa848f37":{
      "scriptId":"u19"},
    "71b5bea1e746416d9a2335f6ce149b7a":{
      "scriptId":"u20"},
    "791ed22b99d04e2daea21921745eba19":{
      "scriptId":"u21"},
    "dd1dcc2819cd46158c2a222833e4b501":{
      "scriptId":"u22"},
    "121913763e384a68af8dd1052b8c0334":{
      "scriptId":"u23"},
    "d8a05e93bc7f45e59fc97abc2bf9a9d9":{
      "scriptId":"u24"},
    "2964acb74adc46e99f293080da4b79d7":{
      "scriptId":"u25"},
    "b3b9f299ef5947f0a31cb2c480fb3f09":{
      "scriptId":"u26"}}});