$axure.loadCurrentPage({
  "url":"生成早餐券.html",
  "generationDate":new Date(1448450537102.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"tplb_img",
"jdt_bfb",
"qsjs_r",
"tpcc_wz",
"tpcc_zt",
"tpcc_kd",
"yz_msg"],
  "page":{
    "packageId":"53c108ccf02c4f14b908ef3600739a04",
    "type":"Axure:Page",
    "name":"生成早餐券",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8a1cad872bf5499ba752f769efa8f64c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":40,
              "y":100},
            "size":{
              "width":320,
              "height":568},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa0e72a03d2c4a79868c54b740f46392",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":40,
                  "y":100},
                "size":{
                  "width":320,
                  "height":568},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u0.png"}},
{
          "id":"965d5725e94a4101af4394fe4c512bcd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":100},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21cad8b0f5e04be8b436825193e8e933",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":100},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u2.png"}},
{
          "id":"7eee460c853a4a90842e413cf40e751a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":115},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7579891c089a4601af32bb3e9db0153c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":115},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u4.png"}},
{
          "id":"52b8ddf168504955b467f031a93d8f74",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":152,
              "y":126},
            "size":{
              "width":138,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85bc9d47f93f41cc9aa07e9bb0dffdc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":152,
                  "y":126},
                "size":{
                  "width":138,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9688dcdef4eb4a37bf219f378090df3a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":128},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"423e080a0783418bafe05cc459b1a23f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":128},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u8.png"}},
{
          "id":"f9af53bfd52f467894392d8e594e1d1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":162},
            "size":{
              "width":320,
              "height":288},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dda0430fe504cccaad49a2d9aa3b269",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":162},
                "size":{
                  "width":320,
                  "height":288},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生成早餐券/u10.png"}},
{
          "id":"5688a90bbbce4d70b4c7011f0bc72315",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":51,
              "y":178},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fca70e840bdf4ad0bc631cc3b43424a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":51,
                  "y":178},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45cbe291e9a74ffc9921e9eec64b0147",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":252},
            "size":{
              "width":219,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"806c93b15fe34101b3e28c3939712518",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":252},
                "size":{
                  "width":219,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae9d5581f585498a9e569507e38678c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":252},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dbd90a1143647b0bd9bf9fe10500942",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":252},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16f8a2b6b0dd4b33818cd36ee5606760",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":310,
              "y":252},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f07f375f2d02483f999b8cb50a8b6f8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":310,
                  "y":252},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ce31f401f4e46c4bc106b0d67258831",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":198},
            "size":{
              "width":304,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC8C8C8}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/下单/u20_line.png"}},
{
          "id":"61a293428e3b4960b38aee6c23709635",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":51,
              "y":214},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3489a2bb0284a769537dad317c2aa12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":51,
                  "y":214},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c161d1dc5564f29b74a4d96832d176c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":286},
            "size":{
              "width":304,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC8C8C8}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/下单/u20_line.png"}},
{
          "id":"0e6db436e98f47bab6afa0528d78db6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":51,
              "y":306},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22e1ef554b2244b3bdf2a170ad9b5f40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":51,
                  "y":306},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a2db5b435304bd6b2c4dcc19ea6e8e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":643},
            "size":{
              "width":320,
              "height":208},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b1207f2988f41438491aa07c9334062",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":643},
                "size":{
                  "width":320,
                  "height":208},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生成早餐券/u26.png"}},
{
          "id":"c03c00c961b5493f9f6e7f7d761b399b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":54,
              "y":660},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a3e892b3e3d49e5b86b38eafc982e04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":54,
                  "y":660},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c78edd5a474840ef80cb995c5e1a963b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":681},
            "size":{
              "width":304,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC8C8C8}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/下单/u20_line.png"}},
{
          "id":"54aeb91050324c0bb69d820d39129682",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":54,
              "y":725},
            "size":{
              "width":249,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d036b41d226d4d5f91d00ec88530d1bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":54,
                  "y":725},
                "size":{
                  "width":249,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39cb5cdf0155479b896ae5d6689664e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":54,
              "y":751},
            "size":{
              "width":289,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fcbcfef90684571999dc23e36088cf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":54,
                  "y":751},
                "size":{
                  "width":289,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5003cc3bff94afa8dfe69ec1494d1d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":54,
              "y":777},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64f594ef6dd4495191aa5b180433d9f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":54,
                  "y":777},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a0db1b6d7cf4e738b6f00973610090d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":54,
              "y":699},
            "size":{
              "width":209,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62266e19cf054d1f8c6592ba4b0e7547",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":54,
                  "y":699},
                "size":{
                  "width":209,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6331ef7b4654f1fb42cf3744d4b38d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":54,
              "y":803},
            "size":{
              "width":309,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b2b23533dbc4c9e920e2023d6d0555e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":54,
                  "y":803},
                "size":{
                  "width":309,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56097d7065344da9a7b02f552bc4904f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":480,
              "y":102},
            "size":{
              "width":320,
              "height":568},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71b231fcdaee4b0e8eecdd37a96793aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":480,
                  "y":102},
                "size":{
                  "width":320,
                  "height":568},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u0.png"}},
{
          "id":"b8ec33f79f054b769425ca81ac57f6c0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":487,
              "y":102},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bd5ccbaea39429496a536a5cbd59a90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":487,
                  "y":102},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u2.png"}},
{
          "id":"706c29f3fa45407e8cb8f6a2f912e5ca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":117},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d814bac9395842178d78dc7fe59ecce3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":117},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u4.png"}},
{
          "id":"c144861b793942638ffb037cb24738ec",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":592,
              "y":128},
            "size":{
              "width":138,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8de1ccf839094e50b65c0335a590619a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":592,
                  "y":128},
                "size":{
                  "width":138,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40aec98d502240388589c18e87b8414d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":491,
              "y":130},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ae62cdeac344c55948c9c31ea3edfbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":491,
                  "y":130},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u8.png"}},
{
          "id":"0f9a6c30b77444a8b25e298559690911",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":164},
            "size":{
              "width":320,
              "height":288},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55815409cf3f4b23a53d1895d8217a52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":164},
                "size":{
                  "width":320,
                  "height":288},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生成早餐券/u10.png"}},
{
          "id":"b768fa29045e4ed8ba9f5beb247e6ab9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":491,
              "y":180},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f014d5514d444a09dacb72a69ec56de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":491,
                  "y":180},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec76011eb69140a6bf8bc665e44aee88",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":491,
              "y":254},
            "size":{
              "width":219,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b310d43a36324804affe31b0bdf30e74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":491,
                  "y":254},
                "size":{
                  "width":219,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d0b133f64ea4acdbe9a77ab2b908940",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":683,
              "y":254},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19743b7d862b412ea18d5ec813f38add",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":683,
                  "y":254},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3141680bbe4b4db79cbc1f23e069527f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":750,
              "y":254},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66b73b0c08bb42c892c7f6136679debe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":750,
                  "y":254},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1279c0748c742db809a9fc29741bb30",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":491,
              "y":200},
            "size":{
              "width":304,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC8C8C8}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/下单/u20_line.png"}},
{
          "id":"1c44f801283543f08271b1a409faf417",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":491,
              "y":216},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f96bd3b2b984599a5ea31604a84371c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":491,
                  "y":216},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"caba516e2a36405a85265d0816089933",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":491,
              "y":288},
            "size":{
              "width":304,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC8C8C8}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/下单/u20_line.png"}},
{
          "id":"71717e97b9514909ba5b4eb52e8b390f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":491,
              "y":308},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd7ec54ebe2d48e695f116907304df16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":491,
                  "y":308},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"55f3b0aa47bd4d229cbd4f6531f6c138",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":582},
            "size":{
              "width":320,
              "height":208},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4305bcbcd67643ffa19edfaf3ade0efd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":582},
                "size":{
                  "width":320,
                  "height":208},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生成早餐券/u26.png"}},
{
          "id":"0d2038ee2dae4a9b9e965653e00b995c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":491,
              "y":599},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f70b695fda543018e19ff697b803973",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":491,
                  "y":599},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb940abead8c4da3ba22555af3d4d16c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":491,
              "y":620},
            "size":{
              "width":304,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC8C8C8}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/下单/u20_line.png"}},
{
          "id":"ac0c10ab39fc4d0fae8a486eaafb3d57",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":491,
              "y":664},
            "size":{
              "width":249,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4815350b065b461d8e33d8c4d0b1d578",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":491,
                  "y":664},
                "size":{
                  "width":249,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f55d4ae164094fd6b0d2a22daf7f4629",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":491,
              "y":690},
            "size":{
              "width":289,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77db030925f04a89a344ca44cce0c429",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":491,
                  "y":690},
                "size":{
                  "width":289,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f4fa569778646cb80ca12611c3e9cf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":491,
              "y":716},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f8ca1a240d4473785cbbc7603497324",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":491,
                  "y":716},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"831a32f7aee04f23a1415ff7bb2237fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":491,
              "y":638},
            "size":{
              "width":209,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0bf4cdcd06d4c79a2074271e69d18fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":491,
                  "y":638},
                "size":{
                  "width":209,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a8b1de7413f4058ab17fc22784c636b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":491,
              "y":742},
            "size":{
              "width":309,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b827c71735a84aa4b9bfc2fcbd8140e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":491,
                  "y":742},
                "size":{
                  "width":309,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e78456cf03e14087a3b1176c19487765",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":40},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fffbbd41231443794e4276d67d4628c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":40},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0f3eeb98fab460db7c05a178689861a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":40},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c56872584e34df781bc2cb5d08b2d27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":40},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78fc146a2430452ca6a9c005cbf056b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":153,
              "y":334},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ac576a1a30a4a83a4c1c828349762ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":153,
                  "y":334},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生成早餐券/u86.png"}},
{
          "id":"a7d446b6728a4a94a673e3e31af4c4d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":340},
            "size":{
              "width":100,
              "height":94}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28411ddde2b744d18d1a58370263358d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":340},
                "size":{
                  "width":100,
                  "height":94}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生成早餐券/u88.png"}},
{
          "id":"a2a02a8ea76f4c20954efa01930dfb57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0x87797979},
            "location":{
              "x":615,
              "y":355.5},
            "size":{
              "width":70,
              "height":69},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6be5cac9882473ba6f57483f8eaf6dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0x87797979},
                "location":{
                  "x":615,
                  "y":355.5},
                "size":{
                  "width":70,
                  "height":69},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生成早餐券/u90.png"}},
{
          "id":"22e323fa02fc4c0a9d13b9818dce596b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":522},
            "size":{
              "width":320,
              "height":110},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96357d97df2b4e93a51649bb4af40d79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":522},
                "size":{
                  "width":320,
                  "height":110},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生成早餐券/u92.png"}},
{
          "id":"1be0411be37943f689d89a0786e7e142",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":536},
            "size":{
              "width":229,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8768e60c11ee403badcce2e53054b400",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":536},
                "size":{
                  "width":229,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6664590ccafa4afdba000a5e00773ba6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":54,
              "y":571},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19324e738b224d2d8edd54af7350ce93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":54,
                  "y":571},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32d38dece9284ffb8eb371b5d63e088a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":597},
            "size":{
              "width":209,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e308193e5c7f48f1835f8ceb9c1265ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":597},
                "size":{
                  "width":209,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fb3287f79454e91b4ad1526b9bf0583",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":462},
            "size":{
              "width":320,
              "height":110},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"107a6a01f7e64cefaf829416d03672f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":462},
                "size":{
                  "width":320,
                  "height":110},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生成早餐券/u92.png"}},
{
          "id":"a62edb428b964d6b99218e80020d7520",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":491,
              "y":476},
            "size":{
              "width":229,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d72cdf39d344d7f91673d9fc5578292",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":491,
                  "y":476},
                "size":{
                  "width":229,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff2f89fd6b8c4a2db780af960f3e091c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":491,
              "y":511},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e70c872829c04ac9bd3cf9e8c9489a3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":491,
                  "y":511},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37ab19e39e624796b6288e42cfe0694e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":491,
              "y":537},
            "size":{
              "width":209,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b79127cf6c314b2e8135f11d27efaab1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":491,
                  "y":537},
                "size":{
                  "width":209,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0cd3ae862ef74308b6760b0836a9debc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":464},
            "size":{
              "width":320,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7405d1f70905455fab2aba878aa23404",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":464},
                "size":{
                  "width":320,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生成早餐券/u108.png"}},
{
          "id":"3f986e53b01a4cf2a93218d69f6981ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":480},
            "size":{
              "width":166,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee9af97eed874189b5bdfeca4c817f78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":480},
                "size":{
                  "width":166,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7617961206b54cf1a65b61093985f58c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":472.5},
            "size":{
              "width":70,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 退款二次确认",
                      "objectsToFades":[{
                          "objectPath":["ef63aaeeabec4f778583a7cfc86252a4"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"ef63aaeeabec4f778583a7cfc86252a4",
          "label":"退款二次确认",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":66,
              "y":291},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"478fb010889343a8b9a7b065ae14f5ed",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a9206a3507e94b4c98ca6d9126729f59",
                  "label":"",
                  "parentDynamicPanel":"ef63aaeeabec4f778583a7cfc86252a4",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"bold",
                    "size":{
                      "width":270,
                      "height":173},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7beed3e358ec4dfb9454e71d45a6f87d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ef63aaeeabec4f778583a7cfc86252a4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"bold",
                        "size":{
                          "width":270,
                          "height":173},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/生成早餐券/u114.png"}},
{
                  "id":"a356fe5b6bee4dc1a8f4a6c5c1b4753e",
                  "label":"",
                  "parentDynamicPanel":"ef63aaeeabec4f778583a7cfc86252a4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":57,
                      "y":70},
                    "size":{
                      "width":213,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bd902e0e2ce744d986da9f1f8aff99cb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ef63aaeeabec4f778583a7cfc86252a4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "location":{
                          "x":57,
                          "y":70},
                        "size":{
                          "width":213,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c8601d98bfa345958cb70167a9b6de30",
                  "label":"",
                  "parentDynamicPanel":"ef63aaeeabec4f778583a7cfc86252a4",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":56,
                      "y":140},
                    "size":{
                      "width":37,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4340bed4e9834c989a643249a52c3645",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ef63aaeeabec4f778583a7cfc86252a4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":56,
                          "y":140},
                        "size":{
                          "width":37,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"21992c63e5bf466ba3dd1f26b2a35d60",
                  "label":"",
                  "parentDynamicPanel":"ef63aaeeabec4f778583a7cfc86252a4",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":176,
                      "y":140},
                    "size":{
                      "width":37,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"36ba2970208a44cd98e33778871f2564",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ef63aaeeabec4f778583a7cfc86252a4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":176,
                          "y":140},
                        "size":{
                          "width":37,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "8a1cad872bf5499ba752f769efa8f64c":{
      "scriptId":"u0"},
    "aa0e72a03d2c4a79868c54b740f46392":{
      "scriptId":"u1"},
    "965d5725e94a4101af4394fe4c512bcd":{
      "scriptId":"u2"},
    "21cad8b0f5e04be8b436825193e8e933":{
      "scriptId":"u3"},
    "7eee460c853a4a90842e413cf40e751a":{
      "scriptId":"u4"},
    "7579891c089a4601af32bb3e9db0153c":{
      "scriptId":"u5"},
    "52b8ddf168504955b467f031a93d8f74":{
      "scriptId":"u6"},
    "85bc9d47f93f41cc9aa07e9bb0dffdc8":{
      "scriptId":"u7"},
    "9688dcdef4eb4a37bf219f378090df3a":{
      "scriptId":"u8"},
    "423e080a0783418bafe05cc459b1a23f":{
      "scriptId":"u9"},
    "f9af53bfd52f467894392d8e594e1d1a":{
      "scriptId":"u10"},
    "4dda0430fe504cccaad49a2d9aa3b269":{
      "scriptId":"u11"},
    "5688a90bbbce4d70b4c7011f0bc72315":{
      "scriptId":"u12"},
    "fca70e840bdf4ad0bc631cc3b43424a1":{
      "scriptId":"u13"},
    "45cbe291e9a74ffc9921e9eec64b0147":{
      "scriptId":"u14"},
    "806c93b15fe34101b3e28c3939712518":{
      "scriptId":"u15"},
    "ae9d5581f585498a9e569507e38678c5":{
      "scriptId":"u16"},
    "9dbd90a1143647b0bd9bf9fe10500942":{
      "scriptId":"u17"},
    "16f8a2b6b0dd4b33818cd36ee5606760":{
      "scriptId":"u18"},
    "f07f375f2d02483f999b8cb50a8b6f8c":{
      "scriptId":"u19"},
    "6ce31f401f4e46c4bc106b0d67258831":{
      "scriptId":"u20"},
    "61a293428e3b4960b38aee6c23709635":{
      "scriptId":"u21"},
    "f3489a2bb0284a769537dad317c2aa12":{
      "scriptId":"u22"},
    "4c161d1dc5564f29b74a4d96832d176c":{
      "scriptId":"u23"},
    "0e6db436e98f47bab6afa0528d78db6c":{
      "scriptId":"u24"},
    "22e1ef554b2244b3bdf2a170ad9b5f40":{
      "scriptId":"u25"},
    "5a2db5b435304bd6b2c4dcc19ea6e8e5":{
      "scriptId":"u26"},
    "0b1207f2988f41438491aa07c9334062":{
      "scriptId":"u27"},
    "c03c00c961b5493f9f6e7f7d761b399b":{
      "scriptId":"u28"},
    "5a3e892b3e3d49e5b86b38eafc982e04":{
      "scriptId":"u29"},
    "c78edd5a474840ef80cb995c5e1a963b":{
      "scriptId":"u30"},
    "54aeb91050324c0bb69d820d39129682":{
      "scriptId":"u31"},
    "d036b41d226d4d5f91d00ec88530d1bd":{
      "scriptId":"u32"},
    "39cb5cdf0155479b896ae5d6689664e9":{
      "scriptId":"u33"},
    "9fcbcfef90684571999dc23e36088cf9":{
      "scriptId":"u34"},
    "b5003cc3bff94afa8dfe69ec1494d1d3":{
      "scriptId":"u35"},
    "64f594ef6dd4495191aa5b180433d9f7":{
      "scriptId":"u36"},
    "3a0db1b6d7cf4e738b6f00973610090d":{
      "scriptId":"u37"},
    "62266e19cf054d1f8c6592ba4b0e7547":{
      "scriptId":"u38"},
    "e6331ef7b4654f1fb42cf3744d4b38d7":{
      "scriptId":"u39"},
    "7b2b23533dbc4c9e920e2023d6d0555e":{
      "scriptId":"u40"},
    "56097d7065344da9a7b02f552bc4904f":{
      "scriptId":"u41"},
    "71b231fcdaee4b0e8eecdd37a96793aa":{
      "scriptId":"u42"},
    "b8ec33f79f054b769425ca81ac57f6c0":{
      "scriptId":"u43"},
    "4bd5ccbaea39429496a536a5cbd59a90":{
      "scriptId":"u44"},
    "706c29f3fa45407e8cb8f6a2f912e5ca":{
      "scriptId":"u45"},
    "d814bac9395842178d78dc7fe59ecce3":{
      "scriptId":"u46"},
    "c144861b793942638ffb037cb24738ec":{
      "scriptId":"u47"},
    "8de1ccf839094e50b65c0335a590619a":{
      "scriptId":"u48"},
    "40aec98d502240388589c18e87b8414d":{
      "scriptId":"u49"},
    "4ae62cdeac344c55948c9c31ea3edfbe":{
      "scriptId":"u50"},
    "0f9a6c30b77444a8b25e298559690911":{
      "scriptId":"u51"},
    "55815409cf3f4b23a53d1895d8217a52":{
      "scriptId":"u52"},
    "b768fa29045e4ed8ba9f5beb247e6ab9":{
      "scriptId":"u53"},
    "3f014d5514d444a09dacb72a69ec56de":{
      "scriptId":"u54"},
    "ec76011eb69140a6bf8bc665e44aee88":{
      "scriptId":"u55"},
    "b310d43a36324804affe31b0bdf30e74":{
      "scriptId":"u56"},
    "8d0b133f64ea4acdbe9a77ab2b908940":{
      "scriptId":"u57"},
    "19743b7d862b412ea18d5ec813f38add":{
      "scriptId":"u58"},
    "3141680bbe4b4db79cbc1f23e069527f":{
      "scriptId":"u59"},
    "66b73b0c08bb42c892c7f6136679debe":{
      "scriptId":"u60"},
    "b1279c0748c742db809a9fc29741bb30":{
      "scriptId":"u61"},
    "1c44f801283543f08271b1a409faf417":{
      "scriptId":"u62"},
    "6f96bd3b2b984599a5ea31604a84371c":{
      "scriptId":"u63"},
    "caba516e2a36405a85265d0816089933":{
      "scriptId":"u64"},
    "71717e97b9514909ba5b4eb52e8b390f":{
      "scriptId":"u65"},
    "cd7ec54ebe2d48e695f116907304df16":{
      "scriptId":"u66"},
    "55f3b0aa47bd4d229cbd4f6531f6c138":{
      "scriptId":"u67"},
    "4305bcbcd67643ffa19edfaf3ade0efd":{
      "scriptId":"u68"},
    "0d2038ee2dae4a9b9e965653e00b995c":{
      "scriptId":"u69"},
    "8f70b695fda543018e19ff697b803973":{
      "scriptId":"u70"},
    "fb940abead8c4da3ba22555af3d4d16c":{
      "scriptId":"u71"},
    "ac0c10ab39fc4d0fae8a486eaafb3d57":{
      "scriptId":"u72"},
    "4815350b065b461d8e33d8c4d0b1d578":{
      "scriptId":"u73"},
    "f55d4ae164094fd6b0d2a22daf7f4629":{
      "scriptId":"u74"},
    "77db030925f04a89a344ca44cce0c429":{
      "scriptId":"u75"},
    "8f4fa569778646cb80ca12611c3e9cf0":{
      "scriptId":"u76"},
    "6f8ca1a240d4473785cbbc7603497324":{
      "scriptId":"u77"},
    "831a32f7aee04f23a1415ff7bb2237fd":{
      "scriptId":"u78"},
    "a0bf4cdcd06d4c79a2074271e69d18fb":{
      "scriptId":"u79"},
    "3a8b1de7413f4058ab17fc22784c636b":{
      "scriptId":"u80"},
    "b827c71735a84aa4b9bfc2fcbd8140e0":{
      "scriptId":"u81"},
    "e78456cf03e14087a3b1176c19487765":{
      "scriptId":"u82"},
    "0fffbbd41231443794e4276d67d4628c":{
      "scriptId":"u83"},
    "d0f3eeb98fab460db7c05a178689861a":{
      "scriptId":"u84"},
    "3c56872584e34df781bc2cb5d08b2d27":{
      "scriptId":"u85"},
    "78fc146a2430452ca6a9c005cbf056b4":{
      "scriptId":"u86"},
    "2ac576a1a30a4a83a4c1c828349762ee":{
      "scriptId":"u87"},
    "a7d446b6728a4a94a673e3e31af4c4d6":{
      "scriptId":"u88"},
    "28411ddde2b744d18d1a58370263358d":{
      "scriptId":"u89"},
    "a2a02a8ea76f4c20954efa01930dfb57":{
      "scriptId":"u90"},
    "f6be5cac9882473ba6f57483f8eaf6dd":{
      "scriptId":"u91"},
    "22e323fa02fc4c0a9d13b9818dce596b":{
      "scriptId":"u92"},
    "96357d97df2b4e93a51649bb4af40d79":{
      "scriptId":"u93"},
    "1be0411be37943f689d89a0786e7e142":{
      "scriptId":"u94"},
    "8768e60c11ee403badcce2e53054b400":{
      "scriptId":"u95"},
    "6664590ccafa4afdba000a5e00773ba6":{
      "scriptId":"u96"},
    "19324e738b224d2d8edd54af7350ce93":{
      "scriptId":"u97"},
    "32d38dece9284ffb8eb371b5d63e088a":{
      "scriptId":"u98"},
    "e308193e5c7f48f1835f8ceb9c1265ec":{
      "scriptId":"u99"},
    "5fb3287f79454e91b4ad1526b9bf0583":{
      "scriptId":"u100"},
    "107a6a01f7e64cefaf829416d03672f8":{
      "scriptId":"u101"},
    "a62edb428b964d6b99218e80020d7520":{
      "scriptId":"u102"},
    "0d72cdf39d344d7f91673d9fc5578292":{
      "scriptId":"u103"},
    "ff2f89fd6b8c4a2db780af960f3e091c":{
      "scriptId":"u104"},
    "e70c872829c04ac9bd3cf9e8c9489a3e":{
      "scriptId":"u105"},
    "37ab19e39e624796b6288e42cfe0694e":{
      "scriptId":"u106"},
    "b79127cf6c314b2e8135f11d27efaab1":{
      "scriptId":"u107"},
    "0cd3ae862ef74308b6760b0836a9debc":{
      "scriptId":"u108"},
    "7405d1f70905455fab2aba878aa23404":{
      "scriptId":"u109"},
    "3f986e53b01a4cf2a93218d69f6981ea":{
      "scriptId":"u110"},
    "ee9af97eed874189b5bdfeca4c817f78":{
      "scriptId":"u111"},
    "7617961206b54cf1a65b61093985f58c":{
      "scriptId":"u112"},
    "ef63aaeeabec4f778583a7cfc86252a4":{
      "scriptId":"u113"},
    "a9206a3507e94b4c98ca6d9126729f59":{
      "scriptId":"u114"},
    "7beed3e358ec4dfb9454e71d45a6f87d":{
      "scriptId":"u115"},
    "a356fe5b6bee4dc1a8f4a6c5c1b4753e":{
      "scriptId":"u116"},
    "bd902e0e2ce744d986da9f1f8aff99cb":{
      "scriptId":"u117"},
    "c8601d98bfa345958cb70167a9b6de30":{
      "scriptId":"u118"},
    "4340bed4e9834c989a643249a52c3645":{
      "scriptId":"u119"},
    "21992c63e5bf466ba3dd1f26b2a35d60":{
      "scriptId":"u120"},
    "36ba2970208a44cd98e33778871f2564":{
      "scriptId":"u121"}}});