$axure.loadCurrentPage({
  "url":"早餐券_1.html",
  "generationDate":new Date(1448450538396.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"tplb_img",
"jdt_bfb",
"qsjs_r",
"tpcc_wz",
"tpcc_zt",
"tpcc_kd",
"yz_msg"],
  "page":{
    "packageId":"73a7e21c22d04c1d89d768a3eafc727c",
    "type":"Axure:Page",
    "name":"早餐券",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"277d9d8d46954b948a2b22512ff2ef65",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":320,
              "height":568},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feda634a6efd410d9a64235648f6d648",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":320,
                  "height":568},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u0.png"}},
{
          "id":"3552909a12424e09b3e6ef4b709c7235",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":35},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0986ac48a37d4bad843c2d8af0298450",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":35},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u4.png"}},
{
          "id":"b4854b6f60a84cf280ef5f9e1dabc883",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":142,
              "y":46},
            "size":{
              "width":128,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ac7fc29f318410f874f45dbb8f09146",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":142,
                  "y":46},
                "size":{
                  "width":128,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c32f8f0de744f3a8b9abc4c7cb37b55",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":48},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cbb5e204f844381ab464e589e15336d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":48},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u8.png"}},
{
          "id":"de31f95bd1364d4b8c224a2010c1b01c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":20},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9694896bfbc54e4db0513139ea4966e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":20},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u2.png"}},
{
          "id":"0b2f0095b1594c518e97858ceb16996c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":100},
            "size":{
              "width":309,
              "height":360},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cef22eb1bd94a47b19d006b1f1e70c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":100},
                "size":{
                  "width":309,
                  "height":360},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐券/u10.png"}},
{
          "id":"98ae1e9c3e9148ae9ada8957a9e03f58",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":44,
              "y":169},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06ac7f38f7594bee8ce35d4ea74f17f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":44,
                  "y":169},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c1ad92da874447595067086ab5bffb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":196},
            "size":{
              "width":140,
              "height":133}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a13f4482bf0f4b40b66a283995c42769",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":196},
                "size":{
                  "width":140,
                  "height":133}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐券/u14.png"}},
{
          "id":"9fc7022287cc41f38c1fc2de3485fa25",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":149},
            "size":{
              "width":305,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/券列表/u60_line.png"}},
{
          "id":"b637c6562abf4ee0bfd1d811d95f8e92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":348},
            "size":{
              "width":305,
              "height":110},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"371f53c8902c4efcbf34a7760a4a1365",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":348},
                "size":{
                  "width":305,
                  "height":110},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐券/u17.png"}},
{
          "id":"94e374906cec4ac48b027caa345ac2e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":395},
            "size":{
              "width":229,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16c5f7528e6e49b9a7265ac3ea2a86b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":395},
                "size":{
                  "width":229,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62e5c4d5dd834f05926f8e75a73787f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":32,
              "y":364},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"187a6238d0dd4f64a141bbd34846c90f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":32,
                  "y":364},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13ee2bbc240b4cd0a4fc57a165d2950c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":395},
            "size":{
              "width":204,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b161048f314e44f3b2af483348f85831",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":395},
                "size":{
                  "width":204,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e341cd8086f426e8d4adc8e5dd78f9c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":338},
            "size":{
              "width":305,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/券列表/u60_line.png"}},
{
          "id":"7efddfd2823a4b559f5ca03403aedaba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":109},
            "size":{
              "width":198,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc3d19dc7f904ff79c5a35b77ad89b67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":109},
                "size":{
                  "width":198,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"635da012a62e4e64b042d0cfce134285",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":92,
              "y":130},
            "size":{
              "width":198,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abedf925203741c7a50a3d343952fe95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":92,
                  "y":130},
                "size":{
                  "width":198,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0e80452dedd4f4e80bb77853e067019",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0x87797979},
            "location":{
              "x":42,
              "y":105},
            "size":{
              "width":45,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f1fe35173444f48a17550eec234b97a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0x87797979},
                "location":{
                  "x":42,
                  "y":105},
                "size":{
                  "width":45,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐券/u30.png"}},
{
          "id":"05c04c883f06420da4fc0fc39c846263",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":300,
              "y":115},
            "size":{
              "width":32,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de672729cd554f7f8b3667976155f435",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":300,
                  "y":115},
                "size":{
                  "width":32,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"adf3c7399916429fa24096c72ca22c21",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":100},
            "size":{
              "width":305,
              "height":59}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 生成早餐券",
                      "target":{
                        "targetType":"page",
                        "url":"生成早餐券.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "277d9d8d46954b948a2b22512ff2ef65":{
      "scriptId":"u0"},
    "feda634a6efd410d9a64235648f6d648":{
      "scriptId":"u1"},
    "3552909a12424e09b3e6ef4b709c7235":{
      "scriptId":"u2"},
    "0986ac48a37d4bad843c2d8af0298450":{
      "scriptId":"u3"},
    "b4854b6f60a84cf280ef5f9e1dabc883":{
      "scriptId":"u4"},
    "6ac7fc29f318410f874f45dbb8f09146":{
      "scriptId":"u5"},
    "5c32f8f0de744f3a8b9abc4c7cb37b55":{
      "scriptId":"u6"},
    "0cbb5e204f844381ab464e589e15336d":{
      "scriptId":"u7"},
    "de31f95bd1364d4b8c224a2010c1b01c":{
      "scriptId":"u8"},
    "9694896bfbc54e4db0513139ea4966e3":{
      "scriptId":"u9"},
    "0b2f0095b1594c518e97858ceb16996c":{
      "scriptId":"u10"},
    "5cef22eb1bd94a47b19d006b1f1e70c5":{
      "scriptId":"u11"},
    "98ae1e9c3e9148ae9ada8957a9e03f58":{
      "scriptId":"u12"},
    "06ac7f38f7594bee8ce35d4ea74f17f9":{
      "scriptId":"u13"},
    "9c1ad92da874447595067086ab5bffb1":{
      "scriptId":"u14"},
    "a13f4482bf0f4b40b66a283995c42769":{
      "scriptId":"u15"},
    "9fc7022287cc41f38c1fc2de3485fa25":{
      "scriptId":"u16"},
    "b637c6562abf4ee0bfd1d811d95f8e92":{
      "scriptId":"u17"},
    "371f53c8902c4efcbf34a7760a4a1365":{
      "scriptId":"u18"},
    "94e374906cec4ac48b027caa345ac2e9":{
      "scriptId":"u19"},
    "16c5f7528e6e49b9a7265ac3ea2a86b9":{
      "scriptId":"u20"},
    "62e5c4d5dd834f05926f8e75a73787f8":{
      "scriptId":"u21"},
    "187a6238d0dd4f64a141bbd34846c90f":{
      "scriptId":"u22"},
    "13ee2bbc240b4cd0a4fc57a165d2950c":{
      "scriptId":"u23"},
    "b161048f314e44f3b2af483348f85831":{
      "scriptId":"u24"},
    "2e341cd8086f426e8d4adc8e5dd78f9c":{
      "scriptId":"u25"},
    "7efddfd2823a4b559f5ca03403aedaba":{
      "scriptId":"u26"},
    "dc3d19dc7f904ff79c5a35b77ad89b67":{
      "scriptId":"u27"},
    "635da012a62e4e64b042d0cfce134285":{
      "scriptId":"u28"},
    "abedf925203741c7a50a3d343952fe95":{
      "scriptId":"u29"},
    "b0e80452dedd4f4e80bb77853e067019":{
      "scriptId":"u30"},
    "8f1fe35173444f48a17550eec234b97a":{
      "scriptId":"u31"},
    "05c04c883f06420da4fc0fc39c846263":{
      "scriptId":"u32"},
    "de672729cd554f7f8b3667976155f435":{
      "scriptId":"u33"},
    "adf3c7399916429fa24096c72ca22c21":{
      "scriptId":"u34"}}});