$axure.loadCurrentPage({
  "url":"员工就餐-早餐点餐.html",
  "generationDate":new Date(1448611751285.32),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"tplb_img",
"jdt_bfb",
"qsjs_r",
"tpcc_wz",
"tpcc_zt",
"tpcc_kd",
"yz_msg"],
  "page":{
    "packageId":"486d114b1b224dd4871e7a95ea78f092",
    "type":"Axure:Page",
    "name":"员工就餐-早餐点餐",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"75d3301e2391437392ac7c4907be6253",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":320,
              "height":568},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41cc97578d714e83a69c67562d89b9b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":320,
                  "height":568},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u0.png"}},
{
          "id":"062f01e1b1c645b593329275978b92a1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":20},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f77fe20cabb344fa8d279215a921718a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":20},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u2.png"}},
{
          "id":"40e2f7596c4a43f0bcc6afbf58be77fc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":35},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcdae1530b3346609e50c77b392b2cc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":35},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u4.png"}},
{
          "id":"18a5900c0fa0431e879516e163fc0fc0",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":145,
              "y":46},
            "size":{
              "width":95,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8759ac5469434e3d8f8b6108df3d6dcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":145,
                  "y":46},
                "size":{
                  "width":95,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a89f427c409e489a826779e542f62227",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":48},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1884fe322a324c9ea53a54005cc7f6ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":48},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u8.png"}},
{
          "id":"e3cec2acce024c138b78ad4e56211266",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":151},
            "size":{
              "width":210,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC8C8C8}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/员工就餐-早餐点餐/u10_line.png"}},
{
          "id":"33842480f4244c75a39a1739be057431",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":80},
            "size":{
              "width":100,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c4d2403c53f444dbcb43a7b8ed99826",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":80},
                "size":{
                  "width":100,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u11.png"}},
{
          "id":"aac16583619c4f0080700fa534654184",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":120},
            "size":{
              "width":100,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"761f3482b52a4225bdbcb71ca8f7142f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":120},
                "size":{
                  "width":100,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u11.png"}},
{
          "id":"4b2c57afcbd04bc3b6eaf0445b5ff444",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":160},
            "size":{
              "width":100,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca855b1903844f4faaa349161e0a8154",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":160},
                "size":{
                  "width":100,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u11.png"}},
{
          "id":"aae9d9716a75406ca786509cd2f675df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":200},
            "size":{
              "width":100,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27b34ce24a374081a2cdc794464a6a4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":200},
                "size":{
                  "width":100,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u11.png"}},
{
          "id":"2ea74614b60545c7bcc14928002dc7de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":240},
            "size":{
              "width":100,
              "height":348},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4336f7878732434db53290e5145ec037",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":240},
                "size":{
                  "width":100,
                  "height":348},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u19.png"}},
{
          "id":"cb2ba5e94a4646f9a9c1e8d755f5c62a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":91},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71785a3b24174040a27c298393e79804",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":91},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u21.png"}},
{
          "id":"0aac4bef483b405895966216b42a622a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":92},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb721552a8294893894f29d497d68fc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":92},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba3f4771394a4365a62b1d5fedb395e4",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":16,
              "y":80},
            "size":{
              "width":10,
              "height":41},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/员工就餐-早餐点餐/u25_line.png"}},
{
          "id":"505bff8fc07b4bd1943f7ebe5366652e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":190,
              "y":125},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"617d629a4bd34e35b34494d675e356c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":125},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bc8b1b32018459e894c8b854c877fc7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":311,
              "y":121},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78500162864a4dc5bb4b134f007ef85b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":311,
                  "y":121},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u28.png"}},
{
          "id":"691eb66e48154f7391f5cacb2fe03d86",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":231},
            "size":{
              "width":210,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC8C8C8}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/员工就餐-早餐点餐/u10_line.png"}},
{
          "id":"3784960d5aed463fa933fd47ef2f58a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":171},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"713fb41227a240b6861a9db391db4087",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":171},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u21.png"}},
{
          "id":"45b9425011904bad97a99b9b41bc05c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":172},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"418fed2d17294ae8ae04abd528a12e27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":172},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bbb51170138248dc955b2f6ce2136378",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":190,
              "y":205},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d92e61d2ef1645d09a98fda0e184de5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":205},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b169b1251818446ca05ddd8e38bb7fbe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":311,
              "y":201},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6ff61329d5141ceafdca42eadca68df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":311,
                  "y":201},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u28.png"}},
{
          "id":"184247d45fe84b61816d6effc6bbc411",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":311},
            "size":{
              "width":210,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC8C8C8}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/员工就餐-早餐点餐/u10_line.png"}},
{
          "id":"2749336c37124a7e8dd742990c231948",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":251},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95fdafd4476a4e878328df88405d6d08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":251},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u21.png"}},
{
          "id":"9b93eb75dceb4a6a8064d660d0cf76e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":252},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc6b9d7b825f44b4899decf86a548530",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":252},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ef5754442944dda85aaf09d7133f4d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":190,
              "y":285},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb37af0bbb0e427999fb98a1b3f080ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":285},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c55bba3394a847679c65ef4b4e4efb22",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":311,
              "y":281},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"672f03b24e764313b6069fd99150b7ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":311,
                  "y":281},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u28.png"}},
{
          "id":"127c1d4004fd4a17b350868ef242603f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":538},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d7bf807017a472d9f20c6ab250dc4c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":538},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u48.png"}},
{
          "id":"76d720cb98ce405daddfda8059248365",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":31,
              "y":543},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e2cab0a88034d9ca90e53e7ae09f260",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":31,
                  "y":543},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u50.png"}},
{
          "id":"5731706fcf6f460b8514d8cd16e97b12",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":240,
              "y":538},
            "size":{
              "width":100,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4020e5623a2848269d6a228f26d31be9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":240,
                  "y":538},
                "size":{
                  "width":100,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u52.png"}},
{
          "id":"5678cc63b34442cba07d621d83eda144",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":54,
              "y":538},
            "size":{
              "width":20,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28a85608b7d14f0aa08a0a1fd5784f0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":54,
                  "y":538},
                "size":{
                  "width":20,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u54.png"}},
{
          "id":"f455e44a578f40b7a302e63616603535",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":121},
            "size":{
              "width":22,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF83BAFC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34b2824082bc420294e9abd986fc195a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":121},
                "size":{
                  "width":22,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF83BAFC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u56.png"}},
{
          "id":"b58d2c579031442eb11b23c507700b01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":296,
              "y":124},
            "size":{
              "width":8,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdaf2e158c6e44e9bd7439bbdd7b252f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":296,
                  "y":124},
                "size":{
                  "width":8,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91c0247e87774e14804f36e8b32f5b2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":81,
              "y":555},
            "size":{
              "width":35,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"564441f2ed6e4096a4779bbe3821e64c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":81,
                  "y":555},
                "size":{
                  "width":35,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5c5a191f63541e783aeecd5cf533a19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":225,
              "y":54},
            "size":{
              "width":20,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b379587920eb49b989f5306cc84ecd18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":225,
                  "y":54},
                "size":{
                  "width":20,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 食堂切换",
                      "objectsToFades":[{
                          "objectPath":["aa47b8ec23704fa3a797c5228b70a87f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u62.png"}},
{
          "id":"aa47b8ec23704fa3a797c5228b70a87f",
          "label":"食堂切换",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":20,
              "y":81},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"a4129c4deb4049a99d1b00eed3e7e486",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9f4e387c5c18437ca4d20f110ed1c4b1",
                  "label":"",
                  "parentDynamicPanel":"aa47b8ec23704fa3a797c5228b70a87f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":321,
                      "height":189},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"daa071f2f2f844d38c30b3396b9b0899",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aa47b8ec23704fa3a797c5228b70a87f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":321,
                          "height":189},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/员工就餐-早餐点餐/u65.png"}},
{
                  "id":"79d535df3be146999637db0c0a12d9a4",
                  "label":"",
                  "parentDynamicPanel":"aa47b8ec23704fa3a797c5228b70a87f",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":14,
                      "y":41},
                    "size":{
                      "width":285,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/员工就餐-早餐点餐/u67_line.png"}},
{
                  "id":"bf4b0cae734348618a26fc8a69c80afc",
                  "label":"",
                  "parentDynamicPanel":"aa47b8ec23704fa3a797c5228b70a87f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":35,
                      "y":18},
                    "size":{
                      "width":106,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"70092e14242346aca52b4fb90a509f9a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aa47b8ec23704fa3a797c5228b70a87f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":35,
                          "y":18},
                        "size":{
                          "width":106,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a736ef29162b475aae0fcfbf35c7cc5d",
                  "label":"",
                  "parentDynamicPanel":"aa47b8ec23704fa3a797c5228b70a87f",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":14,
                      "y":84},
                    "size":{
                      "width":285,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/员工就餐-早餐点餐/u67_line.png"}},
{
                  "id":"2660fa9a949d448890fd249e5c732750",
                  "label":"",
                  "parentDynamicPanel":"aa47b8ec23704fa3a797c5228b70a87f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":35,
                      "y":61},
                    "size":{
                      "width":106,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"61f2f96ad4ce40cd81c5e928ba720814",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aa47b8ec23704fa3a797c5228b70a87f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":35,
                          "y":61},
                        "size":{
                          "width":106,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"eab13178846645ef8db715065d3e4203",
                  "label":"",
                  "parentDynamicPanel":"aa47b8ec23704fa3a797c5228b70a87f",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":14,
                      "y":127},
                    "size":{
                      "width":285,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/员工就餐-早餐点餐/u67_line.png"}},
{
                  "id":"619bea0befcf46eab7ec5d74b946f00e",
                  "label":"",
                  "parentDynamicPanel":"aa47b8ec23704fa3a797c5228b70a87f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":35,
                      "y":104},
                    "size":{
                      "width":106,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6c598bf7388d466595e4a85d50bedf50",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aa47b8ec23704fa3a797c5228b70a87f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":35,
                          "y":104},
                        "size":{
                          "width":106,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c31ab29bcfc84eab987c5afc3b9b17da",
                  "label":"",
                  "parentDynamicPanel":"aa47b8ec23704fa3a797c5228b70a87f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":35,
                      "y":151},
                    "size":{
                      "width":106,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b931e3be7be24ad5a3dfcf5b471c640d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aa47b8ec23704fa3a797c5228b70a87f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":35,
                          "y":151},
                        "size":{
                          "width":106,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"579777df6ddc4f21930c918d1bbaf83d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":398,
              "y":46},
            "size":{
              "width":452,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17253ec5b553423e961fd60f1dfb32d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":398,
                  "y":46},
                "size":{
                  "width":452,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af95037c483f4a818f385a528c0df96c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":53},
            "size":{
              "width":153,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/员工就餐-早餐点餐/u80_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/员工就餐-早餐点餐/u80_line.png"}},
{
          "id":"319f76c0a195422ba6654226ff0e5df0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":398,
              "y":137},
            "size":{
              "width":452,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6f3bea60ce04a44921d780d75b81fff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":398,
                  "y":137},
                "size":{
                  "width":452,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "75d3301e2391437392ac7c4907be6253":{
      "scriptId":"u0"},
    "41cc97578d714e83a69c67562d89b9b1":{
      "scriptId":"u1"},
    "062f01e1b1c645b593329275978b92a1":{
      "scriptId":"u2"},
    "f77fe20cabb344fa8d279215a921718a":{
      "scriptId":"u3"},
    "40e2f7596c4a43f0bcc6afbf58be77fc":{
      "scriptId":"u4"},
    "bcdae1530b3346609e50c77b392b2cc1":{
      "scriptId":"u5"},
    "18a5900c0fa0431e879516e163fc0fc0":{
      "scriptId":"u6"},
    "8759ac5469434e3d8f8b6108df3d6dcc":{
      "scriptId":"u7"},
    "a89f427c409e489a826779e542f62227":{
      "scriptId":"u8"},
    "1884fe322a324c9ea53a54005cc7f6ee":{
      "scriptId":"u9"},
    "e3cec2acce024c138b78ad4e56211266":{
      "scriptId":"u10"},
    "33842480f4244c75a39a1739be057431":{
      "scriptId":"u11"},
    "9c4d2403c53f444dbcb43a7b8ed99826":{
      "scriptId":"u12"},
    "aac16583619c4f0080700fa534654184":{
      "scriptId":"u13"},
    "761f3482b52a4225bdbcb71ca8f7142f":{
      "scriptId":"u14"},
    "4b2c57afcbd04bc3b6eaf0445b5ff444":{
      "scriptId":"u15"},
    "ca855b1903844f4faaa349161e0a8154":{
      "scriptId":"u16"},
    "aae9d9716a75406ca786509cd2f675df":{
      "scriptId":"u17"},
    "27b34ce24a374081a2cdc794464a6a4b":{
      "scriptId":"u18"},
    "2ea74614b60545c7bcc14928002dc7de":{
      "scriptId":"u19"},
    "4336f7878732434db53290e5145ec037":{
      "scriptId":"u20"},
    "cb2ba5e94a4646f9a9c1e8d755f5c62a":{
      "scriptId":"u21"},
    "71785a3b24174040a27c298393e79804":{
      "scriptId":"u22"},
    "0aac4bef483b405895966216b42a622a":{
      "scriptId":"u23"},
    "bb721552a8294893894f29d497d68fc8":{
      "scriptId":"u24"},
    "ba3f4771394a4365a62b1d5fedb395e4":{
      "scriptId":"u25"},
    "505bff8fc07b4bd1943f7ebe5366652e":{
      "scriptId":"u26"},
    "617d629a4bd34e35b34494d675e356c9":{
      "scriptId":"u27"},
    "9bc8b1b32018459e894c8b854c877fc7":{
      "scriptId":"u28"},
    "78500162864a4dc5bb4b134f007ef85b":{
      "scriptId":"u29"},
    "691eb66e48154f7391f5cacb2fe03d86":{
      "scriptId":"u30"},
    "3784960d5aed463fa933fd47ef2f58a9":{
      "scriptId":"u31"},
    "713fb41227a240b6861a9db391db4087":{
      "scriptId":"u32"},
    "45b9425011904bad97a99b9b41bc05c9":{
      "scriptId":"u33"},
    "418fed2d17294ae8ae04abd528a12e27":{
      "scriptId":"u34"},
    "bbb51170138248dc955b2f6ce2136378":{
      "scriptId":"u35"},
    "d92e61d2ef1645d09a98fda0e184de5b":{
      "scriptId":"u36"},
    "b169b1251818446ca05ddd8e38bb7fbe":{
      "scriptId":"u37"},
    "a6ff61329d5141ceafdca42eadca68df":{
      "scriptId":"u38"},
    "184247d45fe84b61816d6effc6bbc411":{
      "scriptId":"u39"},
    "2749336c37124a7e8dd742990c231948":{
      "scriptId":"u40"},
    "95fdafd4476a4e878328df88405d6d08":{
      "scriptId":"u41"},
    "9b93eb75dceb4a6a8064d660d0cf76e6":{
      "scriptId":"u42"},
    "bc6b9d7b825f44b4899decf86a548530":{
      "scriptId":"u43"},
    "5ef5754442944dda85aaf09d7133f4d2":{
      "scriptId":"u44"},
    "cb37af0bbb0e427999fb98a1b3f080ad":{
      "scriptId":"u45"},
    "c55bba3394a847679c65ef4b4e4efb22":{
      "scriptId":"u46"},
    "672f03b24e764313b6069fd99150b7ea":{
      "scriptId":"u47"},
    "127c1d4004fd4a17b350868ef242603f":{
      "scriptId":"u48"},
    "0d7bf807017a472d9f20c6ab250dc4c1":{
      "scriptId":"u49"},
    "76d720cb98ce405daddfda8059248365":{
      "scriptId":"u50"},
    "4e2cab0a88034d9ca90e53e7ae09f260":{
      "scriptId":"u51"},
    "5731706fcf6f460b8514d8cd16e97b12":{
      "scriptId":"u52"},
    "4020e5623a2848269d6a228f26d31be9":{
      "scriptId":"u53"},
    "5678cc63b34442cba07d621d83eda144":{
      "scriptId":"u54"},
    "28a85608b7d14f0aa08a0a1fd5784f0f":{
      "scriptId":"u55"},
    "f455e44a578f40b7a302e63616603535":{
      "scriptId":"u56"},
    "34b2824082bc420294e9abd986fc195a":{
      "scriptId":"u57"},
    "b58d2c579031442eb11b23c507700b01":{
      "scriptId":"u58"},
    "fdaf2e158c6e44e9bd7439bbdd7b252f":{
      "scriptId":"u59"},
    "91c0247e87774e14804f36e8b32f5b2a":{
      "scriptId":"u60"},
    "564441f2ed6e4096a4779bbe3821e64c":{
      "scriptId":"u61"},
    "f5c5a191f63541e783aeecd5cf533a19":{
      "scriptId":"u62"},
    "b379587920eb49b989f5306cc84ecd18":{
      "scriptId":"u63"},
    "aa47b8ec23704fa3a797c5228b70a87f":{
      "scriptId":"u64"},
    "9f4e387c5c18437ca4d20f110ed1c4b1":{
      "scriptId":"u65"},
    "daa071f2f2f844d38c30b3396b9b0899":{
      "scriptId":"u66"},
    "79d535df3be146999637db0c0a12d9a4":{
      "scriptId":"u67"},
    "bf4b0cae734348618a26fc8a69c80afc":{
      "scriptId":"u68"},
    "70092e14242346aca52b4fb90a509f9a":{
      "scriptId":"u69"},
    "a736ef29162b475aae0fcfbf35c7cc5d":{
      "scriptId":"u70"},
    "2660fa9a949d448890fd249e5c732750":{
      "scriptId":"u71"},
    "61f2f96ad4ce40cd81c5e928ba720814":{
      "scriptId":"u72"},
    "eab13178846645ef8db715065d3e4203":{
      "scriptId":"u73"},
    "619bea0befcf46eab7ec5d74b946f00e":{
      "scriptId":"u74"},
    "6c598bf7388d466595e4a85d50bedf50":{
      "scriptId":"u75"},
    "c31ab29bcfc84eab987c5afc3b9b17da":{
      "scriptId":"u76"},
    "b931e3be7be24ad5a3dfcf5b471c640d":{
      "scriptId":"u77"},
    "579777df6ddc4f21930c918d1bbaf83d":{
      "scriptId":"u78"},
    "17253ec5b553423e961fd60f1dfb32d7":{
      "scriptId":"u79"},
    "af95037c483f4a818f385a528c0df96c":{
      "scriptId":"u80"},
    "319f76c0a195422ba6654226ff0e5df0":{
      "scriptId":"u81"},
    "b6f3bea60ce04a44921d780d75b81fff":{
      "scriptId":"u82"}}});