$axure.loadCurrentPage({
  "url":"午餐券.html",
  "generationDate":new Date(1448611752933.42),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"tplb_img",
"jdt_bfb",
"qsjs_r",
"tpcc_wz",
"tpcc_zt",
"tpcc_kd",
"yz_msg"],
  "page":{
    "packageId":"ba60df4f25c246dca75c408548222cb9",
    "type":"Axure:Page",
    "name":"午餐券",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7f64f382a1c94ba3a1b57ef75f74f2a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":320,
              "height":620},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"443e428aa8e649aabc5a2fb2859402a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":320,
                  "height":620},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-午餐/u2.png"}},
{
          "id":"3aa6b117c1de4e67af3019a9156ebe56",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":35},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99f1d5faf1c44a86af3b45c056983c91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":35},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u4.png"}},
{
          "id":"dc7a632512bc485789494c00aff904c9",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":142,
              "y":46},
            "size":{
              "width":128,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07011b3cb05843329cd900e435aec45b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":142,
                  "y":46},
                "size":{
                  "width":128,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84332626932e4c5298c79bc8b6d986c7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":48},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9824c0444254684a09f64815875fec8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":48},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u8.png"}},
{
          "id":"ccd4201be0894b1ebba6c516e4404a27",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":20},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b788058f789f484f93407e812a57dbed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":20},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u2.png"}},
{
          "id":"a546f57ea1174b3ea66bbdb20f2b1399",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":100},
            "size":{
              "width":309,
              "height":370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"666e8b88a18a4f3a9de610d2870b7090",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":100},
                "size":{
                  "width":309,
                  "height":370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/午餐券/u10.png"}},
{
          "id":"2244501422554e2bbb2a84507d0f6c4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":44,
              "y":169},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4965391ea5f74568b382b9b7c3b6030f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":44,
                  "y":169},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a364ff184fb41bb8d31587ca2ab1f9d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":149},
            "size":{
              "width":305,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/券列表/u54_line.png"}},
{
          "id":"fc83c7282ea449ca93687fa1e8e461a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0x87797979},
            "location":{
              "x":42,
              "y":105},
            "size":{
              "width":45,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a131ca6cd23403fae6a2e7e504c4377",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0x87797979},
                "location":{
                  "x":42,
                  "y":105},
                "size":{
                  "width":45,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐券/u30.png"}},
{
          "id":"e73eea6fd3a14c5f93752f023f5c1cb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":107},
            "size":{
              "width":198,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3dc5c0d3a1d443c91f136348b19d7da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":107},
                "size":{
                  "width":198,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84c7a278449c4b5eb7b277011195c8fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":102,
              "y":134},
            "size":{
              "width":198,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48bf24c3a136462089324368828e308c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":102,
                  "y":134},
                "size":{
                  "width":198,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08d5ba895e754b9ba38b0d6dd47b12ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":248},
            "size":{
              "width":362,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46f130f99fe14b7699b9a5aaeb982ec3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":248},
                "size":{
                  "width":362,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58281230eaea4482abdd77fee1d27b6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":210},
            "size":{
              "width":225,
              "height":225}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcae822f3ccc4cdeb0802d688321868c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":210},
                "size":{
                  "width":225,
                  "height":225}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐券/u14.png"}},
{
          "id":"26d17d99599a44d7affeb9119f8a84c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":300,
              "y":115},
            "size":{
              "width":32,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24d6b53b23ba4d58be578fd2662c41bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":300,
                  "y":115},
                "size":{
                  "width":32,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7f64f382a1c94ba3a1b57ef75f74f2a8":{
      "scriptId":"u0"},
    "443e428aa8e649aabc5a2fb2859402a2":{
      "scriptId":"u1"},
    "3aa6b117c1de4e67af3019a9156ebe56":{
      "scriptId":"u2"},
    "99f1d5faf1c44a86af3b45c056983c91":{
      "scriptId":"u3"},
    "dc7a632512bc485789494c00aff904c9":{
      "scriptId":"u4"},
    "07011b3cb05843329cd900e435aec45b":{
      "scriptId":"u5"},
    "84332626932e4c5298c79bc8b6d986c7":{
      "scriptId":"u6"},
    "e9824c0444254684a09f64815875fec8":{
      "scriptId":"u7"},
    "ccd4201be0894b1ebba6c516e4404a27":{
      "scriptId":"u8"},
    "b788058f789f484f93407e812a57dbed":{
      "scriptId":"u9"},
    "a546f57ea1174b3ea66bbdb20f2b1399":{
      "scriptId":"u10"},
    "666e8b88a18a4f3a9de610d2870b7090":{
      "scriptId":"u11"},
    "2244501422554e2bbb2a84507d0f6c4b":{
      "scriptId":"u12"},
    "4965391ea5f74568b382b9b7c3b6030f":{
      "scriptId":"u13"},
    "1a364ff184fb41bb8d31587ca2ab1f9d":{
      "scriptId":"u14"},
    "fc83c7282ea449ca93687fa1e8e461a3":{
      "scriptId":"u15"},
    "4a131ca6cd23403fae6a2e7e504c4377":{
      "scriptId":"u16"},
    "e73eea6fd3a14c5f93752f023f5c1cb6":{
      "scriptId":"u17"},
    "d3dc5c0d3a1d443c91f136348b19d7da":{
      "scriptId":"u18"},
    "84c7a278449c4b5eb7b277011195c8fe":{
      "scriptId":"u19"},
    "48bf24c3a136462089324368828e308c":{
      "scriptId":"u20"},
    "08d5ba895e754b9ba38b0d6dd47b12ab":{
      "scriptId":"u21"},
    "46f130f99fe14b7699b9a5aaeb982ec3":{
      "scriptId":"u22"},
    "58281230eaea4482abdd77fee1d27b6a":{
      "scriptId":"u23"},
    "bcae822f3ccc4cdeb0802d688321868c":{
      "scriptId":"u24"},
    "26d17d99599a44d7affeb9119f8a84c4":{
      "scriptId":"u25"},
    "24d6b53b23ba4d58be578fd2662c41bf":{
      "scriptId":"u26"}}});