$axure.loadCurrentPage({
  "url":"午餐券.html",
  "generationDate":new Date(1448450538502.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"tplb_img",
"jdt_bfb",
"qsjs_r",
"tpcc_wz",
"tpcc_zt",
"tpcc_kd",
"yz_msg"],
  "page":{
    "packageId":"ba60df4f25c246dca75c408548222cb9",
    "type":"Axure:Page",
    "name":"午餐券",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7f64f382a1c94ba3a1b57ef75f74f2a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":320,
              "height":620},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"443e428aa8e649aabc5a2fb2859402a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":320,
                  "height":620},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/午餐券/u0.png"}},
{
          "id":"3aa6b117c1de4e67af3019a9156ebe56",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":35},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99f1d5faf1c44a86af3b45c056983c91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":35},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u4.png"}},
{
          "id":"dc7a632512bc485789494c00aff904c9",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":142,
              "y":46},
            "size":{
              "width":128,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07011b3cb05843329cd900e435aec45b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":142,
                  "y":46},
                "size":{
                  "width":128,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84332626932e4c5298c79bc8b6d986c7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":48},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9824c0444254684a09f64815875fec8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":48},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u8.png"}},
{
          "id":"ccd4201be0894b1ebba6c516e4404a27",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":20},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b788058f789f484f93407e812a57dbed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":20},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u2.png"}},
{
          "id":"a546f57ea1174b3ea66bbdb20f2b1399",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":100},
            "size":{
              "width":309,
              "height":510},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"666e8b88a18a4f3a9de610d2870b7090",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":100},
                "size":{
                  "width":309,
                  "height":510},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/午餐券/u10.png"}},
{
          "id":"2244501422554e2bbb2a84507d0f6c4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":44,
              "y":169},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4965391ea5f74568b382b9b7c3b6030f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":44,
                  "y":169},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"853a99c33ada4e0e9c7742eb4f8012de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":196},
            "size":{
              "width":140,
              "height":133}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b211820a5194c3f92226d82baa7fe48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":196},
                "size":{
                  "width":140,
                  "height":133}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐券/u14.png"}},
{
          "id":"1a364ff184fb41bb8d31587ca2ab1f9d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":149},
            "size":{
              "width":305,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/券列表/u60_line.png"}},
{
          "id":"af2b0daca6ce4ba58e4b25ac17db7cf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":532},
            "size":{
              "width":305,
              "height":72},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3aee7a3ef2ff437cacb8fb2598697afe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":532},
                "size":{
                  "width":305,
                  "height":72},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/午餐券/u17.png"}},
{
          "id":"23074bf33c554ca5b167103552142cb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":579},
            "size":{
              "width":229,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b44ebaa91b1459e9ae07e66bf25d417",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":579},
                "size":{
                  "width":229,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17eec0dd81374be09d6ef265bfdfc742",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":32,
              "y":548},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f134e96b5f94ce19f0314616b9e5f7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":32,
                  "y":548},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57064a18a6544299929573f4e335731a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":579},
            "size":{
              "width":204,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3c7260a418746d7b9027c5ed67d0fba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":579},
                "size":{
                  "width":204,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc83c7282ea449ca93687fa1e8e461a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0x87797979},
            "location":{
              "x":42,
              "y":105},
            "size":{
              "width":45,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a131ca6cd23403fae6a2e7e504c4377",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0x87797979},
                "location":{
                  "x":42,
                  "y":105},
                "size":{
                  "width":45,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐券/u30.png"}},
{
          "id":"e73eea6fd3a14c5f93752f023f5c1cb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":107},
            "size":{
              "width":198,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3dc5c0d3a1d443c91f136348b19d7da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":107},
                "size":{
                  "width":198,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84c7a278449c4b5eb7b277011195c8fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":102,
              "y":134},
            "size":{
              "width":198,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48bf24c3a136462089324368828e308c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":102,
                  "y":134},
                "size":{
                  "width":198,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac62bcffdfe04922b3765c61bde37f02",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":339},
            "size":{
              "width":305,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/券列表/u60_line.png"}},
{
          "id":"acb442a0f27147d8a003c2f6b5cc9f0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":107,
              "y":383},
            "size":{
              "width":140,
              "height":133}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96861d4e5fb44b8c8640c751f555f8ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":107,
                  "y":383},
                "size":{
                  "width":140,
                  "height":133}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐券/u14.png"}},
{
          "id":"de62102fa7164314ac9fde756ff908f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":44,
              "y":359},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc7191417a454f57b27d98a765e02a23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":44,
                  "y":359},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44667d975de3447ea94562af210d3ac9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":532},
            "size":{
              "width":305,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/券列表/u60_line.png"}},
{
          "id":"afc032dbc79145e68ef8128bbd9f3a24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":410,
              "y":20},
            "size":{
              "width":320,
              "height":620},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9647a35c247c4670901e4e1b5eb2fdee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":410,
                  "y":20},
                "size":{
                  "width":320,
                  "height":620},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/午餐券/u0.png"}},
{
          "id":"b7f8531b99754df18245d7f3c5884964",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":35},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dbcdb255d554b07bb7a6fcc138355d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":35},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u4.png"}},
{
          "id":"5daa4ce840fc4fea91c8cfe2b73415c6",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":532,
              "y":46},
            "size":{
              "width":128,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dffa363beb24b40981e4e2c6d80d4d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":532,
                  "y":46},
                "size":{
                  "width":128,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8622b8b812044b758aade9859a074eea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":421,
              "y":48},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a32e2742bdba430b82d96b6f96791950",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":421,
                  "y":48},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u8.png"}},
{
          "id":"468deb3fc6384e2d8e0c9f1c2345b6d0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":417,
              "y":20},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"447bc689654a4a2f98382cb4278f2f50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":417,
                  "y":20},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u2.png"}},
{
          "id":"a23be22d6a9c4e7d8b90cb769da524eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":415,
              "y":100},
            "size":{
              "width":309,
              "height":510},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3473cfb9f6c49bea65657f2f29de50e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":415,
                  "y":100},
                "size":{
                  "width":309,
                  "height":510},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/午餐券/u10.png"}},
{
          "id":"b904f15fece449c6ab6a367849703283",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":434,
              "y":169},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef44a7080b3442609a53821e023b5db1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":434,
                  "y":169},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05aa81ec13924e67bbd43331bd40c514",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":496,
              "y":196},
            "size":{
              "width":140,
              "height":133}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84e33538d2b7408d9f642a573dc3c730",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":496,
                  "y":196},
                "size":{
                  "width":140,
                  "height":133}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐券/u14.png"}},
{
          "id":"42479fbe5a21438bb4f07289146e2120",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":417,
              "y":149},
            "size":{
              "width":305,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/券列表/u60_line.png"}},
{
          "id":"6d27a7b2272e451190f293a413696e1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":417,
              "y":532},
            "size":{
              "width":305,
              "height":72},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fba56963c334df3bbb0daab25ba63f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":417,
                  "y":532},
                "size":{
                  "width":305,
                  "height":72},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/午餐券/u17.png"}},
{
          "id":"339a8e750ebb40989b07f4e9ecda082c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":422,
              "y":579},
            "size":{
              "width":229,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c5c1e734f2b4538b03b75b0a7d828a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":422,
                  "y":579},
                "size":{
                  "width":229,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45fc11abed2c4bb8a1ee2ceb8410de95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":422,
              "y":548},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24fcc3f4b3704158b9f8103f6fb27b17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":422,
                  "y":548},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1abc7ffeece43429499ed929d87b56a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":476,
              "y":579},
            "size":{
              "width":204,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c33595ea61c424ca0528cd898f099ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":476,
                  "y":579},
                "size":{
                  "width":204,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d99a4f717e7437c855358de2865fbf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0x87797979},
            "location":{
              "x":432,
              "y":105},
            "size":{
              "width":45,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"677b34d9269b4a28aa3e9a5b379b9487",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0x87797979},
                "location":{
                  "x":432,
                  "y":105},
                "size":{
                  "width":45,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐券/u30.png"}},
{
          "id":"41965484d6004d259320d7bab2f19e05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":107},
            "size":{
              "width":198,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d2b44b5b0d8401cad73fe95862ed2b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":107},
                "size":{
                  "width":198,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2d16ddf6bf54708a762ecddc0ed01d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":492,
              "y":134},
            "size":{
              "width":198,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a7f96eb0dfb4eadaacb51485874c341",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":492,
                  "y":134},
                "size":{
                  "width":198,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"606e49b8bc1d461781c8a941123792b2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":418,
              "y":339},
            "size":{
              "width":305,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/券列表/u60_line.png"}},
{
          "id":"f182d73845664429baa991e304bba29e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":497,
              "y":383},
            "size":{
              "width":140,
              "height":133}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0362fe495afe462f93e91d25de43e010",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":497,
                  "y":383},
                "size":{
                  "width":140,
                  "height":133}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐券/u14.png"}},
{
          "id":"f207be6762eb474a9ec3cffd04715773",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":434,
              "y":359},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10cae18e70b34211ba27f8c1868cf506",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":434,
                  "y":359},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e56a2d237b44f4398b09f4304f27c03",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":417,
              "y":532},
            "size":{
              "width":305,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/券列表/u60_line.png"}},
{
          "id":"690e0720903444ebbadd108d9c65f8a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0x87797979},
            "location":{
              "x":534.5,
              "y":415},
            "size":{
              "width":70,
              "height":69},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c716ab75e9434702ab8e5ed602938b41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0x87797979},
                "location":{
                  "x":534.5,
                  "y":415},
                "size":{
                  "width":70,
                  "height":69},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生成早餐券/u90.png"}},
{
          "id":"08d5ba895e754b9ba38b0d6dd47b12ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":758,
              "y":374},
            "size":{
              "width":362,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46f130f99fe14b7699b9a5aaeb982ec3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":758,
                  "y":374},
                "size":{
                  "width":362,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7f64f382a1c94ba3a1b57ef75f74f2a8":{
      "scriptId":"u0"},
    "443e428aa8e649aabc5a2fb2859402a2":{
      "scriptId":"u1"},
    "3aa6b117c1de4e67af3019a9156ebe56":{
      "scriptId":"u2"},
    "99f1d5faf1c44a86af3b45c056983c91":{
      "scriptId":"u3"},
    "dc7a632512bc485789494c00aff904c9":{
      "scriptId":"u4"},
    "07011b3cb05843329cd900e435aec45b":{
      "scriptId":"u5"},
    "84332626932e4c5298c79bc8b6d986c7":{
      "scriptId":"u6"},
    "e9824c0444254684a09f64815875fec8":{
      "scriptId":"u7"},
    "ccd4201be0894b1ebba6c516e4404a27":{
      "scriptId":"u8"},
    "b788058f789f484f93407e812a57dbed":{
      "scriptId":"u9"},
    "a546f57ea1174b3ea66bbdb20f2b1399":{
      "scriptId":"u10"},
    "666e8b88a18a4f3a9de610d2870b7090":{
      "scriptId":"u11"},
    "2244501422554e2bbb2a84507d0f6c4b":{
      "scriptId":"u12"},
    "4965391ea5f74568b382b9b7c3b6030f":{
      "scriptId":"u13"},
    "853a99c33ada4e0e9c7742eb4f8012de":{
      "scriptId":"u14"},
    "5b211820a5194c3f92226d82baa7fe48":{
      "scriptId":"u15"},
    "1a364ff184fb41bb8d31587ca2ab1f9d":{
      "scriptId":"u16"},
    "af2b0daca6ce4ba58e4b25ac17db7cf2":{
      "scriptId":"u17"},
    "3aee7a3ef2ff437cacb8fb2598697afe":{
      "scriptId":"u18"},
    "23074bf33c554ca5b167103552142cb4":{
      "scriptId":"u19"},
    "1b44ebaa91b1459e9ae07e66bf25d417":{
      "scriptId":"u20"},
    "17eec0dd81374be09d6ef265bfdfc742":{
      "scriptId":"u21"},
    "2f134e96b5f94ce19f0314616b9e5f7f":{
      "scriptId":"u22"},
    "57064a18a6544299929573f4e335731a":{
      "scriptId":"u23"},
    "d3c7260a418746d7b9027c5ed67d0fba":{
      "scriptId":"u24"},
    "fc83c7282ea449ca93687fa1e8e461a3":{
      "scriptId":"u25"},
    "4a131ca6cd23403fae6a2e7e504c4377":{
      "scriptId":"u26"},
    "e73eea6fd3a14c5f93752f023f5c1cb6":{
      "scriptId":"u27"},
    "d3dc5c0d3a1d443c91f136348b19d7da":{
      "scriptId":"u28"},
    "84c7a278449c4b5eb7b277011195c8fe":{
      "scriptId":"u29"},
    "48bf24c3a136462089324368828e308c":{
      "scriptId":"u30"},
    "ac62bcffdfe04922b3765c61bde37f02":{
      "scriptId":"u31"},
    "acb442a0f27147d8a003c2f6b5cc9f0d":{
      "scriptId":"u32"},
    "96861d4e5fb44b8c8640c751f555f8ad":{
      "scriptId":"u33"},
    "de62102fa7164314ac9fde756ff908f1":{
      "scriptId":"u34"},
    "dc7191417a454f57b27d98a765e02a23":{
      "scriptId":"u35"},
    "44667d975de3447ea94562af210d3ac9":{
      "scriptId":"u36"},
    "afc032dbc79145e68ef8128bbd9f3a24":{
      "scriptId":"u37"},
    "9647a35c247c4670901e4e1b5eb2fdee":{
      "scriptId":"u38"},
    "b7f8531b99754df18245d7f3c5884964":{
      "scriptId":"u39"},
    "8dbcdb255d554b07bb7a6fcc138355d2":{
      "scriptId":"u40"},
    "5daa4ce840fc4fea91c8cfe2b73415c6":{
      "scriptId":"u41"},
    "5dffa363beb24b40981e4e2c6d80d4d6":{
      "scriptId":"u42"},
    "8622b8b812044b758aade9859a074eea":{
      "scriptId":"u43"},
    "a32e2742bdba430b82d96b6f96791950":{
      "scriptId":"u44"},
    "468deb3fc6384e2d8e0c9f1c2345b6d0":{
      "scriptId":"u45"},
    "447bc689654a4a2f98382cb4278f2f50":{
      "scriptId":"u46"},
    "a23be22d6a9c4e7d8b90cb769da524eb":{
      "scriptId":"u47"},
    "b3473cfb9f6c49bea65657f2f29de50e":{
      "scriptId":"u48"},
    "b904f15fece449c6ab6a367849703283":{
      "scriptId":"u49"},
    "ef44a7080b3442609a53821e023b5db1":{
      "scriptId":"u50"},
    "05aa81ec13924e67bbd43331bd40c514":{
      "scriptId":"u51"},
    "84e33538d2b7408d9f642a573dc3c730":{
      "scriptId":"u52"},
    "42479fbe5a21438bb4f07289146e2120":{
      "scriptId":"u53"},
    "6d27a7b2272e451190f293a413696e1b":{
      "scriptId":"u54"},
    "3fba56963c334df3bbb0daab25ba63f2":{
      "scriptId":"u55"},
    "339a8e750ebb40989b07f4e9ecda082c":{
      "scriptId":"u56"},
    "7c5c1e734f2b4538b03b75b0a7d828a4":{
      "scriptId":"u57"},
    "45fc11abed2c4bb8a1ee2ceb8410de95":{
      "scriptId":"u58"},
    "24fcc3f4b3704158b9f8103f6fb27b17":{
      "scriptId":"u59"},
    "f1abc7ffeece43429499ed929d87b56a":{
      "scriptId":"u60"},
    "9c33595ea61c424ca0528cd898f099ac":{
      "scriptId":"u61"},
    "7d99a4f717e7437c855358de2865fbf4":{
      "scriptId":"u62"},
    "677b34d9269b4a28aa3e9a5b379b9487":{
      "scriptId":"u63"},
    "41965484d6004d259320d7bab2f19e05":{
      "scriptId":"u64"},
    "2d2b44b5b0d8401cad73fe95862ed2b6":{
      "scriptId":"u65"},
    "d2d16ddf6bf54708a762ecddc0ed01d1":{
      "scriptId":"u66"},
    "3a7f96eb0dfb4eadaacb51485874c341":{
      "scriptId":"u67"},
    "606e49b8bc1d461781c8a941123792b2":{
      "scriptId":"u68"},
    "f182d73845664429baa991e304bba29e":{
      "scriptId":"u69"},
    "0362fe495afe462f93e91d25de43e010":{
      "scriptId":"u70"},
    "f207be6762eb474a9ec3cffd04715773":{
      "scriptId":"u71"},
    "10cae18e70b34211ba27f8c1868cf506":{
      "scriptId":"u72"},
    "9e56a2d237b44f4398b09f4304f27c03":{
      "scriptId":"u73"},
    "690e0720903444ebbadd108d9c65f8a3":{
      "scriptId":"u74"},
    "c716ab75e9434702ab8e5ed602938b41":{
      "scriptId":"u75"},
    "08d5ba895e754b9ba38b0d6dd47b12ab":{
      "scriptId":"u76"},
    "46f130f99fe14b7699b9a5aaeb982ec3":{
      "scriptId":"u77"}}});