$axure.loadCurrentPage({
  "url":"早餐购买（与集团员工一致）.html",
  "generationDate":new Date(1448611752382.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"tplb_img",
"jdt_bfb",
"qsjs_r",
"tpcc_wz",
"tpcc_zt",
"tpcc_kd",
"yz_msg"],
  "page":{
    "packageId":"9effce16212d46c682fdcc35b1194277",
    "type":"Axure:Page",
    "name":"早餐购买（与集团员工一致）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e91cab0715b746f4b98009314be88e1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":320,
              "height":568},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d40f5af15de4dfa8c6b7948ac451c66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":320,
                  "height":568},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u0.png"}},
{
          "id":"181aab52f5ff4c30a715aab377488578",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":20},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce78f155839c4454834bc7d7bd51a0ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":20},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u2.png"}},
{
          "id":"7a16cfebabcb4644b2a839f84c254ac6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":35},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f06f7d80d63041cfbb305c9b8b000223",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":35},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u4.png"}},
{
          "id":"dd594300095c4b3f890bd3acf35fbc31",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":145,
              "y":46},
            "size":{
              "width":95,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a6082447a31492e9442503e830322c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":145,
                  "y":46},
                "size":{
                  "width":95,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e51927e83a5e46539a8ee963ac6793e7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":48},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7ecddf0a831424f82558cf60efd3db6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":48},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u8.png"}},
{
          "id":"3ecf4fed327748b8acba8c1bac9a1607",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":151},
            "size":{
              "width":210,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC8C8C8}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/员工就餐-早餐点餐/u10_line.png"}},
{
          "id":"79380325a4d34f62b273b238abd3ebb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":80},
            "size":{
              "width":100,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bea7137e54b74276b8359b9f1668d90a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":80},
                "size":{
                  "width":100,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u11.png"}},
{
          "id":"12cfda1d3d364911bc9a5aa20461db03",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":120},
            "size":{
              "width":100,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8dcbbbe600b455abd1aef17587a968c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":120},
                "size":{
                  "width":100,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u11.png"}},
{
          "id":"b9d601fb6c744fb58b8305fcd59988ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":160},
            "size":{
              "width":100,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd7f72d1de254ff49b616a765f3ff3dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":160},
                "size":{
                  "width":100,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u11.png"}},
{
          "id":"6cda14d295764ae690472720d9b756e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":200},
            "size":{
              "width":100,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5aff325b8214cf9b261f20094c63cb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":200},
                "size":{
                  "width":100,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u11.png"}},
{
          "id":"5ca6a82321464f21b5df928bd1a5e7a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":240},
            "size":{
              "width":100,
              "height":348},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2db3af5c4620452b8fbd36fa18602d25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":240},
                "size":{
                  "width":100,
                  "height":348},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u19.png"}},
{
          "id":"c259a5d6eafe43f58776193662b7ee3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":91},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c531904ad6b4446fbcbf7b0c57dbd98f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":91},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u21.png"}},
{
          "id":"479ed034cd4249e0b220b3849d6dd824",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":92},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6f1d35f2417453188d35330d7eed369",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":92},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b41302270154470281fee7536a79792c",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":16,
              "y":80},
            "size":{
              "width":10,
              "height":41},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/员工就餐-早餐点餐/u25_line.png"}},
{
          "id":"6e30796553a847e29cca9747ff3fcecf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":190,
              "y":125},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a2b632980204041b6d4158a1cdabfcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":125},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ab2509a404140c48f095a24f8997bd9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":311,
              "y":121},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3402b39261f40d18875f55348598139",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":311,
                  "y":121},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u28.png"}},
{
          "id":"ca0e4ff1cc734c86a0a25b09bc0eb240",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":231},
            "size":{
              "width":210,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC8C8C8}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/员工就餐-早餐点餐/u10_line.png"}},
{
          "id":"3b452cf3b9c54942845b75152dc0d311",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":171},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caae7f23dd81420397109eaaefc3b65a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":171},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u21.png"}},
{
          "id":"1dc5767e0ad34110b4a763d03bda0346",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":172},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4064ccb2afa34d418deb2054fbea3a0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":172},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c1681765c7a4e3d95d02a7785d6e0be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":190,
              "y":205},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08e4968cbaa646c9b5ceb4a04a462905",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":205},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a04f5fe480ba4286a77d0168fa439317",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":311,
              "y":201},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8820332a5f941c38edb6e4f387dcddc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":311,
                  "y":201},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u28.png"}},
{
          "id":"700e3af920f4410181d33944a48473be",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":311},
            "size":{
              "width":210,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC8C8C8}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/员工就餐-早餐点餐/u10_line.png"}},
{
          "id":"ee9db8b465a045fa8383e9317453b09d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":251},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef098ffce0ba4e9ebbd82c7913cddcbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":251},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u21.png"}},
{
          "id":"eb671825efd049f18b316c9b71173f18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":252},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"421906059d204bdcaf3700d08a9a280a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":252},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e9d578d2852466bab3bd902062347e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":190,
              "y":285},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd75bbe7fe0a47569a986697bbb31ee8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":285},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"acde209eb2a04073b1b3aca4a83a7aed",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":311,
              "y":281},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90ce4b170284412ea6731ab3e46476b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":311,
                  "y":281},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u28.png"}},
{
          "id":"fee908a7cd65459eac41542e62bb045b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":538},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8a5437478e5413595b895f42d9506fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":538},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u48.png"}},
{
          "id":"ba0f9c56dcb7474f8353806c94cd3a53",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":31,
              "y":543},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e005a12f282444a9585dfa3964e9fe3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":31,
                  "y":543},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u50.png"}},
{
          "id":"e091ccdefc73497fb907e68050e6601b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":240,
              "y":538},
            "size":{
              "width":100,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06b324a724cd43fca492fcae95353edf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":240,
                  "y":538},
                "size":{
                  "width":100,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u52.png"}},
{
          "id":"c22de3278aa24e2089ded25f707e3578",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":54,
              "y":538},
            "size":{
              "width":20,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78c4d735aad94368bd9d9cab3ce75083",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":54,
                  "y":538},
                "size":{
                  "width":20,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u54.png"}},
{
          "id":"8c500b13933e40a48851bf9ebe516ffc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":121},
            "size":{
              "width":22,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF83BAFC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4f3b83cb59744cda425934d1179cc6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":121},
                "size":{
                  "width":22,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF83BAFC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u56.png"}},
{
          "id":"4e54b2a422ee43449ce1dc46c5fba818",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":296,
              "y":124},
            "size":{
              "width":8,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e47add00e9ff4978bd87b30aa1a4c2d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":296,
                  "y":124},
                "size":{
                  "width":8,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d650399b6d44dc4bc734db86c2c7482",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":81,
              "y":555},
            "size":{
              "width":35,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72be381365c14fb4a892ca792e51872a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":81,
                  "y":555},
                "size":{
                  "width":35,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0df7ecefef54f7a966f525f856c1526",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":225,
              "y":54},
            "size":{
              "width":20,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a5401808d90423b84d3bf86e5734c66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":225,
                  "y":54},
                "size":{
                  "width":20,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 食堂切换",
                      "objectsToFades":[{
                          "objectPath":["06456964b1a841689a92c35d45e0bdf5"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/员工就餐-早餐点餐/u62.png"}},
{
          "id":"06456964b1a841689a92c35d45e0bdf5",
          "label":"食堂切换",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":20,
              "y":81},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"ef50416e1ca747ffa6bf71bfb9dd13be",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"192008b050464b2093bcb49484357c5a",
                  "label":"",
                  "parentDynamicPanel":"06456964b1a841689a92c35d45e0bdf5",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":321,
                      "height":189},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dc530651716348a3be98d619811aba23",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"06456964b1a841689a92c35d45e0bdf5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":321,
                          "height":189},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/员工就餐-早餐点餐/u65.png"}},
{
                  "id":"d8ae11b298d5439aab2854660cfb2630",
                  "label":"",
                  "parentDynamicPanel":"06456964b1a841689a92c35d45e0bdf5",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":14,
                      "y":41},
                    "size":{
                      "width":285,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/员工就餐-早餐点餐/u67_line.png"}},
{
                  "id":"17fdedb4937d469e94d8cbe28af4f907",
                  "label":"",
                  "parentDynamicPanel":"06456964b1a841689a92c35d45e0bdf5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":35,
                      "y":18},
                    "size":{
                      "width":106,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ae8753c0553f44a8afcaf0e57c8f08e7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"06456964b1a841689a92c35d45e0bdf5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":35,
                          "y":18},
                        "size":{
                          "width":106,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9e4802da90a3482bad9b1806200f72f1",
                  "label":"",
                  "parentDynamicPanel":"06456964b1a841689a92c35d45e0bdf5",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":14,
                      "y":84},
                    "size":{
                      "width":285,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/员工就餐-早餐点餐/u67_line.png"}},
{
                  "id":"4c8a32381ab34c5498b419988d1e08ed",
                  "label":"",
                  "parentDynamicPanel":"06456964b1a841689a92c35d45e0bdf5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":35,
                      "y":61},
                    "size":{
                      "width":106,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d3af94b579804f88995ecd0ee0626f04",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"06456964b1a841689a92c35d45e0bdf5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":35,
                          "y":61},
                        "size":{
                          "width":106,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8e0bd514f0284e92a2832f897a3638f1",
                  "label":"",
                  "parentDynamicPanel":"06456964b1a841689a92c35d45e0bdf5",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":14,
                      "y":127},
                    "size":{
                      "width":285,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/员工就餐-早餐点餐/u67_line.png"}},
{
                  "id":"ea7296aa0e55407297cf53b5377a1930",
                  "label":"",
                  "parentDynamicPanel":"06456964b1a841689a92c35d45e0bdf5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":35,
                      "y":104},
                    "size":{
                      "width":106,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"87605070d8d64d818f228650fe3219f4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"06456964b1a841689a92c35d45e0bdf5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":35,
                          "y":104},
                        "size":{
                          "width":106,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"dfb13dfe508d47479c178efcb999e0d2",
                  "label":"",
                  "parentDynamicPanel":"06456964b1a841689a92c35d45e0bdf5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":35,
                      "y":151},
                    "size":{
                      "width":106,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ef81325af26a4173803cdfa6483f6ebe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"06456964b1a841689a92c35d45e0bdf5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":35,
                          "y":151},
                        "size":{
                          "width":106,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"57d91d9b507c4e1baf667b578869ea35",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":398,
              "y":46},
            "size":{
              "width":452,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b773b8d950a4b16b18293697eb66de8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":398,
                  "y":46},
                "size":{
                  "width":452,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17e8639e8d194f578d1e05d2403c83d6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":53},
            "size":{
              "width":153,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/员工就餐-早餐点餐/u80_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/员工就餐-早餐点餐/u80_line.png"}},
{
          "id":"d33b32dc8a4d4080ac09e935c4ad1d67",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":398,
              "y":137},
            "size":{
              "width":452,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfec2fb12e3143ebbb8e14a396a1471b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":398,
                  "y":137},
                "size":{
                  "width":452,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e91cab0715b746f4b98009314be88e1f":{
      "scriptId":"u0"},
    "1d40f5af15de4dfa8c6b7948ac451c66":{
      "scriptId":"u1"},
    "181aab52f5ff4c30a715aab377488578":{
      "scriptId":"u2"},
    "ce78f155839c4454834bc7d7bd51a0ea":{
      "scriptId":"u3"},
    "7a16cfebabcb4644b2a839f84c254ac6":{
      "scriptId":"u4"},
    "f06f7d80d63041cfbb305c9b8b000223":{
      "scriptId":"u5"},
    "dd594300095c4b3f890bd3acf35fbc31":{
      "scriptId":"u6"},
    "4a6082447a31492e9442503e830322c3":{
      "scriptId":"u7"},
    "e51927e83a5e46539a8ee963ac6793e7":{
      "scriptId":"u8"},
    "c7ecddf0a831424f82558cf60efd3db6":{
      "scriptId":"u9"},
    "3ecf4fed327748b8acba8c1bac9a1607":{
      "scriptId":"u10"},
    "79380325a4d34f62b273b238abd3ebb3":{
      "scriptId":"u11"},
    "bea7137e54b74276b8359b9f1668d90a":{
      "scriptId":"u12"},
    "12cfda1d3d364911bc9a5aa20461db03":{
      "scriptId":"u13"},
    "a8dcbbbe600b455abd1aef17587a968c":{
      "scriptId":"u14"},
    "b9d601fb6c744fb58b8305fcd59988ed":{
      "scriptId":"u15"},
    "bd7f72d1de254ff49b616a765f3ff3dd":{
      "scriptId":"u16"},
    "6cda14d295764ae690472720d9b756e3":{
      "scriptId":"u17"},
    "a5aff325b8214cf9b261f20094c63cb6":{
      "scriptId":"u18"},
    "5ca6a82321464f21b5df928bd1a5e7a6":{
      "scriptId":"u19"},
    "2db3af5c4620452b8fbd36fa18602d25":{
      "scriptId":"u20"},
    "c259a5d6eafe43f58776193662b7ee3c":{
      "scriptId":"u21"},
    "c531904ad6b4446fbcbf7b0c57dbd98f":{
      "scriptId":"u22"},
    "479ed034cd4249e0b220b3849d6dd824":{
      "scriptId":"u23"},
    "b6f1d35f2417453188d35330d7eed369":{
      "scriptId":"u24"},
    "b41302270154470281fee7536a79792c":{
      "scriptId":"u25"},
    "6e30796553a847e29cca9747ff3fcecf":{
      "scriptId":"u26"},
    "7a2b632980204041b6d4158a1cdabfcb":{
      "scriptId":"u27"},
    "5ab2509a404140c48f095a24f8997bd9":{
      "scriptId":"u28"},
    "a3402b39261f40d18875f55348598139":{
      "scriptId":"u29"},
    "ca0e4ff1cc734c86a0a25b09bc0eb240":{
      "scriptId":"u30"},
    "3b452cf3b9c54942845b75152dc0d311":{
      "scriptId":"u31"},
    "caae7f23dd81420397109eaaefc3b65a":{
      "scriptId":"u32"},
    "1dc5767e0ad34110b4a763d03bda0346":{
      "scriptId":"u33"},
    "4064ccb2afa34d418deb2054fbea3a0e":{
      "scriptId":"u34"},
    "4c1681765c7a4e3d95d02a7785d6e0be":{
      "scriptId":"u35"},
    "08e4968cbaa646c9b5ceb4a04a462905":{
      "scriptId":"u36"},
    "a04f5fe480ba4286a77d0168fa439317":{
      "scriptId":"u37"},
    "f8820332a5f941c38edb6e4f387dcddc":{
      "scriptId":"u38"},
    "700e3af920f4410181d33944a48473be":{
      "scriptId":"u39"},
    "ee9db8b465a045fa8383e9317453b09d":{
      "scriptId":"u40"},
    "ef098ffce0ba4e9ebbd82c7913cddcbf":{
      "scriptId":"u41"},
    "eb671825efd049f18b316c9b71173f18":{
      "scriptId":"u42"},
    "421906059d204bdcaf3700d08a9a280a":{
      "scriptId":"u43"},
    "0e9d578d2852466bab3bd902062347e3":{
      "scriptId":"u44"},
    "dd75bbe7fe0a47569a986697bbb31ee8":{
      "scriptId":"u45"},
    "acde209eb2a04073b1b3aca4a83a7aed":{
      "scriptId":"u46"},
    "90ce4b170284412ea6731ab3e46476b9":{
      "scriptId":"u47"},
    "fee908a7cd65459eac41542e62bb045b":{
      "scriptId":"u48"},
    "d8a5437478e5413595b895f42d9506fc":{
      "scriptId":"u49"},
    "ba0f9c56dcb7474f8353806c94cd3a53":{
      "scriptId":"u50"},
    "3e005a12f282444a9585dfa3964e9fe3":{
      "scriptId":"u51"},
    "e091ccdefc73497fb907e68050e6601b":{
      "scriptId":"u52"},
    "06b324a724cd43fca492fcae95353edf":{
      "scriptId":"u53"},
    "c22de3278aa24e2089ded25f707e3578":{
      "scriptId":"u54"},
    "78c4d735aad94368bd9d9cab3ce75083":{
      "scriptId":"u55"},
    "8c500b13933e40a48851bf9ebe516ffc":{
      "scriptId":"u56"},
    "a4f3b83cb59744cda425934d1179cc6d":{
      "scriptId":"u57"},
    "4e54b2a422ee43449ce1dc46c5fba818":{
      "scriptId":"u58"},
    "e47add00e9ff4978bd87b30aa1a4c2d9":{
      "scriptId":"u59"},
    "7d650399b6d44dc4bc734db86c2c7482":{
      "scriptId":"u60"},
    "72be381365c14fb4a892ca792e51872a":{
      "scriptId":"u61"},
    "c0df7ecefef54f7a966f525f856c1526":{
      "scriptId":"u62"},
    "4a5401808d90423b84d3bf86e5734c66":{
      "scriptId":"u63"},
    "06456964b1a841689a92c35d45e0bdf5":{
      "scriptId":"u64"},
    "192008b050464b2093bcb49484357c5a":{
      "scriptId":"u65"},
    "dc530651716348a3be98d619811aba23":{
      "scriptId":"u66"},
    "d8ae11b298d5439aab2854660cfb2630":{
      "scriptId":"u67"},
    "17fdedb4937d469e94d8cbe28af4f907":{
      "scriptId":"u68"},
    "ae8753c0553f44a8afcaf0e57c8f08e7":{
      "scriptId":"u69"},
    "9e4802da90a3482bad9b1806200f72f1":{
      "scriptId":"u70"},
    "4c8a32381ab34c5498b419988d1e08ed":{
      "scriptId":"u71"},
    "d3af94b579804f88995ecd0ee0626f04":{
      "scriptId":"u72"},
    "8e0bd514f0284e92a2832f897a3638f1":{
      "scriptId":"u73"},
    "ea7296aa0e55407297cf53b5377a1930":{
      "scriptId":"u74"},
    "87605070d8d64d818f228650fe3219f4":{
      "scriptId":"u75"},
    "dfb13dfe508d47479c178efcb999e0d2":{
      "scriptId":"u76"},
    "ef81325af26a4173803cdfa6483f6ebe":{
      "scriptId":"u77"},
    "57d91d9b507c4e1baf667b578869ea35":{
      "scriptId":"u78"},
    "8b773b8d950a4b16b18293697eb66de8":{
      "scriptId":"u79"},
    "17e8639e8d194f578d1e05d2403c83d6":{
      "scriptId":"u80"},
    "d33b32dc8a4d4080ac09e935c4ad1d67":{
      "scriptId":"u81"},
    "cfec2fb12e3143ebbb8e14a396a1471b":{
      "scriptId":"u82"}}});