$axure.loadCurrentPage({
  "url":"午餐券详情_1.html",
  "generationDate":new Date(1448611752982.42),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"tplb_img",
"jdt_bfb",
"qsjs_r",
"tpcc_wz",
"tpcc_zt",
"tpcc_kd",
"yz_msg"],
  "page":{
    "packageId":"fe6f933585d74a10828295fca61721a5",
    "type":"Axure:Page",
    "name":"午餐券详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d5de396e5e87414a99d1b9400242fba7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":320,
              "height":620},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c5a58a0c8fd4c8b8458d184fcf861f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":320,
                  "height":620},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-午餐/u2.png"}},
{
          "id":"5c1a82ac6cc4491fae0f9cdf1f7b26cc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":35},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"193b7272ed164fa2a363307acee4ea64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":35},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u4.png"}},
{
          "id":"0edd27ed89bd40118240c6ca519a67d8",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":122,
              "y":46},
            "size":{
              "width":128,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"474246fb39eb440aba56197b9d13a71d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":122,
                  "y":46},
                "size":{
                  "width":128,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37861a56130245dd9cd47a88bc6e6145",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":48},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a93a31ea71444890b4b6ac8ad75c8693",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":48},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u8.png"}},
{
          "id":"2d804eeab5724d0db54b3a3eef916137",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":20},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"512451592f734756bfa032398f96e772",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":20},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u2.png"}},
{
          "id":"49eccbb9b4fc4c249240e2b834aff939",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":91},
            "size":{
              "width":320,
              "height":49},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94b024c3d8064b7da2e512da72f597ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":91},
                "size":{
                  "width":320,
                  "height":49},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/午餐券详情_1/u10.png"}},
{
          "id":"73f65e4238474ccc964a07a4f9378d4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":110},
            "size":{
              "width":219,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32fb53cc8f4d43e8a9d4fc9b7ba50243",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":110},
                "size":{
                  "width":219,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dac1e3ed3c8b47fd870e43acffc1bd06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":223,
              "y":110},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e608067cc6146d6a14ec0bcfdc68761",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":223,
                  "y":110},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9dffb095fa7474a841f151dd94cf396",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":290,
              "y":110},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a5a8756aaf144f49b555adffe8cd693",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":290,
                  "y":110},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a7f0bd5f9304f8c8e6b07de796486d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":209},
            "size":{
              "width":320,
              "height":208},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdd2f86e679841e79dfb7ea7ee9e2a78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":209},
                "size":{
                  "width":320,
                  "height":208},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/早餐订单详情/u26.png"}},
{
          "id":"e8ade452a25b4c45a5a26dc567b0e645",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":31,
              "y":226},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60c44044f703495ca353022133692285",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":31,
                  "y":226},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97e0616e637d4619aebf0f0d7583f6f8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":247},
            "size":{
              "width":304,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC8C8C8}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/下单/u20_line.png"}},
{
          "id":"0243c325c2554b5e92719791b302f286",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":31,
              "y":291},
            "size":{
              "width":249,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08603e277c16460db820e644967d432c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":31,
                  "y":291},
                "size":{
                  "width":249,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66765669b5354ca6b2f3aa8ebdd8af9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":31,
              "y":317},
            "size":{
              "width":289,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cec5672de2d64fbe9475db862b307c0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":31,
                  "y":317},
                "size":{
                  "width":289,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a362e7b76494635800364fcedd385c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":31,
              "y":343},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f358602f820441296ea51a9c66ee78a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":31,
                  "y":343},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ac21193269540fda31a42e292279062",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":31,
              "y":265},
            "size":{
              "width":209,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4a17967175946bb912c8596ec70cfcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":31,
                  "y":265},
                "size":{
                  "width":209,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db71ef8339ca4d33abc6b030b38eb24e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":31,
              "y":369},
            "size":{
              "width":309,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d127547042a4ac190a624e46a856998",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":31,
                  "y":369},
                "size":{
                  "width":309,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4b54d66f2d84ce0b40ba2b1e39f0edd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":150},
            "size":{
              "width":320,
              "height":49},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d47386238b034acbb8112de03f27bc49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":150},
                "size":{
                  "width":320,
                  "height":49},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/午餐券详情_1/u10.png"}},
{
          "id":"479d057068334922a5046af97230ad54",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":168},
            "size":{
              "width":219,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f8463aaa2a64f529e360eb8ffd39211",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":168},
                "size":{
                  "width":219,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08767409a471404682fc7043d3886594",
          "label":"退款二次确认",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":45,
              "y":226.5},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"ac2730c2f570420887ae6e5b48872618",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"16758c3dc19e40288ed88fab0e5dd489",
                  "label":"",
                  "parentDynamicPanel":"08767409a471404682fc7043d3886594",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"bold",
                    "size":{
                      "width":270,
                      "height":173},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e42ae93de4ce4013bb0dc86fcf754820",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08767409a471404682fc7043d3886594",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"bold",
                        "size":{
                          "width":270,
                          "height":173},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/早餐订单详情/u97.png"}},
{
                  "id":"bea46b7042984e7d802e1bd40ac6b6fc",
                  "label":"",
                  "parentDynamicPanel":"08767409a471404682fc7043d3886594",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":57,
                      "y":70},
                    "size":{
                      "width":213,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"37659f9f2a6441bbbeb27855444f7ffc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08767409a471404682fc7043d3886594",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "location":{
                          "x":57,
                          "y":70},
                        "size":{
                          "width":213,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5d3e5acd12fc496b8dda1e17157ac998",
                  "label":"",
                  "parentDynamicPanel":"08767409a471404682fc7043d3886594",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":56,
                      "y":140},
                    "size":{
                      "width":37,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b82ba2d0477a4df29f5417d1dc57b615",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08767409a471404682fc7043d3886594",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":56,
                          "y":140},
                        "size":{
                          "width":37,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0b8e65589c9d49ef810c9e417d396df3",
                  "label":"",
                  "parentDynamicPanel":"08767409a471404682fc7043d3886594",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":176,
                      "y":140},
                    "size":{
                      "width":37,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b436fbc4934e45c4a5f10c6aeb1be5b0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08767409a471404682fc7043d3886594",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":176,
                          "y":140},
                        "size":{
                          "width":37,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"08f3c028edcd431fb5629e8a19460a09",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":162},
            "size":{
              "width":70,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0888a7ed30ef4bbf992ed329fa874ba7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":162},
                "size":{
                  "width":70,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 退款二次确认",
                      "objectsToFades":[{
                          "objectPath":["08767409a471404682fc7043d3886594"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/早餐订单详情/u105.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d5de396e5e87414a99d1b9400242fba7":{
      "scriptId":"u0"},
    "9c5a58a0c8fd4c8b8458d184fcf861f3":{
      "scriptId":"u1"},
    "5c1a82ac6cc4491fae0f9cdf1f7b26cc":{
      "scriptId":"u2"},
    "193b7272ed164fa2a363307acee4ea64":{
      "scriptId":"u3"},
    "0edd27ed89bd40118240c6ca519a67d8":{
      "scriptId":"u4"},
    "474246fb39eb440aba56197b9d13a71d":{
      "scriptId":"u5"},
    "37861a56130245dd9cd47a88bc6e6145":{
      "scriptId":"u6"},
    "a93a31ea71444890b4b6ac8ad75c8693":{
      "scriptId":"u7"},
    "2d804eeab5724d0db54b3a3eef916137":{
      "scriptId":"u8"},
    "512451592f734756bfa032398f96e772":{
      "scriptId":"u9"},
    "49eccbb9b4fc4c249240e2b834aff939":{
      "scriptId":"u10"},
    "94b024c3d8064b7da2e512da72f597ba":{
      "scriptId":"u11"},
    "73f65e4238474ccc964a07a4f9378d4e":{
      "scriptId":"u12"},
    "32fb53cc8f4d43e8a9d4fc9b7ba50243":{
      "scriptId":"u13"},
    "dac1e3ed3c8b47fd870e43acffc1bd06":{
      "scriptId":"u14"},
    "3e608067cc6146d6a14ec0bcfdc68761":{
      "scriptId":"u15"},
    "b9dffb095fa7474a841f151dd94cf396":{
      "scriptId":"u16"},
    "0a5a8756aaf144f49b555adffe8cd693":{
      "scriptId":"u17"},
    "6a7f0bd5f9304f8c8e6b07de796486d2":{
      "scriptId":"u18"},
    "fdd2f86e679841e79dfb7ea7ee9e2a78":{
      "scriptId":"u19"},
    "e8ade452a25b4c45a5a26dc567b0e645":{
      "scriptId":"u20"},
    "60c44044f703495ca353022133692285":{
      "scriptId":"u21"},
    "97e0616e637d4619aebf0f0d7583f6f8":{
      "scriptId":"u22"},
    "0243c325c2554b5e92719791b302f286":{
      "scriptId":"u23"},
    "08603e277c16460db820e644967d432c":{
      "scriptId":"u24"},
    "66765669b5354ca6b2f3aa8ebdd8af9a":{
      "scriptId":"u25"},
    "cec5672de2d64fbe9475db862b307c0c":{
      "scriptId":"u26"},
    "6a362e7b76494635800364fcedd385c0":{
      "scriptId":"u27"},
    "6f358602f820441296ea51a9c66ee78a":{
      "scriptId":"u28"},
    "3ac21193269540fda31a42e292279062":{
      "scriptId":"u29"},
    "a4a17967175946bb912c8596ec70cfcc":{
      "scriptId":"u30"},
    "db71ef8339ca4d33abc6b030b38eb24e":{
      "scriptId":"u31"},
    "7d127547042a4ac190a624e46a856998":{
      "scriptId":"u32"},
    "e4b54d66f2d84ce0b40ba2b1e39f0edd":{
      "scriptId":"u33"},
    "d47386238b034acbb8112de03f27bc49":{
      "scriptId":"u34"},
    "479d057068334922a5046af97230ad54":{
      "scriptId":"u35"},
    "2f8463aaa2a64f529e360eb8ffd39211":{
      "scriptId":"u36"},
    "08767409a471404682fc7043d3886594":{
      "scriptId":"u37"},
    "16758c3dc19e40288ed88fab0e5dd489":{
      "scriptId":"u38"},
    "e42ae93de4ce4013bb0dc86fcf754820":{
      "scriptId":"u39"},
    "bea46b7042984e7d802e1bd40ac6b6fc":{
      "scriptId":"u40"},
    "37659f9f2a6441bbbeb27855444f7ffc":{
      "scriptId":"u41"},
    "5d3e5acd12fc496b8dda1e17157ac998":{
      "scriptId":"u42"},
    "b82ba2d0477a4df29f5417d1dc57b615":{
      "scriptId":"u43"},
    "0b8e65589c9d49ef810c9e417d396df3":{
      "scriptId":"u44"},
    "b436fbc4934e45c4a5f10c6aeb1be5b0":{
      "scriptId":"u45"},
    "08f3c028edcd431fb5629e8a19460a09":{
      "scriptId":"u46"},
    "0888a7ed30ef4bbf992ed329fa874ba7":{
      "scriptId":"u47"}}});