$axure.loadCurrentPage({
  "url":"员工就餐-午餐.html",
  "generationDate":new Date(1448275246512.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"tplb_img",
"jdt_bfb",
"qsjs_r",
"tpcc_wz",
"tpcc_zt",
"tpcc_kd",
"yz_msg"],
  "page":{
    "packageId":"6448cf87f8c74bfeb1ceb32160fd05f2",
    "type":"Axure:Page",
    "name":"员工就餐-午餐",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4a4199315e4048a6b41eb6186dae7217",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":320,
              "height":590},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b56592ff62964f03b920d434d46b50ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":320,
                  "height":590},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-午餐/u0.png"}},
{
          "id":"57ca9a7056194e1aba7991b6b2dfe636",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":20},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ad03dfc0dde4f20b2711af551fd4d70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":20},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页/u2.png"}},
{
          "id":"a00b41987a414f5fa5c3e2e6ab4f4486",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":35},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9efeb5aa11d44af593523c8d4dac6af0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":35},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页/u4.png"}},
{
          "id":"d4de20b488ef464f897a405e8b1871d3",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":155,
              "y":48},
            "size":{
              "width":95,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bd63439e7d64b6e99745db67fb7d197",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":155,
                  "y":48},
                "size":{
                  "width":95,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"526a78c716584aa7a407714ed77ff1f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":48},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4090e5cec3c47e98247d900ce4fa7bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":48},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页/u8.png"}},
{
          "id":"33c4f2b193164f36b6d1c2c565b67ab8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":100},
            "size":{
              "width":303,
              "height":320},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07728c50de114909bc095f52838c6bba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":29,
                  "y":100},
                "size":{
                  "width":303,
                  "height":320},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-午餐/u10.png"}},
{
          "id":"60fbfc020c7043abab4708a2b4b46322",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":80,
              "y":190},
            "size":{
              "width":185,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee1abef6c8404ba698d6c69e3e5ecf9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":80,
                  "y":190},
                "size":{
                  "width":185,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-午餐/u12.png"}},
{
          "id":"6713ddcb438047a493008ac6c4d7dace",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":284,
              "y":380},
            "size":{
              "width":23,
              "height":23},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54dfd5380f5241148a6dbe9fc3d6c904",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":284,
                  "y":380},
                "size":{
                  "width":23,
                  "height":23},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 消费详情,<br>遮罩",
                      "objectsToFades":[{
                          "objectPath":["85901d2e0d8b4180a2ff4b0749547d99"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["aea1a3f82d6542a98984d3dda747676c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/员工就餐-午餐/u14.png"}},
{
          "id":"c24a2ab075814f8fb537f4115d431622",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":199,
              "y":384},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb0eb9a662d249dabe7ada77767be901",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":199,
                  "y":384},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 消费详情,<br>遮罩",
                      "objectsToFades":[{
                          "objectPath":["85901d2e0d8b4180a2ff4b0749547d99"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["aea1a3f82d6542a98984d3dda747676c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f998cb3ce4af459a9b633d8759cc8df6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":44,
              "y":120},
            "size":{
              "width":190,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d618d09037e4439839e2afa6708daf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":44,
                  "y":120},
                "size":{
                  "width":190,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21db972286054f4a910cdb0a511243da",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":171},
            "size":{
              "width":289,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/员工就餐-午餐/u20_line.png"}},
{
          "id":"77bba4ad541f46c89db41eab2fa56ef4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":44,
              "y":149},
            "size":{
              "width":280,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"908ddab90d02402b8af7cd2f902f2145",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":44,
                  "y":149},
                "size":{
                  "width":280,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aea1a3f82d6542a98984d3dda747676c",
          "label":"遮罩",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x91000000},
            "location":{
              "x":20,
              "y":80},
            "size":{
              "width":320,
              "height":530},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"956aa09ae8854a3eb4ceb1cee800413a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x91000000},
                "location":{
                  "x":20,
                  "y":80},
                "size":{
                  "width":320,
                  "height":530},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工就餐-午餐/遮罩_u23.png"}},
{
          "id":"85901d2e0d8b4180a2ff4b0749547d99",
          "label":"消费详情",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":20,
              "y":174},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"8f89b91226ad4ea78651c959e36480be",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"63c6aa5b47224e85ad2b2aafb751f2b5",
                  "label":"",
                  "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":290,
                      "height":280},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"8"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5b34f09544524f2fb55a901d693f981f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":290,
                          "height":280},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"8"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/员工就餐-午餐/u26.png"}},
{
                  "id":"fcfa2e8d7c9e47569348d74fb58f9c07",
                  "label":"",
                  "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":35,
                      "y":126},
                    "size":{
                      "width":289,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9d4c1edbb91a47f79cce88c3f2fe824d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":35,
                          "y":126},
                        "size":{
                          "width":289,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e6712076bf5b4a8198dfa05e83d1df9b",
                  "label":"",
                  "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":35,
                      "y":210},
                    "size":{
                      "width":289,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"164d19bfb9a6443d8e6bc8223eeb1a02",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":35,
                          "y":210},
                        "size":{
                          "width":289,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8c8d2a1038e54c26b5b9e437408ba299",
                  "label":"",
                  "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":35,
                      "y":250},
                    "size":{
                      "width":289,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c5f3cdb6bc394e56a08e67bd2488bb5b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":35,
                          "y":250},
                        "size":{
                          "width":289,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d7986ffd7f6d4038a84a05baa2e9161f",
                  "label":"",
                  "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":35,
                      "y":54},
                    "size":{
                      "width":289,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fb53f926dda64ba4a8b46553baf73de3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":35,
                          "y":54},
                        "size":{
                          "width":289,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f08ab10efbfa4abc832e74d82df3e546",
                  "label":"",
                  "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":35,
                      "y":90},
                    "size":{
                      "width":289,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"32689880f45544c582fa08871b1aacfa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":35,
                          "y":90},
                        "size":{
                          "width":289,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"929ed0c919e641808d2cd3cb3d42ea2c",
                  "label":"",
                  "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":35,
                      "y":170},
                    "size":{
                      "width":289,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3692c820a56449a4ab788d9a28365a43",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":35,
                          "y":170},
                        "size":{
                          "width":289,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f3d3b97c339c42179c0fc461ea37b5b1",
                  "label":"",
                  "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":277,
                      "y":31},
                    "size":{
                      "width":23,
                      "height":23},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"68cabd9479c041299ecf3e22ec071ec8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"85901d2e0d8b4180a2ff4b0749547d99",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":277,
                          "y":31},
                        "size":{
                          "width":23,
                          "height":23},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF666666}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 遮罩,<br>消费详情",
                              "objectsToFades":[{
                                  "objectPath":["aea1a3f82d6542a98984d3dda747676c"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["85901d2e0d8b4180a2ff4b0749547d99"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/员工就餐-午餐/u40.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "4a4199315e4048a6b41eb6186dae7217":{
      "scriptId":"u0"},
    "b56592ff62964f03b920d434d46b50ec":{
      "scriptId":"u1"},
    "57ca9a7056194e1aba7991b6b2dfe636":{
      "scriptId":"u2"},
    "6ad03dfc0dde4f20b2711af551fd4d70":{
      "scriptId":"u3"},
    "a00b41987a414f5fa5c3e2e6ab4f4486":{
      "scriptId":"u4"},
    "9efeb5aa11d44af593523c8d4dac6af0":{
      "scriptId":"u5"},
    "d4de20b488ef464f897a405e8b1871d3":{
      "scriptId":"u6"},
    "4bd63439e7d64b6e99745db67fb7d197":{
      "scriptId":"u7"},
    "526a78c716584aa7a407714ed77ff1f0":{
      "scriptId":"u8"},
    "b4090e5cec3c47e98247d900ce4fa7bc":{
      "scriptId":"u9"},
    "33c4f2b193164f36b6d1c2c565b67ab8":{
      "scriptId":"u10"},
    "07728c50de114909bc095f52838c6bba":{
      "scriptId":"u11"},
    "60fbfc020c7043abab4708a2b4b46322":{
      "scriptId":"u12"},
    "ee1abef6c8404ba698d6c69e3e5ecf9b":{
      "scriptId":"u13"},
    "6713ddcb438047a493008ac6c4d7dace":{
      "scriptId":"u14"},
    "54dfd5380f5241148a6dbe9fc3d6c904":{
      "scriptId":"u15"},
    "c24a2ab075814f8fb537f4115d431622":{
      "scriptId":"u16"},
    "cb0eb9a662d249dabe7ada77767be901":{
      "scriptId":"u17"},
    "f998cb3ce4af459a9b633d8759cc8df6":{
      "scriptId":"u18"},
    "7d618d09037e4439839e2afa6708daf0":{
      "scriptId":"u19"},
    "21db972286054f4a910cdb0a511243da":{
      "scriptId":"u20"},
    "77bba4ad541f46c89db41eab2fa56ef4":{
      "scriptId":"u21"},
    "908ddab90d02402b8af7cd2f902f2145":{
      "scriptId":"u22"},
    "aea1a3f82d6542a98984d3dda747676c":{
      "scriptId":"u23"},
    "956aa09ae8854a3eb4ceb1cee800413a":{
      "scriptId":"u24"},
    "85901d2e0d8b4180a2ff4b0749547d99":{
      "scriptId":"u25"},
    "63c6aa5b47224e85ad2b2aafb751f2b5":{
      "scriptId":"u26"},
    "5b34f09544524f2fb55a901d693f981f":{
      "scriptId":"u27"},
    "fcfa2e8d7c9e47569348d74fb58f9c07":{
      "scriptId":"u28"},
    "9d4c1edbb91a47f79cce88c3f2fe824d":{
      "scriptId":"u29"},
    "e6712076bf5b4a8198dfa05e83d1df9b":{
      "scriptId":"u30"},
    "164d19bfb9a6443d8e6bc8223eeb1a02":{
      "scriptId":"u31"},
    "8c8d2a1038e54c26b5b9e437408ba299":{
      "scriptId":"u32"},
    "c5f3cdb6bc394e56a08e67bd2488bb5b":{
      "scriptId":"u33"},
    "d7986ffd7f6d4038a84a05baa2e9161f":{
      "scriptId":"u34"},
    "fb53f926dda64ba4a8b46553baf73de3":{
      "scriptId":"u35"},
    "f08ab10efbfa4abc832e74d82df3e546":{
      "scriptId":"u36"},
    "32689880f45544c582fa08871b1aacfa":{
      "scriptId":"u37"},
    "929ed0c919e641808d2cd3cb3d42ea2c":{
      "scriptId":"u38"},
    "3692c820a56449a4ab788d9a28365a43":{
      "scriptId":"u39"},
    "f3d3b97c339c42179c0fc461ea37b5b1":{
      "scriptId":"u40"},
    "68cabd9479c041299ecf3e22ec071ec8":{
      "scriptId":"u41"}}});