$axure.loadCurrentPage({
  "url":"退款详情.html",
  "generationDate":new Date(1448450537403.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"tplb_img",
"jdt_bfb",
"qsjs_r",
"tpcc_wz",
"tpcc_zt",
"tpcc_kd",
"yz_msg"],
  "page":{
    "packageId":"1acbb379984344a797d65fc1d772cfb2",
    "type":"Axure:Page",
    "name":"退款详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ec33c8fd2b1a4470826abebf9663aefd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":410,
              "y":92},
            "size":{
              "width":320,
              "height":568},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ca630a15b314260a9b4cd503e2ad794",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":410,
                  "y":92},
                "size":{
                  "width":320,
                  "height":568},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u0.png"}},
{
          "id":"4956a6180d4a4782991bbeb8a4739d37",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":417,
              "y":92},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c3d3185b68d49f581b740fb3bad5572",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":417,
                  "y":92},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u2.png"}},
{
          "id":"8d412e719a7c457b83e6a4977e4087f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":107},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9440afccc85143feb3542d5226111131",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":107},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u4.png"}},
{
          "id":"4db81a5e70ae4976a6800a2895327ddb",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":522,
              "y":118},
            "size":{
              "width":138,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3bc9192658f46ae8b636f01b992df68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":522,
                  "y":118},
                "size":{
                  "width":138,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bca9a1760565432daf70a407760b491e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":421,
              "y":120},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79c4016af0b248e38dc3a82e0b07e958",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":421,
                  "y":120},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u8.png"}},
{
          "id":"77894ed23bd74c98aafdf3cb35f8725f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":282},
            "size":{
              "width":320,
              "height":163},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feebe2a2ce574a20b93c8731e06b5a00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":282},
                "size":{
                  "width":320,
                  "height":163},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/退款详情/u10.png"}},
{
          "id":"3ce4c342ce8348c6942739d55343ad3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":163},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cdf69b22f3843d48638eea2fb080cb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":163},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/退款详情/u12.png"}},
{
          "id":"4b12fa9a812243d0bf346c6978d6e379",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":421,
              "y":180},
            "size":{
              "width":169,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c4f5d1a919646c2a4b885cef3b9de77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":421,
                  "y":180},
                "size":{
                  "width":169,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"915a41d3c4dc4b4fb819569393a3eb6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":659,
              "y":180},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d2020039d1f448fa17f2f8b13c06f4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":659,
                  "y":180},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"631783908c134065a6881ee443b0ba88",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":298},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e0aad7948044c1793d080dcfddd9328",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":425,
                  "y":298},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"474484fb21154038b99ac21b4e47acde",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":421,
              "y":319},
            "size":{
              "width":298,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/退款详情/u20_line.png"}},
{
          "id":"54919b90a98c47068b53d4bdaf0f6a39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":445,
              "y":398},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd2783080b1e4866933c976a1ae88903",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":445,
                  "y":398},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47c20a8ade7c4e609198f92a07d32fae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":445,
              "y":414},
            "size":{
              "width":90,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a50cbb1bb6342d08baf9a762cba916c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":445,
                  "y":414},
                "size":{
                  "width":90,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59e646e1ecc24f2fb30f8364d7a0e1d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":445,
              "y":356},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0657c72d1d9447b98e2d13ef9e2e00a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":445,
                  "y":356},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b576b73754d46ddb4b8074c6316464d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":445,
              "y":372},
            "size":{
              "width":90,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51818b133ee845aeace22788d7a249e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":445,
                  "y":372},
                "size":{
                  "width":90,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a43243063cc4202b728794b61ee8dfa",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":385},
            "size":{
              "width":10,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/退款详情/u29_end.png",
            "line~":"images/退款详情/u29_line.png"}},
{
          "id":"4816378ea1134331b5472e810733f844",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":340},
            "size":{
              "width":10,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/退款详情/u30_end.png",
            "line~":"images/退款详情/u30_line.png"}},
{
          "id":"f281adcb6268436886999cd4b6c6aeb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":223},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ced5b6726b14b64bd0a6a3711673034",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":223},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/退款详情/u12.png"}},
{
          "id":"4985d1d0771a44c18339bf35f08216aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":421,
              "y":234},
            "size":{
              "width":304,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6ed962613ba4bf9b6a22219da38f05f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":421,
                  "y":234},
                "size":{
                  "width":304,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4ebd8ef2b2645c998256e8cd65e3728",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":40,
              "y":92},
            "size":{
              "width":320,
              "height":568},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d5a0a24e6244d1db098a6581518f973",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":40,
                  "y":92},
                "size":{
                  "width":320,
                  "height":568},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u0.png"}},
{
          "id":"4f76624f61484d819ae7c1f55c134e19",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":92},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"264dc07351fa412783300abd29a59242",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":92},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u2.png"}},
{
          "id":"8c14b54b3cc84f34b7952df7fd422fa0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":107},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"958c3024c6644554952dd3a08f21a766",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":107},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u4.png"}},
{
          "id":"d73c4b994a484a15a939616e954f636b",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":152,
              "y":118},
            "size":{
              "width":138,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce0aa95b22e342c0845f996b4561ff56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":152,
                  "y":118},
                "size":{
                  "width":138,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05f0fbacf7744796aaeec2a650d8c8ee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":120},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02c09712e8c6460a978ccc9c9cee1f2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":120},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u8.png"}},
{
          "id":"5f6be778f0114e04965dc8d566564ae7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":282},
            "size":{
              "width":320,
              "height":118},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"866b39e702d346a2a93698351ea737be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":282},
                "size":{
                  "width":320,
                  "height":118},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/退款详情/u45.png"}},
{
          "id":"fb655a51bb8e463cadb98a45883bcc8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":163},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e43f1382a4a34820809a375ea17580e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":163},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/退款详情/u12.png"}},
{
          "id":"968c34524c764768819c4aa7e45117d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":180},
            "size":{
              "width":169,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3437ba64e7ff4e0fb822c2e6278d68aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":180},
                "size":{
                  "width":169,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12e7d02259614063bbd00c97c0f36f62",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":289,
              "y":180},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"889fc76cd0b64fd6ad3098de9ebc11f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":289,
                  "y":180},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"291afebf3fde4eec860becfd5c09dab4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":298},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb5ce28f7b9c4ea094a1f15aa22f9497",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":298},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05b651f2cf4a46ef97cd771e4d062a29",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":319},
            "size":{
              "width":298,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/退款详情/u20_line.png"}},
{
          "id":"ca92aab5ccdc49638723ac41d0efd848",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":356},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c39bc3d240df4ed3884763bb8e85f914",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":356},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1748acf8d7f94286b903fee310783f42",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":75,
              "y":372},
            "size":{
              "width":90,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77ccc69f67144ee3b12ccb262f2d6afc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":75,
                  "y":372},
                "size":{
                  "width":90,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6bccc2b121294070ba73567598c67ad9",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":348},
            "size":{
              "width":10,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/退款详情/u29_end.png",
            "line~":"images/退款详情/u29_line.png"}},
{
          "id":"47e9f0c7b95b4578b0f47eeb7d4f3a1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":223},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44ad981b70e24a3bad83d843678ab273",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":223},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/退款详情/u12.png"}},
{
          "id":"c27d725c45df42c5b0fa314a834f88ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":51,
              "y":240},
            "size":{
              "width":279,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"312565751bac4aed939e85a17bfcdec0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":51,
                  "y":240},
                "size":{
                  "width":279,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6528242168cb4387a5d02ea53e313c5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":45},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b2090b11ac7488395e8eee85cab8fdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":45},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44ef0813eaa6412a8362b194234b60a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":45},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a77cbdb44b7413b8d45d648df442978",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":45},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56ab92ed43b244d1a0386647b03d6b5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":40},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a77264dd99ea4300a31cbee1aa6e3ca9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":40},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ba83242f9f34d39a3e227beb2ea48bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":780,
              "y":87},
            "size":{
              "width":320,
              "height":568},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e462245d17d46b9b96a99e4582fae5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":780,
                  "y":87},
                "size":{
                  "width":320,
                  "height":568},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u0.png"}},
{
          "id":"b5b06a23d8a24d07a408cede9b1e49b7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":787,
              "y":87},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a46401af5284462b14669b4ac0d5ef6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":787,
                  "y":87},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u2.png"}},
{
          "id":"e36202778b804f2ca6fef4c0be7ca120",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":102},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c71412d901014056b7f97af3f8151175",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":102},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u4.png"}},
{
          "id":"03ba3c2a76d34697aa951f1cd2b9e294",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":892,
              "y":113},
            "size":{
              "width":138,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cb12fc407d24907a26c8ebbb35f26fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":892,
                  "y":113},
                "size":{
                  "width":138,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4dca888d8bd444e879815a854a9cfe8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":115},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f061e825e6114d5995b2232489d0ea45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":791,
                  "y":115},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u8.png"}},
{
          "id":"f55669dc33c34a80b7928a10d66da59d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":277},
            "size":{
              "width":320,
              "height":210},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f27b3961fba2404aa7db4da0d1e20b73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":277},
                "size":{
                  "width":320,
                  "height":210},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/退款详情/u81.png"}},
{
          "id":"ec8a02a94c9b44f59eca0fa81996508d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":158},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d1ebf2a7be34d128e23f5e9428cab23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":158},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/退款详情/u12.png"}},
{
          "id":"d25425c10e944eb494ed9b6bd2b1943d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":175},
            "size":{
              "width":169,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9246297dac7a4078aba3791835ab36a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":791,
                  "y":175},
                "size":{
                  "width":169,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a371fa1f906491fa609cbb3e5a22df2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":1029,
              "y":175},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d920657dc014e84af5131d67e795be7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":1029,
                  "y":175},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04c04c1ba62a464dbdac97107b39606c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":795,
              "y":293},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c58c789d63e4917aeee7f65581804c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":795,
                  "y":293},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01c6306f569c493b89b3ebaa90817e54",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":795,
              "y":377},
            "size":{
              "width":10,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/退款详情/u30_end.png",
            "line~":"images/退款详情/u30_line.png"}},
{
          "id":"f28a583c2ecc4523aa39999b5c0050b9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":314},
            "size":{
              "width":298,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/退款详情/u20_line.png"}},
{
          "id":"0802d53bdb524b6b9f7f222de3c4fcd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":815,
              "y":393},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0a2a0805c8546ca91e3937b41002cc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":815,
                  "y":393},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"055cd494e0dd4148bb9ee30370889055",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":815,
              "y":409},
            "size":{
              "width":90,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c94c1c46dca465f85a99bc036217f58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":815,
                  "y":409},
                "size":{
                  "width":90,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b980d320c4d346f18944f4b17946d8cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":815,
              "y":351},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a12deb1b90a4ad58622892b231541bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":815,
                  "y":351},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"303a6cef632544128b379b272d7d8725",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":815,
              "y":367},
            "size":{
              "width":90,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"570a4c0b4bf74b60a8459e5dd7519fc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":815,
                  "y":367},
                "size":{
                  "width":90,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a36d743a857047c59949b6557933eddc",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":795,
              "y":421},
            "size":{
              "width":10,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/退款详情/u29_end.png",
            "line~":"images/退款详情/u29_line.png"}},
{
          "id":"f075bf59898544c1afbbf4d59bf10a03",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":795,
              "y":335},
            "size":{
              "width":10,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/退款详情/u30_end.png",
            "line~":"images/退款详情/u30_line.png"}},
{
          "id":"4e53b815e2414ebc8b23bb65ef96147c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":815,
              "y":429},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a767dd065e714283975f5ee618c80f43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":815,
                  "y":429},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae112251c9474bcf881f10d551c2b19b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":815,
              "y":447},
            "size":{
              "width":90,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6d1b962471c48d684c66c2f2df48f8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":815,
                  "y":447},
                "size":{
                  "width":90,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"117cbcb950a04b3a8f0a70db8f9853f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":218},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbc0fcccd1224960bdf4eff360190894",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":218},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/退款详情/u12.png"}},
{
          "id":"3672466f6c32421cbfa542d120eae6e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":791,
              "y":237},
            "size":{
              "width":279,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"589ba5976fdd45cda657372108499731",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":791,
                  "y":237},
                "size":{
                  "width":279,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ec33c8fd2b1a4470826abebf9663aefd":{
      "scriptId":"u0"},
    "3ca630a15b314260a9b4cd503e2ad794":{
      "scriptId":"u1"},
    "4956a6180d4a4782991bbeb8a4739d37":{
      "scriptId":"u2"},
    "0c3d3185b68d49f581b740fb3bad5572":{
      "scriptId":"u3"},
    "8d412e719a7c457b83e6a4977e4087f0":{
      "scriptId":"u4"},
    "9440afccc85143feb3542d5226111131":{
      "scriptId":"u5"},
    "4db81a5e70ae4976a6800a2895327ddb":{
      "scriptId":"u6"},
    "a3bc9192658f46ae8b636f01b992df68":{
      "scriptId":"u7"},
    "bca9a1760565432daf70a407760b491e":{
      "scriptId":"u8"},
    "79c4016af0b248e38dc3a82e0b07e958":{
      "scriptId":"u9"},
    "77894ed23bd74c98aafdf3cb35f8725f":{
      "scriptId":"u10"},
    "feebe2a2ce574a20b93c8731e06b5a00":{
      "scriptId":"u11"},
    "3ce4c342ce8348c6942739d55343ad3d":{
      "scriptId":"u12"},
    "6cdf69b22f3843d48638eea2fb080cb1":{
      "scriptId":"u13"},
    "4b12fa9a812243d0bf346c6978d6e379":{
      "scriptId":"u14"},
    "7c4f5d1a919646c2a4b885cef3b9de77":{
      "scriptId":"u15"},
    "915a41d3c4dc4b4fb819569393a3eb6a":{
      "scriptId":"u16"},
    "2d2020039d1f448fa17f2f8b13c06f4d":{
      "scriptId":"u17"},
    "631783908c134065a6881ee443b0ba88":{
      "scriptId":"u18"},
    "1e0aad7948044c1793d080dcfddd9328":{
      "scriptId":"u19"},
    "474484fb21154038b99ac21b4e47acde":{
      "scriptId":"u20"},
    "54919b90a98c47068b53d4bdaf0f6a39":{
      "scriptId":"u21"},
    "fd2783080b1e4866933c976a1ae88903":{
      "scriptId":"u22"},
    "47c20a8ade7c4e609198f92a07d32fae":{
      "scriptId":"u23"},
    "7a50cbb1bb6342d08baf9a762cba916c":{
      "scriptId":"u24"},
    "59e646e1ecc24f2fb30f8364d7a0e1d8":{
      "scriptId":"u25"},
    "0657c72d1d9447b98e2d13ef9e2e00a3":{
      "scriptId":"u26"},
    "7b576b73754d46ddb4b8074c6316464d":{
      "scriptId":"u27"},
    "51818b133ee845aeace22788d7a249e4":{
      "scriptId":"u28"},
    "2a43243063cc4202b728794b61ee8dfa":{
      "scriptId":"u29"},
    "4816378ea1134331b5472e810733f844":{
      "scriptId":"u30"},
    "f281adcb6268436886999cd4b6c6aeb5":{
      "scriptId":"u31"},
    "0ced5b6726b14b64bd0a6a3711673034":{
      "scriptId":"u32"},
    "4985d1d0771a44c18339bf35f08216aa":{
      "scriptId":"u33"},
    "b6ed962613ba4bf9b6a22219da38f05f":{
      "scriptId":"u34"},
    "d4ebd8ef2b2645c998256e8cd65e3728":{
      "scriptId":"u35"},
    "7d5a0a24e6244d1db098a6581518f973":{
      "scriptId":"u36"},
    "4f76624f61484d819ae7c1f55c134e19":{
      "scriptId":"u37"},
    "264dc07351fa412783300abd29a59242":{
      "scriptId":"u38"},
    "8c14b54b3cc84f34b7952df7fd422fa0":{
      "scriptId":"u39"},
    "958c3024c6644554952dd3a08f21a766":{
      "scriptId":"u40"},
    "d73c4b994a484a15a939616e954f636b":{
      "scriptId":"u41"},
    "ce0aa95b22e342c0845f996b4561ff56":{
      "scriptId":"u42"},
    "05f0fbacf7744796aaeec2a650d8c8ee":{
      "scriptId":"u43"},
    "02c09712e8c6460a978ccc9c9cee1f2a":{
      "scriptId":"u44"},
    "5f6be778f0114e04965dc8d566564ae7":{
      "scriptId":"u45"},
    "866b39e702d346a2a93698351ea737be":{
      "scriptId":"u46"},
    "fb655a51bb8e463cadb98a45883bcc8f":{
      "scriptId":"u47"},
    "e43f1382a4a34820809a375ea17580e9":{
      "scriptId":"u48"},
    "968c34524c764768819c4aa7e45117d8":{
      "scriptId":"u49"},
    "3437ba64e7ff4e0fb822c2e6278d68aa":{
      "scriptId":"u50"},
    "12e7d02259614063bbd00c97c0f36f62":{
      "scriptId":"u51"},
    "889fc76cd0b64fd6ad3098de9ebc11f0":{
      "scriptId":"u52"},
    "291afebf3fde4eec860becfd5c09dab4":{
      "scriptId":"u53"},
    "cb5ce28f7b9c4ea094a1f15aa22f9497":{
      "scriptId":"u54"},
    "05b651f2cf4a46ef97cd771e4d062a29":{
      "scriptId":"u55"},
    "ca92aab5ccdc49638723ac41d0efd848":{
      "scriptId":"u56"},
    "c39bc3d240df4ed3884763bb8e85f914":{
      "scriptId":"u57"},
    "1748acf8d7f94286b903fee310783f42":{
      "scriptId":"u58"},
    "77ccc69f67144ee3b12ccb262f2d6afc":{
      "scriptId":"u59"},
    "6bccc2b121294070ba73567598c67ad9":{
      "scriptId":"u60"},
    "47e9f0c7b95b4578b0f47eeb7d4f3a1a":{
      "scriptId":"u61"},
    "44ad981b70e24a3bad83d843678ab273":{
      "scriptId":"u62"},
    "c27d725c45df42c5b0fa314a834f88ac":{
      "scriptId":"u63"},
    "312565751bac4aed939e85a17bfcdec0":{
      "scriptId":"u64"},
    "6528242168cb4387a5d02ea53e313c5e":{
      "scriptId":"u65"},
    "1b2090b11ac7488395e8eee85cab8fdf":{
      "scriptId":"u66"},
    "44ef0813eaa6412a8362b194234b60a3":{
      "scriptId":"u67"},
    "4a77cbdb44b7413b8d45d648df442978":{
      "scriptId":"u68"},
    "56ab92ed43b244d1a0386647b03d6b5e":{
      "scriptId":"u69"},
    "a77264dd99ea4300a31cbee1aa6e3ca9":{
      "scriptId":"u70"},
    "0ba83242f9f34d39a3e227beb2ea48bb":{
      "scriptId":"u71"},
    "0e462245d17d46b9b96a99e4582fae5e":{
      "scriptId":"u72"},
    "b5b06a23d8a24d07a408cede9b1e49b7":{
      "scriptId":"u73"},
    "2a46401af5284462b14669b4ac0d5ef6":{
      "scriptId":"u74"},
    "e36202778b804f2ca6fef4c0be7ca120":{
      "scriptId":"u75"},
    "c71412d901014056b7f97af3f8151175":{
      "scriptId":"u76"},
    "03ba3c2a76d34697aa951f1cd2b9e294":{
      "scriptId":"u77"},
    "3cb12fc407d24907a26c8ebbb35f26fb":{
      "scriptId":"u78"},
    "c4dca888d8bd444e879815a854a9cfe8":{
      "scriptId":"u79"},
    "f061e825e6114d5995b2232489d0ea45":{
      "scriptId":"u80"},
    "f55669dc33c34a80b7928a10d66da59d":{
      "scriptId":"u81"},
    "f27b3961fba2404aa7db4da0d1e20b73":{
      "scriptId":"u82"},
    "ec8a02a94c9b44f59eca0fa81996508d":{
      "scriptId":"u83"},
    "7d1ebf2a7be34d128e23f5e9428cab23":{
      "scriptId":"u84"},
    "d25425c10e944eb494ed9b6bd2b1943d":{
      "scriptId":"u85"},
    "9246297dac7a4078aba3791835ab36a1":{
      "scriptId":"u86"},
    "0a371fa1f906491fa609cbb3e5a22df2":{
      "scriptId":"u87"},
    "8d920657dc014e84af5131d67e795be7":{
      "scriptId":"u88"},
    "04c04c1ba62a464dbdac97107b39606c":{
      "scriptId":"u89"},
    "0c58c789d63e4917aeee7f65581804c5":{
      "scriptId":"u90"},
    "01c6306f569c493b89b3ebaa90817e54":{
      "scriptId":"u91"},
    "f28a583c2ecc4523aa39999b5c0050b9":{
      "scriptId":"u92"},
    "0802d53bdb524b6b9f7f222de3c4fcd9":{
      "scriptId":"u93"},
    "f0a2a0805c8546ca91e3937b41002cc6":{
      "scriptId":"u94"},
    "055cd494e0dd4148bb9ee30370889055":{
      "scriptId":"u95"},
    "5c94c1c46dca465f85a99bc036217f58":{
      "scriptId":"u96"},
    "b980d320c4d346f18944f4b17946d8cc":{
      "scriptId":"u97"},
    "6a12deb1b90a4ad58622892b231541bf":{
      "scriptId":"u98"},
    "303a6cef632544128b379b272d7d8725":{
      "scriptId":"u99"},
    "570a4c0b4bf74b60a8459e5dd7519fc7":{
      "scriptId":"u100"},
    "a36d743a857047c59949b6557933eddc":{
      "scriptId":"u101"},
    "f075bf59898544c1afbbf4d59bf10a03":{
      "scriptId":"u102"},
    "4e53b815e2414ebc8b23bb65ef96147c":{
      "scriptId":"u103"},
    "a767dd065e714283975f5ee618c80f43":{
      "scriptId":"u104"},
    "ae112251c9474bcf881f10d551c2b19b":{
      "scriptId":"u105"},
    "c6d1b962471c48d684c66c2f2df48f8b":{
      "scriptId":"u106"},
    "117cbcb950a04b3a8f0a70db8f9853f7":{
      "scriptId":"u107"},
    "bbc0fcccd1224960bdf4eff360190894":{
      "scriptId":"u108"},
    "3672466f6c32421cbfa542d120eae6e2":{
      "scriptId":"u109"},
    "589ba5976fdd45cda657372108499731":{
      "scriptId":"u110"}}});