$axure.loadCurrentPage({
  "url":"就餐主页（集团员工）.html",
  "generationDate":new Date(1448611751188.32),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"tplb_img",
"jdt_bfb",
"qsjs_r",
"tpcc_wz",
"tpcc_zt",
"tpcc_kd",
"yz_msg"],
  "page":{
    "packageId":"5774ae7e6c9146aa94a5dad6f17bd8ba",
    "type":"Axure:Page",
    "name":"就餐主页（集团员工）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"89fa103d54d94541b09339ba17177e7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":320,
              "height":568},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"785cdc13af9b4713acad28516a08d87c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":320,
                  "height":568},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u0.png"}},
{
          "id":"424b879b8d9f42a49fedcb93948618b0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":20},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e478aa25cc97405188066c29e1008625",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":20},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u2.png"}},
{
          "id":"d2edd828b7fb4db493476f2089bbe53c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":35},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b118ab125c96493a99fabdf739fc024d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":35},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u4.png"}},
{
          "id":"52ba70de16704dfbbd0a3bbdde40a649",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":136,
              "y":46},
            "size":{
              "width":95,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ce2726b21824e20806bcc0561301605",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":136,
                  "y":46},
                "size":{
                  "width":95,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7440345fde5463e80a147e28db994f4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":48},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"514d510af27641eab86d758418c5d559",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":48},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u8.png"}},
{
          "id":"bf77be660e3f4af284fb27260ce9af2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":50,
              "y":230},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a345afa7ba9469a82549524cdc97cdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":50,
                  "y":230},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u10.png"}},
{
          "id":"ea3713a1e41b401991d6e23cc24a3ffe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":200,
              "y":230},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d0b848474ae4848908fb421d595d5a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":200,
                  "y":230},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u10.png"}},
{
          "id":"8712c32121b3442c83e91736e7de7097",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":50},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c77806e2064a44689a5de74de6cbb673",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":50},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 券列表",
                      "target":{
                        "targetType":"page",
                        "url":"券列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "89fa103d54d94541b09339ba17177e7a":{
      "scriptId":"u0"},
    "785cdc13af9b4713acad28516a08d87c":{
      "scriptId":"u1"},
    "424b879b8d9f42a49fedcb93948618b0":{
      "scriptId":"u2"},
    "e478aa25cc97405188066c29e1008625":{
      "scriptId":"u3"},
    "d2edd828b7fb4db493476f2089bbe53c":{
      "scriptId":"u4"},
    "b118ab125c96493a99fabdf739fc024d":{
      "scriptId":"u5"},
    "52ba70de16704dfbbd0a3bbdde40a649":{
      "scriptId":"u6"},
    "5ce2726b21824e20806bcc0561301605":{
      "scriptId":"u7"},
    "f7440345fde5463e80a147e28db994f4":{
      "scriptId":"u8"},
    "514d510af27641eab86d758418c5d559":{
      "scriptId":"u9"},
    "bf77be660e3f4af284fb27260ce9af2e":{
      "scriptId":"u10"},
    "9a345afa7ba9469a82549524cdc97cdc":{
      "scriptId":"u11"},
    "ea3713a1e41b401991d6e23cc24a3ffe":{
      "scriptId":"u12"},
    "7d0b848474ae4848908fb421d595d5a4":{
      "scriptId":"u13"},
    "8712c32121b3442c83e91736e7de7097":{
      "scriptId":"u14"},
    "c77806e2064a44689a5de74de6cbb673":{
      "scriptId":"u15"}}});