$axure.loadCurrentPage({
  "url":"退款详情_1.html",
  "generationDate":new Date(1448611753095.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"tplb_img",
"jdt_bfb",
"qsjs_r",
"tpcc_wz",
"tpcc_zt",
"tpcc_kd",
"yz_msg"],
  "page":{
    "packageId":"f5752ea039f347299a9a3824d48bb74a",
    "type":"Axure:Page",
    "name":"退款详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a1fe8578be52434ab7acd68d7890e321",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":410,
              "y":92},
            "size":{
              "width":320,
              "height":568},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"898b6fef4bef4eacb024fa82106dbc7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":410,
                  "y":92},
                "size":{
                  "width":320,
                  "height":568},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u0.png"}},
{
          "id":"ce9e607a8ddc44b08bc925b0cb89e1ad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":417,
              "y":92},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"646db3eaed784d0080a4a0a9193c0aee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":417,
                  "y":92},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u2.png"}},
{
          "id":"679ac3a965df47938d91d89234e67fe8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":107},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdcaa994586742e6972f671005842b68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":107},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u4.png"}},
{
          "id":"b8d8ee5b84ab40c6b7e967cea261a5e5",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":522,
              "y":118},
            "size":{
              "width":138,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33c14f0011594abda74abc68366675e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":522,
                  "y":118},
                "size":{
                  "width":138,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c910d841cbbb48d1b4d2022b0a3dfd20",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":421,
              "y":120},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b1e63b50fcd4014af47b818c33b837d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":421,
                  "y":120},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u8.png"}},
{
          "id":"475269a59fb44f2db399bc73c9fcf792",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":282},
            "size":{
              "width":320,
              "height":163},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"417e5119577b4cf9b6143de4e60cf8c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":282},
                "size":{
                  "width":320,
                  "height":163},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/退款详情/u10.png"}},
{
          "id":"62ff2a23622240d59bd86f569294d432",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":163},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7e5168fac8046b990ff6eee6cb1b9cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":163},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/退款详情/u12.png"}},
{
          "id":"377d89e7c8ff48358cc0e38d75b9711b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":421,
              "y":180},
            "size":{
              "width":169,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f4803aa7b884be19d824b78c2bb8321",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":421,
                  "y":180},
                "size":{
                  "width":169,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c61c454f14f34f06bbee1a63325ff662",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":659,
              "y":180},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e7b4cbd36034274928681bf66df8a35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":659,
                  "y":180},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fe9f70985ef47f9a8a0259304915cc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":298},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbc98bbe9fbb4ec5ae4060972dc7bf4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":425,
                  "y":298},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c946f9619e64431bc4db38a90e8234c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":421,
              "y":319},
            "size":{
              "width":298,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/退款详情/u20_line.png"}},
{
          "id":"429922370a79496192f625d6c78bbc32",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":445,
              "y":398},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3acca2d7940a418d994855350567cf1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":445,
                  "y":398},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba7336bc6cd642048b57fafd59737307",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":445,
              "y":414},
            "size":{
              "width":90,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c4da032806648f19e32a0d90914d414",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":445,
                  "y":414},
                "size":{
                  "width":90,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84516555642a411d8511b19fe4ffd1fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":445,
              "y":356},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d87c7ca46b5747aba68f74f419df7ce8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":445,
                  "y":356},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3288a95ea5f402692fa5c96f9968dd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":445,
              "y":372},
            "size":{
              "width":90,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65e2a2374a5b4ab5ad872fa78e6ca2f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":445,
                  "y":372},
                "size":{
                  "width":90,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f305855390b2436dab154ffd579cb75a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":385},
            "size":{
              "width":10,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/退款详情/u29_end.png",
            "line~":"images/退款详情/u29_line.png"}},
{
          "id":"533a382a5c7a4e5a83065c642dcd02ef",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":340},
            "size":{
              "width":10,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/退款详情/u30_end.png",
            "line~":"images/退款详情/u30_line.png"}},
{
          "id":"db7327bfef964b999974fb11753f5d33",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":223},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8709f9798894a45bec54bfd0dbaec51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":223},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/退款详情/u12.png"}},
{
          "id":"1e8d4d0ac5984525ad95da7c2f494570",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":421,
              "y":234},
            "size":{
              "width":304,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d6c38d472704d8b9671f3275209ab79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":421,
                  "y":234},
                "size":{
                  "width":304,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c833e31979cc4ce881ada0b8894a967a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":40,
              "y":92},
            "size":{
              "width":320,
              "height":568},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed5e50736077452fa008219160b84845",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":40,
                  "y":92},
                "size":{
                  "width":320,
                  "height":568},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u0.png"}},
{
          "id":"3e17a6d4fdae4a3097ee440a970554bf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":92},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7905b02527f488bb9f40698c79d86fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":92},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u2.png"}},
{
          "id":"1c814e6a8ff24f6598cf336f02437eb7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":107},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bafec82175d44575b2069eec0dc2d900",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":107},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u4.png"}},
{
          "id":"6748e5cfa8ab49f4817fb2e194fb80d7",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":152,
              "y":118},
            "size":{
              "width":138,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fc857b7e960467cbe0419b4298fc8d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":152,
                  "y":118},
                "size":{
                  "width":138,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e2330bed1a64a24af03dd52c9345059",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":120},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e9c81dfc1304eccaeace475d578a50c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":120},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u8.png"}},
{
          "id":"609acdb0277241918c08ebde7a8c30ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":282},
            "size":{
              "width":320,
              "height":118},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7174f1bbeabb453d805a6412d143d998",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":282},
                "size":{
                  "width":320,
                  "height":118},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/退款详情/u45.png"}},
{
          "id":"8663e47ae676448b92ac38c12a9e7c82",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":163},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a6c52f8f78a44259888c46677c29c5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":163},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/退款详情/u12.png"}},
{
          "id":"2153fb9b8375479987d8580574513e4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":180},
            "size":{
              "width":169,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff2bc7b70089424383527a0db3e93815",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":180},
                "size":{
                  "width":169,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7d905c3f1674abc95aa528293222b12",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":289,
              "y":180},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0002de03405a43fab5df929059b1af8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":289,
                  "y":180},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95277fc824ae4d94964f3e64ef32535c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":298},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6f3c17494cc441587e3c8ce7ea264c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":298},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1c9b3be195e4eddbc7e648342c3577a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":319},
            "size":{
              "width":298,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/退款详情/u20_line.png"}},
{
          "id":"539697b115084698a0c975066155cc22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":356},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f7516aadda34f7b879356fa25d8254a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":356},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73432d395e5945aca786b32761a956d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":75,
              "y":372},
            "size":{
              "width":90,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cb0616a818d46e891b0b1507cf8f01c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":75,
                  "y":372},
                "size":{
                  "width":90,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04dc17ffe51440ffb7ded1b728960893",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":348},
            "size":{
              "width":10,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/退款详情/u29_end.png",
            "line~":"images/退款详情/u29_line.png"}},
{
          "id":"528a447d3081440980bc7d291adc3e16",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":223},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0af966ab42b8457c87ddd405680feb7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":223},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/退款详情/u12.png"}},
{
          "id":"87681db1458e47c5968c9c76e1eab9de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":51,
              "y":240},
            "size":{
              "width":279,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf56988ac9a248d5aad86b99195b0941",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":51,
                  "y":240},
                "size":{
                  "width":279,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aaf5b383cd3e411d8ea5b941483d9d3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":45},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96d1540dccfa4f8181fbbb3290c5c6ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":45},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f5cffc052d54a18a9421fa841f2f4de",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":45},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4b6f674bdf447e8a4cb8b01278abfb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":45},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22c57bed12254c228641ce8393fa86e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":40},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f43324791c2642e4a3d101ac51acf8b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":40},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"653524f970374b8181b18fb0b4ff5e7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":780,
              "y":87},
            "size":{
              "width":320,
              "height":568},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"701c132b2ccf48cf86ed7c0919b3f844",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":780,
                  "y":87},
                "size":{
                  "width":320,
                  "height":568},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u0.png"}},
{
          "id":"8a502e93c2dc490a929097011889cb5e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":787,
              "y":87},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92f1168ac6794e399defa7f515d0205e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":787,
                  "y":87},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u2.png"}},
{
          "id":"4d336fa02bef4734acec9fe6749924d2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":102},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43fbabf1a5d3447d8de0ffa082b93d34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":102},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u4.png"}},
{
          "id":"34627a53d0f441a2a30c63d4cb5e1d4e",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":892,
              "y":113},
            "size":{
              "width":138,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ff3e01d25b34d17ba77173d2a3fc04c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":892,
                  "y":113},
                "size":{
                  "width":138,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4c5476679c04c578e6ecd9200c0dffd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":115},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e61626a6920c49c8a04a5a6e9dc34b9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":791,
                  "y":115},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/就餐主页（集团员工）/u8.png"}},
{
          "id":"aceda0790ef84c54b25b5e4be9b6c166",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":277},
            "size":{
              "width":320,
              "height":210},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fa8405676b6483cb669687694f6e0db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":277},
                "size":{
                  "width":320,
                  "height":210},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/退款详情/u81.png"}},
{
          "id":"30e97297341c45778bbe2f0a8ef1dd11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":158},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95cd0aadc6cb4331be8e54ac87f0c502",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":158},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/退款详情/u12.png"}},
{
          "id":"b046427f6a5e4129955b9c513eafc039",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":175},
            "size":{
              "width":169,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a5b25fea13a455fbeab1f25a050a8e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":791,
                  "y":175},
                "size":{
                  "width":169,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44c0637eff28490d9e69d97f07ccd4c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":1029,
              "y":175},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b804ac1af02d42eb908f0ad359776292",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":1029,
                  "y":175},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d85f14932588423ba0980ff56163c42a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":795,
              "y":293},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"238cca557c9941a1824e325316979654",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":795,
                  "y":293},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0dedd455793e4eac9b70333c3035b1a1",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":795,
              "y":377},
            "size":{
              "width":10,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/退款详情/u30_end.png",
            "line~":"images/退款详情/u30_line.png"}},
{
          "id":"1e7fc7701a23464f8d9cc2b43b808e71",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":314},
            "size":{
              "width":298,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/退款详情/u20_line.png"}},
{
          "id":"cf6c4e6acff14d38858eeeca902c89c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":815,
              "y":393},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8d232d309034b3db61bebd6d2a65813",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":815,
                  "y":393},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49140955b5464f4186ba80596dd61a5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":815,
              "y":409},
            "size":{
              "width":90,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d306d850e654f20b25f9e6d4aed07eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":815,
                  "y":409},
                "size":{
                  "width":90,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"367d4dfe79a74cdd8bebcff9f9866cbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":815,
              "y":351},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70afcb22f4bb4aaa93aa35a2ba979241",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":815,
                  "y":351},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eae53ea3cea44ddd8e98bd5a33ead53c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":815,
              "y":367},
            "size":{
              "width":90,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bf0e24ee8d54ba7a817eabee9eced06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":815,
                  "y":367},
                "size":{
                  "width":90,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"906184d8037049d2a07f2e6957bb66db",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":795,
              "y":421},
            "size":{
              "width":10,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/退款详情/u29_end.png",
            "line~":"images/退款详情/u29_line.png"}},
{
          "id":"d41d09201ccf40c5aca1d24f8d0006de",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":795,
              "y":335},
            "size":{
              "width":10,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/退款详情/u30_end.png",
            "line~":"images/退款详情/u30_line.png"}},
{
          "id":"c440657ed79c4eb3a9774d267e419f4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":815,
              "y":429},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f348c674a8514415a1c8df1acba7563f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":815,
                  "y":429},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c642568de4b34d409738543da1c21376",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":815,
              "y":447},
            "size":{
              "width":90,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63b8a3347d6d4aada2d5981f45ff519e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":815,
                  "y":447},
                "size":{
                  "width":90,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20f6d5e7134f482bbc7ce741f03e9448",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":218},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"501c60c519c04cd7841370201098afe1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":218},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/退款详情/u12.png"}},
{
          "id":"0569b64cd3104dc383f749f0e80dc806",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":791,
              "y":237},
            "size":{
              "width":279,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00f01cce969f4f7e9661af4f0a503be3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":791,
                  "y":237},
                "size":{
                  "width":279,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "a1fe8578be52434ab7acd68d7890e321":{
      "scriptId":"u0"},
    "898b6fef4bef4eacb024fa82106dbc7e":{
      "scriptId":"u1"},
    "ce9e607a8ddc44b08bc925b0cb89e1ad":{
      "scriptId":"u2"},
    "646db3eaed784d0080a4a0a9193c0aee":{
      "scriptId":"u3"},
    "679ac3a965df47938d91d89234e67fe8":{
      "scriptId":"u4"},
    "bdcaa994586742e6972f671005842b68":{
      "scriptId":"u5"},
    "b8d8ee5b84ab40c6b7e967cea261a5e5":{
      "scriptId":"u6"},
    "33c14f0011594abda74abc68366675e9":{
      "scriptId":"u7"},
    "c910d841cbbb48d1b4d2022b0a3dfd20":{
      "scriptId":"u8"},
    "4b1e63b50fcd4014af47b818c33b837d":{
      "scriptId":"u9"},
    "475269a59fb44f2db399bc73c9fcf792":{
      "scriptId":"u10"},
    "417e5119577b4cf9b6143de4e60cf8c8":{
      "scriptId":"u11"},
    "62ff2a23622240d59bd86f569294d432":{
      "scriptId":"u12"},
    "a7e5168fac8046b990ff6eee6cb1b9cd":{
      "scriptId":"u13"},
    "377d89e7c8ff48358cc0e38d75b9711b":{
      "scriptId":"u14"},
    "6f4803aa7b884be19d824b78c2bb8321":{
      "scriptId":"u15"},
    "c61c454f14f34f06bbee1a63325ff662":{
      "scriptId":"u16"},
    "5e7b4cbd36034274928681bf66df8a35":{
      "scriptId":"u17"},
    "0fe9f70985ef47f9a8a0259304915cc1":{
      "scriptId":"u18"},
    "cbc98bbe9fbb4ec5ae4060972dc7bf4f":{
      "scriptId":"u19"},
    "6c946f9619e64431bc4db38a90e8234c":{
      "scriptId":"u20"},
    "429922370a79496192f625d6c78bbc32":{
      "scriptId":"u21"},
    "3acca2d7940a418d994855350567cf1f":{
      "scriptId":"u22"},
    "ba7336bc6cd642048b57fafd59737307":{
      "scriptId":"u23"},
    "3c4da032806648f19e32a0d90914d414":{
      "scriptId":"u24"},
    "84516555642a411d8511b19fe4ffd1fb":{
      "scriptId":"u25"},
    "d87c7ca46b5747aba68f74f419df7ce8":{
      "scriptId":"u26"},
    "c3288a95ea5f402692fa5c96f9968dd8":{
      "scriptId":"u27"},
    "65e2a2374a5b4ab5ad872fa78e6ca2f8":{
      "scriptId":"u28"},
    "f305855390b2436dab154ffd579cb75a":{
      "scriptId":"u29"},
    "533a382a5c7a4e5a83065c642dcd02ef":{
      "scriptId":"u30"},
    "db7327bfef964b999974fb11753f5d33":{
      "scriptId":"u31"},
    "c8709f9798894a45bec54bfd0dbaec51":{
      "scriptId":"u32"},
    "1e8d4d0ac5984525ad95da7c2f494570":{
      "scriptId":"u33"},
    "4d6c38d472704d8b9671f3275209ab79":{
      "scriptId":"u34"},
    "c833e31979cc4ce881ada0b8894a967a":{
      "scriptId":"u35"},
    "ed5e50736077452fa008219160b84845":{
      "scriptId":"u36"},
    "3e17a6d4fdae4a3097ee440a970554bf":{
      "scriptId":"u37"},
    "e7905b02527f488bb9f40698c79d86fb":{
      "scriptId":"u38"},
    "1c814e6a8ff24f6598cf336f02437eb7":{
      "scriptId":"u39"},
    "bafec82175d44575b2069eec0dc2d900":{
      "scriptId":"u40"},
    "6748e5cfa8ab49f4817fb2e194fb80d7":{
      "scriptId":"u41"},
    "8fc857b7e960467cbe0419b4298fc8d6":{
      "scriptId":"u42"},
    "7e2330bed1a64a24af03dd52c9345059":{
      "scriptId":"u43"},
    "6e9c81dfc1304eccaeace475d578a50c":{
      "scriptId":"u44"},
    "609acdb0277241918c08ebde7a8c30ad":{
      "scriptId":"u45"},
    "7174f1bbeabb453d805a6412d143d998":{
      "scriptId":"u46"},
    "8663e47ae676448b92ac38c12a9e7c82":{
      "scriptId":"u47"},
    "7a6c52f8f78a44259888c46677c29c5f":{
      "scriptId":"u48"},
    "2153fb9b8375479987d8580574513e4f":{
      "scriptId":"u49"},
    "ff2bc7b70089424383527a0db3e93815":{
      "scriptId":"u50"},
    "c7d905c3f1674abc95aa528293222b12":{
      "scriptId":"u51"},
    "0002de03405a43fab5df929059b1af8b":{
      "scriptId":"u52"},
    "95277fc824ae4d94964f3e64ef32535c":{
      "scriptId":"u53"},
    "d6f3c17494cc441587e3c8ce7ea264c2":{
      "scriptId":"u54"},
    "f1c9b3be195e4eddbc7e648342c3577a":{
      "scriptId":"u55"},
    "539697b115084698a0c975066155cc22":{
      "scriptId":"u56"},
    "9f7516aadda34f7b879356fa25d8254a":{
      "scriptId":"u57"},
    "73432d395e5945aca786b32761a956d9":{
      "scriptId":"u58"},
    "0cb0616a818d46e891b0b1507cf8f01c":{
      "scriptId":"u59"},
    "04dc17ffe51440ffb7ded1b728960893":{
      "scriptId":"u60"},
    "528a447d3081440980bc7d291adc3e16":{
      "scriptId":"u61"},
    "0af966ab42b8457c87ddd405680feb7e":{
      "scriptId":"u62"},
    "87681db1458e47c5968c9c76e1eab9de":{
      "scriptId":"u63"},
    "bf56988ac9a248d5aad86b99195b0941":{
      "scriptId":"u64"},
    "aaf5b383cd3e411d8ea5b941483d9d3b":{
      "scriptId":"u65"},
    "96d1540dccfa4f8181fbbb3290c5c6ec":{
      "scriptId":"u66"},
    "4f5cffc052d54a18a9421fa841f2f4de":{
      "scriptId":"u67"},
    "e4b6f674bdf447e8a4cb8b01278abfb5":{
      "scriptId":"u68"},
    "22c57bed12254c228641ce8393fa86e1":{
      "scriptId":"u69"},
    "f43324791c2642e4a3d101ac51acf8b4":{
      "scriptId":"u70"},
    "653524f970374b8181b18fb0b4ff5e7a":{
      "scriptId":"u71"},
    "701c132b2ccf48cf86ed7c0919b3f844":{
      "scriptId":"u72"},
    "8a502e93c2dc490a929097011889cb5e":{
      "scriptId":"u73"},
    "92f1168ac6794e399defa7f515d0205e":{
      "scriptId":"u74"},
    "4d336fa02bef4734acec9fe6749924d2":{
      "scriptId":"u75"},
    "43fbabf1a5d3447d8de0ffa082b93d34":{
      "scriptId":"u76"},
    "34627a53d0f441a2a30c63d4cb5e1d4e":{
      "scriptId":"u77"},
    "6ff3e01d25b34d17ba77173d2a3fc04c":{
      "scriptId":"u78"},
    "e4c5476679c04c578e6ecd9200c0dffd":{
      "scriptId":"u79"},
    "e61626a6920c49c8a04a5a6e9dc34b9d":{
      "scriptId":"u80"},
    "aceda0790ef84c54b25b5e4be9b6c166":{
      "scriptId":"u81"},
    "7fa8405676b6483cb669687694f6e0db":{
      "scriptId":"u82"},
    "30e97297341c45778bbe2f0a8ef1dd11":{
      "scriptId":"u83"},
    "95cd0aadc6cb4331be8e54ac87f0c502":{
      "scriptId":"u84"},
    "b046427f6a5e4129955b9c513eafc039":{
      "scriptId":"u85"},
    "8a5b25fea13a455fbeab1f25a050a8e5":{
      "scriptId":"u86"},
    "44c0637eff28490d9e69d97f07ccd4c5":{
      "scriptId":"u87"},
    "b804ac1af02d42eb908f0ad359776292":{
      "scriptId":"u88"},
    "d85f14932588423ba0980ff56163c42a":{
      "scriptId":"u89"},
    "238cca557c9941a1824e325316979654":{
      "scriptId":"u90"},
    "0dedd455793e4eac9b70333c3035b1a1":{
      "scriptId":"u91"},
    "1e7fc7701a23464f8d9cc2b43b808e71":{
      "scriptId":"u92"},
    "cf6c4e6acff14d38858eeeca902c89c9":{
      "scriptId":"u93"},
    "b8d232d309034b3db61bebd6d2a65813":{
      "scriptId":"u94"},
    "49140955b5464f4186ba80596dd61a5c":{
      "scriptId":"u95"},
    "7d306d850e654f20b25f9e6d4aed07eb":{
      "scriptId":"u96"},
    "367d4dfe79a74cdd8bebcff9f9866cbe":{
      "scriptId":"u97"},
    "70afcb22f4bb4aaa93aa35a2ba979241":{
      "scriptId":"u98"},
    "eae53ea3cea44ddd8e98bd5a33ead53c":{
      "scriptId":"u99"},
    "6bf0e24ee8d54ba7a817eabee9eced06":{
      "scriptId":"u100"},
    "906184d8037049d2a07f2e6957bb66db":{
      "scriptId":"u101"},
    "d41d09201ccf40c5aca1d24f8d0006de":{
      "scriptId":"u102"},
    "c440657ed79c4eb3a9774d267e419f4f":{
      "scriptId":"u103"},
    "f348c674a8514415a1c8df1acba7563f":{
      "scriptId":"u104"},
    "c642568de4b34d409738543da1c21376":{
      "scriptId":"u105"},
    "63b8a3347d6d4aada2d5981f45ff519e":{
      "scriptId":"u106"},
    "20f6d5e7134f482bbc7ce741f03e9448":{
      "scriptId":"u107"},
    "501c60c519c04cd7841370201098afe1":{
      "scriptId":"u108"},
    "0569b64cd3104dc383f749f0e80dc806":{
      "scriptId":"u109"},
    "00f01cce969f4f7e9661af4f0a503be3":{
      "scriptId":"u110"}}});